Repository menloresearch/jan, pull requests merged in 2023-10, with the labels that each got.

#289 add electron artifactName
  .github/workflows/linter-and-test.yml
  electron/package.json
Labels: P1: important

#293 fix(nitro): Update metal file from llama.cpp f56e1ba
  electron/core/plugins/inference-plugin/nitro/ggml-metal.metal
Labels: P0: critical

#280 docs: update per v0.1.3
  README.md
  docs/src/components/Elements/dropdown.js
  docs/src/components/Homepage/downloads.js
  docs/src/components/Homepage/hero.js
Labels: P1: important, type: documentation

#311 Add auto update app download url on jan.ai
  .github/workflows/deploy-jan-docs.yml
  .github/workflows/jan-docs-test.yml
  docs/package.json
  docs/src/components/Elements/dropdown.js
  docs/yarn.lock
Labels: P1: important, type: documentation

#240 docs: initial hardware content
  docs/docs/hardware/concepts/concepts-images/GPU.png
  docs/docs/hardware/concepts/concepts-images/GPU_Image.png
  docs/docs/hardware/concepts/concepts-images/PCIex16.png
  docs/docs/hardware/concepts/concepts-images/Power.png
  docs/docs/hardware/concepts/concepts-images/RAM-VRAM.png
  docs/docs/hardware/concepts/concepts-images/VRAM-Image.png
  docs/docs/hardware/concepts/concepts-images/slot.png
  docs/docs/hardware/concepts/gpu-and-vram.md
  docs/docs/hardware/examples/4090x2-@dan-jan.md
  docs/docs/hardware/hardware.md
  docs/docs/hardware/overview/cloud-vs-buy.md
  docs/docs/hardware/overview/cloud-vs-self-hosting.md
  docs/docs/hardware/overview/cpu-vs-gpu.md
  docs/docs/hardware/recommendations/by-budget.md
  docs/docs/hardware/recommendations/by-hardware.md
  docs/docs/hardware/recommendations/by-model.md
  docs/docs/hardware/recommendations/by-usecase.md
  docs/package.json
  docs/sidebars.js
  docs/yarn.lock
Labels: documentation

#316 Fix icon error for linux app
  .github/workflows/linter-and-test.yml
  electron/icons/icon.png
  electron/package.json
Labels: P1: important

#322 Add release note template
  .github/release-drafter.yml
Labels: type: chore

#323 Chore/release note template
  .github/workflows/build-app.yml
Labels: type: ci, type: chore

#332 Add Documentation category to release note template
  .github/release-drafter.yml
Labels: type: ci, type: chore

#333 Fix #290: Add description in package.json and rename to jan
  README.md
  electron/package.json
  electron/tests/main.e2e.spec.ts
  package-lock.json
  package.json
Labels: type: bug

#354 chore: jan.ai nits
  docs/docusaurus.config.js
  docs/src/components/Homepage/hero.js
  docs/src/pages/index.js
  docs/yarn.lock
Labels: P1: important, type: chore

#363 Update yarn script for build plugins
  electron/core/plugins/data-plugin/package-lock.json
  electron/core/plugins/data-plugin/package.json
  electron/core/plugins/inference-plugin/package-lock.json
  electron/core/plugins/inference-plugin/package.json
  electron/core/plugins/model-management-plugin/package-lock.json
  electron/core/plugins/model-management-plugin/package.json
  electron/core/plugins/openai-plugin/package-lock.json
  electron/core/plugins/openai-plugin/package.json
  package.json
Labels: type: chore

#367 Fix error check change in plugins folder
  .github/workflows/publish-plugins.yml
Labels: type: ci

#262 Feat/issue 255 adr 001 jand cloud native
  adr/adr-001-jan-deployable-cloud-native.md
  adr/adr-template.md
  adr/images/adr-001-01.png
  adr/images/adr-001-02.png
Labels: P1: important

#370 Rename plugin-core to core
  .github/workflows/publish-plugin-core.yml
  core/README.md
  core/core.ts
  core/events.ts
  core/index.ts
  core/package-lock.json
  core/package.json
  core/preferences.ts
  core/store.ts
  core/tsconfig.json
  core/types/index.d.ts
Labels: type: chore

#374 Correct version of plugins
  .github/workflows/publish-plugin-core.yml
  plugins/data-plugin/package-lock.json
  plugins/data-plugin/package.json
  plugins/inference-plugin/package-lock.json
  plugins/inference-plugin/package.json
  plugins/model-management-plugin/package-lock.json
  plugins/model-management-plugin/package.json
  plugins/monitoring-plugin/package-lock.json
  plugins/monitoring-plugin/package.json
  plugins/openai-plugin/package.json
Labels: type: bug, type: ci, type: chore

#397 Refactor cicd
  .github/workflows/jan-docs-test.yml
  .github/workflows/jan-docs.yml
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  .github/workflows/jan-plugin-core.yml
  .github/workflows/jan-plugins.yml
  .github/workflows/quality-gate.yml
  plugins/data-plugin/package-lock.json
  plugins/data-plugin/package.json
  plugins/inference-plugin/package-lock.json
  plugins/inference-plugin/package.json
  plugins/model-management-plugin/package-lock.json
  plugins/model-management-plugin/package.json
  plugins/monitoring-plugin/package-lock.json
  plugins/monitoring-plugin/package.json
  plugins/openai-plugin/package.json
  yarn.lock
Labels: type: ci

#398 Chore/remove package lock
  .github/workflows/jan-docs.yml
  .gitignore
  core/package-lock.json
  docs/package-lock.json
  package-lock.json
  plugins/data-plugin/package-lock.json
  plugins/data-plugin/package.json
  plugins/inference-plugin/package-lock.json
  plugins/inference-plugin/package.json
  plugins/model-management-plugin/package-lock.json
  plugins/model-management-plugin/package.json
  plugins/monitoring-plugin/package-lock.json
  plugins/monitoring-plugin/package.json
  plugins/openai-plugin/package-lock.json
  plugins/openai-plugin/package.json
  yarn.lock
Labels: type: chore

#413 Fix data-plugin install failed on mac silicon from npm
  .github/workflows/jan-plugins.yml
  plugins/data-plugin/package.json
Labels: type: bug, type: chore

#425 Add username to remote origin
  .github/workflows/jan-plugins.yml
Labels: type: ci

#433 Update code siging for new data plugin
  .github/scripts/auto-sign.sh
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-plugins.yml
  electron/auto-sign.sh
  package.json
Labels: type: ci

#440 Change codesign plugin folder in ci
  .github/workflows/jan-electron-build.yml
Labels: type: chore

#445 Update auto-sign plugin by search file permission 664
  .github/scripts/auto-sign.sh
Labels: type: chore

#447 upgrade leveldown to newest version
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-plugins.yml
  plugins/data-plugin/package.json
Labels: type: ci

#451 Change to load nitron on windows and linux from bash/shell script
  plugins/inference-plugin/module.ts
  plugins/inference-plugin/nitro/nitro_start_linux.sh
  plugins/inference-plugin/nitro/nitro_start_windows.bat
Labels: type: bug

#453 data-plugin force leveldown to 6.1.1
  .github/workflows/jan-plugins.yml
  plugins/data-plugin/README.md
  plugins/data-plugin/package.json
Labels: type: bug, type: chore

#454 data-plugin force leveldown back to 5.6.0 and rebuild for darwin arm64
  plugins/data-plugin/README.md
  plugins/data-plugin/package.json
Labels: type: chore

#455 Use electron-rebuild to build leveldown@5.6.0 for darwin arm64
  plugins/data-plugin/package.json
Labels: type: chore

#472 Add build deps for data-plugin in CI
  .github/workflows/jan-plugins.yml
Labels: type: ci, type: chore

#473 add rebuild for mac x64
  plugins/data-plugin/README.md
  plugins/data-plugin/package.json
Labels: type: bug

#450 docs: new dev hub
  docs/docs/about/about.md
  docs/docs/about/brand-assets.md
  docs/docs/about/team.md
  docs/docs/apps/azure-openai.md
  docs/docs/apps/data.md
  docs/docs/apps/inference.md
  docs/docs/apps/model-management.md
  docs/docs/apps/monitoring.md
  docs/docs/apps/rag.md
  docs/docs/changelog/README.md
  docs/docs/docs/docs.md
  docs/docs/docs/install/mac.md
  docs/docs/docs/install/windows.md
  docs/docs/getting-started/app-anatomy.md
  docs/docs/getting-started/build-an-app.md
  docs/docs/getting-started/cloud-native.md
  docs/docs/getting-started/img/app-anatomy-1.drawio.jpg
  docs/docs/getting-started/img/app-anatomy-2.drawio.jpg
  docs/docs/getting-started/img/app-anatomy-3.drawio.jpg
  docs/docs/getting-started/img/app-anatomy-4.drawio.jpg
  docs/docs/getting-started/img/app-anatomy-5.drawio.png
  docs/docs/getting-started/img/architecture-0.drawio.png
  docs/docs/getting-started/img/architecture-1.drawio.png
  docs/docs/getting-started/img/architecture.png
  docs/docs/getting-started/img/build-app-1.png
  docs/docs/getting-started/img/cloudnative.png
  docs/docs/getting-started/nitro.md
  docs/docs/getting-started/publish-jan-app.md
  docs/docs/guides/concepts.md
  docs/docs/guides/linux.md
  docs/docs/guides/mac.md
  docs/docs/guides/troubleshooting.md
  docs/docs/guides/windows.md
  docs/docs/platform/platform.md
  docs/docs/products/desktop.md
  docs/docs/products/mobile.md
  docs/docs/products/products.md
  docs/docs/products/server.md
  docs/docs/reference/01_init.md
  docs/docs/reference/02_coreservice.md
  docs/docs/reference/03_events.md
  docs/docs/reference/04_store.md
  docs/docs/reference/05_filesystem.md
  docs/docs/reference/06_preferences.md
  docs/docs/solutions/industries/education.md
  docs/docs/solutions/industries/finance.md
  docs/docs/solutions/industries/healthcare.md
  docs/docs/solutions/industries/law.md
  docs/docs/solutions/industries/public-sector.md
  docs/docs/solutions/industries/software.md
  docs/docs/solutions/personal-ai.md
  docs/docs/solutions/self-hosted.md
  docs/docs/solutions/solutions.md
  docs/docs/tutorials/build-chat-app.md
  docs/docs/tutorials/build-rag-app.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/styles/base.scss
  docs/src/styles/tweaks.scss
  plugins/data-plugin/package.json
Labels: P0: critical

#487 Add rebuild leveldown for arm on mac intel
  plugins/data-plugin/README.md
  plugins/data-plugin/package.json
Labels: type: bug

#320 #255: Jan cloud native
  .dockerignore
  Dockerfile
  electron/core/plugin-manager/execution/facade.js
  package.json
  plugins/data-plugin/module.ts
  plugins/inference-plugin/module.ts
  plugins/inference-plugin/nitro/nitro_start_linux.sh
  plugins/model-management-plugin/index.ts
  server/main.ts
  server/nodemon.json
  server/package.json
  server/tsconfig.json
  web/app/_components/SidebarFooter/index.tsx
  web/app/page.tsx
  web/containers/Providers/index.tsx
  web/containers/Sidebar/Left.tsx
  web/helpers/EventHandler.tsx
  web/next.config.js
  web/package.json
  web/screens/Settings/CorePlugins/PluginsCatalog.tsx
  web/services/cloudNativeService.ts
  web/services/coreService.ts
  web/types/index.d.ts
Labels: P1: important
