Repository menloresearch/jan, pull requests merged in 2023-12, with the labels that each got.

#739 docs/update-api-reference
  docs/docusaurus.config.js
  docs/openapi/jan.yaml
  docs/openapi/specs/assistant.yaml
  docs/openapi/specs/chat.yaml
  docs/openapi/specs/messages.yaml
  docs/openapi/specs/models.yaml
  docs/openapi/specs/threads.yaml
  docs/src/styles/base.scss
Labels: type: documentation, type: enhancement

#800 Remove .zip in artifact name
  .github/workflows/jan-electron-build-nightly.yml
Labels: type: chore

#796 feat: pre-populate Jan's /models folder
  .gitignore
  core/src/core.ts
  core/src/extensions/model.ts
  core/src/fs.ts
  core/src/types/index.ts
  electron/handlers/app.ts
  electron/handlers/download.ts
  electron/handlers/extension.ts
  electron/handlers/fs.ts
  electron/handlers/update.ts
  electron/invokers/fs.ts
  electron/main.ts
  electron/managers/extension.ts
  electron/managers/module.ts
  electron/package.json
  electron/utils/path.ts
  extensions/inference-extension/src/index.ts
  extensions/model-extension/src/@types/global.d.ts
  extensions/model-extension/src/@types/schema.ts
  extensions/model-extension/src/helpers/modelParser.ts
  extensions/model-extension/src/index.ts
  extensions/model-extension/webpack.config.js
  package.json
  web/containers/ItemCardSidebar/index.tsx
  web/containers/Layout/BottomBar/DownloadingState/index.tsx
  web/containers/Layout/TopBar/CommandSearch/index.tsx
  web/containers/ModalCancelDownload/index.tsx
  web/containers/Providers/EventListener.tsx
  web/hooks/useActiveModel.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useDeleteConversation.ts
  web/hooks/useDownloadModel.ts
  web/hooks/useDownloadState.ts
  web/hooks/useGetConfiguredModels.ts
  web/hooks/useGetMostSuitableModelVersion.ts
  web/hooks/useGetPerformanceTag.ts
  web/hooks/useSendChatMessage.ts
  web/hooks/useSetActiveThread.ts
  web/screens/Chat/MessageToolbar/index.tsx
  web/screens/Chat/Sidebar/index.tsx
  web/screens/ExploreModels/ExploreModelItem/index.tsx
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
  web/screens/ExploreModels/ExploreModelList/index.tsx
  web/screens/ExploreModels/ModelVersionItem/index.tsx
  web/screens/MyModels/BlankState/index.tsx
  web/screens/MyModels/index.tsx
  web/screens/Settings/index.tsx
  web/types/downloadState.d.ts
  web/utils/dummy.ts
Labels: type: chore

#819 fix: CI script - reorder copy models action
  package.json
Labels: type: bug

#818 fix/docusaurus-seo
  docs/docs/about/about.md
  docs/docs/community/community.md
  docs/docs/docs/assistants.md
  docs/docs/docs/extensions.md
  docs/docs/docs/models.md
  docs/docs/docs/modules.md
  docs/docs/docs/server.md
  docs/docs/docs/themes.md
  docs/docs/docs/tools.md
  docs/docs/handbook/engineering/engineering.md
  docs/docs/handbook/handbook.md
  docs/docs/hardware/community.md
  docs/docs/install/from-source.md
  docs/docs/install/linux.md
  docs/docs/install/mac.md
  docs/docs/install/overview.md
  docs/docs/install/windows.md
  docs/docs/intro/how-jan-works.md
  docs/docs/intro/introduction.md
  docs/docs/intro/quickstart.md
  docs/docs/specs/architecture.md
  docs/docs/specs/engineering/assistants.md
  docs/docs/specs/engineering/chats.md
  docs/docs/specs/engineering/files.md
  docs/docs/specs/engineering/fine-tuning.md
  docs/docs/specs/engineering/messages.md
  docs/docs/specs/engineering/models.md
  docs/docs/specs/engineering/prompts.md
  docs/docs/specs/engineering/threads.md
  docs/docs/specs/file-based.md
  docs/docs/specs/jan.md
  docs/docs/specs/product/chat.md
  docs/docs/specs/product/hub.md
  docs/docs/specs/product/settings.md
  docs/docs/specs/product/system-monitor.md
  docs/docs/specs/user-interface.md
  docs/docusaurus.config.js
  docs/src/pages/index.js
  docs/static/robots.txt
Labels: type: bug

#831 Add document for nightly build and update message for manual build
  .github/workflows/jan-electron-build-nightly.yml
  README.md
Labels: type: chore

#832 Switch to download nitro .tar.gz file instead of .zip file on windows
  extensions/inference-extension/download.bat
Labels: type: bug

#803 feat: boilerplate for express server localhost 1337
  server/.gitignore
  server/data/.gitkeep
  server/data/models/.gitkeep
  server/data/threads/.gitkeep
  server/icons/icon.png
  server/lib/.gitkeep
  server/main.ts
  server/nodemon.json
  server/package.json
  server/tsconfig.json
  server/v1/assistants/index.ts
  server/v1/chat/index.ts
  server/v1/index.ts
  server/v1/models/downloadModel.ts
  server/v1/models/index.ts
  server/v1/models/modelOp.ts
  server/v1/threads/index.ts
Labels: type: feature request

#846 bug: fix broken banner position hub screen
  web/screens/ExploreModels/index.tsx
Labels: type: bug

#855 fix: empty assistant instruction by default
  electron/handlers/update.ts
  extensions/assistant-extension/src/index.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/MessageToolbar/index.tsx
Labels: type: bug

#861 fix: update wrong main view state when use a model
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Labels: type: bug

#862 fix: production CI workflow does not populate models
  package.json
Labels: type: bug

#867 fix: can not download multiple models at once
  web/containers/Providers/EventListener.tsx
  web/helpers/atoms/Model.atom.ts
  web/hooks/useDownloadModel.ts
  web/hooks/useDownloadState.ts
  web/hooks/useSendChatMessage.ts
Labels: type: bug

#869 fix: delete message break the entire thread
  extensions/conversational-extension/src/index.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/MessageToolbar/index.tsx
Labels: type: bug

#872 feat : add cover image model hub screen
  core/src/types/index.ts
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Labels: type: enhancement

#874 chore: update model ranking
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
  web/screens/ExploreModels/ExploreModelList/index.tsx
  web/screens/ExploreModels/index.tsx
Labels: type: chore

#877 fix: Nitro interface update to prevent warning
  extensions/inference-extension/src/module.ts
Labels: P1: important, type: bug

#883 fix: download button text color is blending into the background
  docs/src/containers/DownloadApp/index.js
Labels: type: bug

#884 bug: update metadata title and desc
  docs/docusaurus.config.js
  docs/src/pages/index.js
  docs/static/img/og-image.png
Labels: type: bug

#899 bug: fix syntax formatting
  web/screens/Chat/SimpleTextMessage/index.tsx
Labels: type: bug

#840 docs: add json schema for engine and model parameters
  docs/openapi/specs/models.yaml
Labels: P0: critical, type: discussion, type: documentation, type: enhancement, mlops

#801 docs: add assistants api reference
  docs/docs/specs/engineering/assistants.md
  docs/openapi/jan.yaml
  docs/openapi/specs/assistant.yaml
  docs/openapi/specs/assistants.yaml
  docs/openapi/specs/chat.yaml
  docs/openapi/specs/messages.yaml
  docs/openapi/specs/models.yaml
  docs/openapi/specs/threads.yaml
Labels: P1: important, type: documentation

#934 [bug] Fix floating border outside card right panel
  web/containers/CardSidebar/index.tsx
Labels: type: bug

#933 docs: standardize yaml files
  docs/docusaurus.config.js
  docs/openapi/jan.yaml
  docs/openapi/specs/assistants.yaml
  docs/openapi/specs/chat.yaml
  docs/openapi/specs/messages.yaml
  docs/openapi/specs/models.yaml
  docs/openapi/specs/threads.yaml
Labels: type: documentation

#924 refactor: deprecate invokers - auto proxying apis - strict types
  core/src/api/index.ts
  core/src/core.ts
  core/src/index.ts
  electron/handlers/app.ts
  electron/handlers/download.ts
  electron/handlers/extension.ts
  electron/handlers/fs.ts
  electron/handlers/theme.ts
  electron/handlers/update.ts
  electron/invokers/app.ts
  electron/invokers/download.ts
  electron/invokers/extension.ts
  electron/invokers/fs.ts
  electron/main.ts
  electron/package.json
  electron/preload.ts
  web/containers/Providers/EventHandler.tsx
  web/containers/Providers/index.tsx
  web/extension/ExtensionManager.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useGetAppVersion.ts
  web/screens/Settings/CoreExtensions/ExtensionsCatalog/index.tsx
  web/types/index.d.ts
Labels: type: chore

#935 fix: model parameters for inference extensions
  extensions/inference-nitro-extension/src/helpers/sse.ts
  extensions/inference-openai-extension/src/helpers/sse.ts
  models/gpt-3.5-turbo-16k-0613/model.json
  models/gpt-4/model.json
Labels: P1: important, type: bug

#940 CI automatically update Update README with Nightly Build Information and stable download URL
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-linter-and-test.yml
  .github/workflows/update-release-url.yml
  README.md
  docs/static/img/linux.png
  docs/static/img/mac.png
  docs/static/img/windows.png
Labels: type: ci, type: chore

#941 Fix update release url pipeline
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/update-release-url.yml
  README.md
Labels: type: ci, type: chore

#942 chore: Bumpt nitro bin version to version 0.1.23
  extensions/inference-nitro-extension/bin/version.txt
Labels: P1: important, type: ci, type: chore

#886 feat: adding model params
  core/src/types/index.ts
  extensions/assistant-extension/src/index.ts
  extensions/inference-nitro-extension/src/helpers/sse.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-openai-extension/src/helpers/sse.ts
  uikit/package.json
  uikit/src/index.ts
  uikit/src/input/styles.scss
  uikit/src/main.scss
  uikit/src/slider/index.tsx
  uikit/src/slider/styles.scss
  web/containers/CardSidebar/index.tsx
  web/containers/Checkbox/index.tsx
  web/containers/DropdownListSidebar/index.tsx
  web/containers/Layout/TopBar/index.tsx
  web/containers/Providers/EventHandler.tsx
  web/containers/Slider/index.tsx
  web/helpers/atoms/ChatMessage.atom.ts
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useActiveModel.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useDeleteThread.ts
  web/hooks/useGetAllThreads.ts
  web/hooks/useGetConfiguredModels.ts
  web/hooks/useSendChatMessage.ts
  web/hooks/useSetActiveThread.ts
  web/hooks/useUpdateModelParameters.ts
  web/package.json
  web/screens/Chat/MessageToolbar/index.tsx
  web/screens/Chat/ModelSetting/index.tsx
  web/screens/Chat/ModelSetting/predefinedComponent.ts
  web/screens/Chat/ModelSetting/settingComponentBuilder.tsx
  web/screens/Chat/Sidebar/index.tsx
  web/screens/Chat/ThreadList/index.tsx
  web/screens/Chat/index.tsx
  web/utils/thread.ts
Labels: type: feature request

#931 feat: Hotfit for Nitro loading on CPU with hyper-threading support
  core/src/types/index.ts
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/@types/global.d.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/module.ts
  extensions/inference-openai-extension/src/index.ts
Labels: P0: critical, type: enhancement, type: feature request

#947 Fix update release url pipeline run failed
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/update-release-url.yml
Labels: type: ci

#949 fix: windows bug - control buttons close,max,min hidden
  electron/managers/window.ts
Labels: type: bug

#951 Update update-release-url.yml
  .github/workflows/update-release-url.yml
Labels: type: ci

#958 Fix error Jan app linux crash
  electron/package.json
Labels: P0: critical, type: bug

#960 chore: Bump nitro to 0.1.26
  extensions/inference-nitro-extension/bin/version.txt
Labels: P1: important, type: chore

#888 feat: Add NVIDIA triton trt-llm extension
  core/src/types/index.ts
  extensions/inference-triton-trtllm-extension/README.md
  extensions/inference-triton-trtllm-extension/package.json
  extensions/inference-triton-trtllm-extension/src/@types/global.d.ts
  extensions/inference-triton-trtllm-extension/src/helpers/sse.ts
  extensions/inference-triton-trtllm-extension/src/index.ts
  extensions/inference-triton-trtllm-extension/tsconfig.json
  extensions/inference-triton-trtllm-extension/webpack.config.js
Labels: P1: important, type: feature request

#950 fix: Inference engine Nitro with Windows with/ without CUDA
  .gitignore
Labels: P0: critical, type: bug

#856 docs: scaffold dev docs
  docs/docs/docs/01-overview.md
  docs/docs/docs/02-get-started/01-build-extension.md
  docs/docs/docs/02-get-started/02-extension-anatomy.md
  docs/docs/docs/02-get-started/03-use-local-server.md
  docs/docs/docs/02-get-started/04-build-on-desktop.md
  docs/docs/docs/02-get-started/05-build-on-mobile.md
  docs/docs/docs/02-get-started/README.md
  docs/docs/docs/03-extension-capabilities/01-Core.md
  docs/docs/docs/03-extension-capabilities/02-common-extensions.md
  docs/docs/docs/03-extension-capabilities/README.md
  docs/docs/docs/04-extension-guides/README.md
  docs/docs/docs/04-extension-guides/assistant.md
  docs/docs/docs/04-extension-guides/inference.md
  docs/docs/docs/04-extension-guides/model.md
  docs/docs/docs/04-extension-guides/monitoring.md
  docs/docs/docs/04-extension-guides/threads-messages.md
  docs/docs/docs/05-UI/README.md
  docs/docs/docs/assistants.md
  docs/docs/docs/extensions.md
  docs/docs/docs/modules.md
  docs/docs/docs/themes.md
  docs/docs/docs/tools.md
  docs/docs/guides/how-jan-works.md
  docs/docs/guides/introduction.md
  docs/docs/guides/models.md
  docs/docs/guides/quickstart.md
  docs/docs/guides/server.md
  docs/sidebars.js
Labels: type: documentation

#966 refactor: clean types and interfaces
  core/src/events.ts
  core/src/extensions/assistant.ts
  core/src/extensions/conversational.ts
  core/src/extensions/inference.ts
  core/src/extensions/model.ts
  core/src/extensions/monitoring.ts
  core/src/types/assistant/assistantEntity.ts
  core/src/types/assistant/assistantInterface.ts
  core/src/types/assistant/index.ts
  core/src/types/index.ts
  core/src/types/inference/index.ts
  core/src/types/inference/inferenceEntity.ts
  core/src/types/inference/inferenceEvent.ts
  core/src/types/inference/inferenceInterface.ts
  core/src/types/message/index.ts
  core/src/types/message/messageEntity.ts
  core/src/types/message/messageEvent.ts
  core/src/types/message/messageInterface.ts
  core/src/types/model/index.ts
  core/src/types/model/modelEntity.ts
  core/src/types/model/modelEvent.ts
  core/src/types/model/modelInterface.ts
  core/src/types/monitoring/index.ts
  core/src/types/monitoring/monitoringInterface.ts
  core/src/types/thread/index.ts
  core/src/types/thread/threadEntity.ts
  core/src/types/thread/threadInterface.ts
Labels: type: chore

#952 feat: Inference Nitro with Prompt Template
  core/src/types/model/modelEntity.ts
  extensions/inference-nitro-extension/src/module.ts
  models/capybara-34b/model.json
  models/deepseek-coder-1.3b/model.json
  models/deepseek-coder-34b/model.json
  models/llama2-chat-70b-q4/model.json
  models/llama2-chat-7b-q4/model.json
  models/llama2-chat-7b-q5/model.json
  models/lzlv-70b/model.json
  models/mistral-ins-7b-q4/model.json
  models/mistral-ins-7b-q5/model.json
  models/neural-chat-7b/model.json
  models/noromaid-20b/model.json
  models/openhermes-neural-7b/model.json
  models/openorca-13b/model.json
  models/phind-34b/model.json
  models/rocket-3b/model.json
  models/starling-7b/model.json
  models/tiefighter-13b/model.json
  models/tinyllama-1.1b/model.json
  models/wizardcoder-13b/model.json
  models/yi-34b/model.json
  models/zephyr-beta-7b/model.json
  web/hooks/useActiveModel.ts
Labels: P1: important, type: enhancement, type: feature request

#974 fix: 963 can not run openai models on windows
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-triton-trtllm-extension/src/index.ts
  web/hooks/useCreateNewThread.ts
Labels: type: bug

#975 feat: Kill nitro process with API - nitro 0.1.27
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/src/module.ts
Labels: P0: critical, type: enhancement, type: feature request

#978 chore: add desktop app analytics
  web/containers/Providers/index.tsx
  web/next.config.js
  web/package.json
  web/types/index.d.ts
  web/utils/posthog.ts
Labels: type: chore

#986 fix: remove coming soon windows
  docs/src/containers/DownloadApp/index.js
Labels: type: enhancement

#993 fix: enable download app linux
  docs/src/containers/DownloadApp/index.js
Labels: type: bug, type: enhancement

#945 feat: loader when starting model
  web/containers/Loader/ModelStart.tsx
  web/screens/Chat/index.tsx
Labels: type: feature request

#991 feat: adding API support at 1337
  electron/api/index.ts
  electron/api/models/index.ts
  electron/main.ts
  electron/package.json
Labels: type: feature request

#1000 fix: review finder and view as json
  electron/handlers/app.ts
Labels: type: bug

#1001 fix: wrong selected model right panel
  web/containers/DropdownListSidebar/index.tsx
Labels: type: bug

#1011 feat: move stop inference button into the send button
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-openai-extension/src/index.ts
  web/screens/Chat/MessageToolbar/index.tsx
  web/screens/Chat/index.tsx
Labels: type: feature request

#1012 fix: limit analytics events capture
  web/utils/posthog.ts
Labels: type: bug

#1009 fix: #995 - Fix onboarding state and model sorting
  core/src/types/model/modelEntity.ts
  web/containers/DropdownListSidebar/index.tsx
  web/screens/Chat/ChatBody/index.tsx
Labels: type: bug

#1014 feat: app theme depend on local storage instead native theme electron
  core/src/api/index.ts
  electron/handlers/app.ts
  web/containers/Layout/index.tsx
  web/screens/Settings/Appearance/ToggleTheme.tsx
Labels: type: feature request

#1015 fix: delete first message then regenerate again will break the thread
  extensions/conversational-extension/src/index.ts
Labels: type: bug

#1019 fix bug #1013, enable posthog for release app version only
  .github/workflows/jan-electron-build.yml
  web/next.config.js
Labels: type: bug, type: ci

#1020 docs: how to import models
  docs/docs/guides/quickstart.md
Labels: type: documentation

#1021 docs: second half of "import model docs" PR
  docs/docs/guides/quickstart.md
Labels: type: documentation

#1022 Update posthog capture url list
  web/utils/posthog.ts
Labels: type: chore

#1029 Separate posthog project for jan app and docs
  .github/workflows/jan-electron-build.yml
Labels: type: chore

#1030 chore: read engine.json for openai chat_completion
  electron/api/models/index.ts
  extensions/model-extension/src/index.ts
Labels: type: chore

#1032 chore: in app copy fixes
  extensions/assistant-extension/package.json
  extensions/conversational-extension/package.json
  extensions/inference-nitro-extension/package.json
  extensions/inference-openai-extension/package.json
  extensions/inference-triton-trtllm-extension/package.json
  extensions/model-extension/package.json
  extensions/monitoring-extension/package.json
  web/screens/ExploreModels/index.tsx
  web/screens/Settings/Advanced/index.tsx
Labels: type: chore

#1036 bump nitro version to 0.1.30
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#1038 chore: remigrate if there is no models dir
  extensions/model-extension/src/index.ts
Labels: type: chore

#965 Enhancements to Dependency Installation and App Testing
  .github/workflows/jan-electron-linter-and-test.yml
  Makefile
Labels: P1: important, type: feature request

#1061 fix: thread is broken after deleted first generated message
  extensions/conversational-extension/src/index.ts
Labels: type: bug

#1047 docs: improve quickstart docs
  docs/docs/guides/how-jan-works.md
  docs/docs/guides/models.md
  docs/docs/guides/models.mdx
  docs/docs/guides/quickstart.md
  docs/docs/guides/quickstart.mdx
  docs/docs/handbook/engineering.md
  docs/docs/handbook/handbook.md
  docs/docs/handbook/onboarding.md
  docs/docs/handbook/product.md
  docs/sidebars.js
Labels: type: documentation

#1060 Posthog disable click event and increase timeout for nitro load model…
  extensions/inference-nitro-extension/src/module.ts
  web/utils/posthog.ts
Labels: type: chore

#1066 docs: Update product.md
  docs/docs/handbook/product.md
Labels: type: documentation

#1062 feat: copy button for code block
  web/hooks/useClipboard.ts
  web/screens/Chat/MessageToolbar/index.tsx
  web/screens/Chat/SimpleTextMessage/index.tsx
Labels: type: feature request

#1073 Fix nightly build autoupdater
  .github/workflows/jan-electron-build-nightly.yml
Labels: type: ci

#1085 fix: system monitor broken layout when responsive
  web/screens/SystemMonitor/index.tsx
Labels: type: bug

#1102 Fix auto update windows Bug
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build.yml
  electron/package.json
  electron/sign.js
Labels: type: bug

#1099 fix: #1097 streaming response is replaced by error message
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-openai-extension/src/index.ts
Labels: type: bug

#1104 Correct jq command cause ci nightly build run failed
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build.yml
Labels: type: ci, type: chore

#1106 fix: search recommended model
  web/screens/ExploreModels/index.tsx
Labels: type: bug

#1105 fix: update copy setting page
  web/screens/Settings/Appearance/index.tsx
Labels: type: bug

#1111 fix: toaster success deleted thread showing id instead of active model
  web/hooks/useDeleteThread.ts
Labels: type: bug

#1109 fix: #1096 yield error message upon thread switching
  core/src/types/message/messageEntity.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-triton-trtllm-extension/src/index.ts
  web/containers/Providers/EventHandler.tsx
  web/hooks/useSetActiveThread.ts
  web/screens/Chat/ChatBody/index.tsx
  web/screens/Chat/MessageToolbar/index.tsx
  web/screens/Chat/SimpleTextMessage/index.tsx
Labels: type: bug

#1110 fix: model active indicator only show when model activated
  web/containers/Layout/BottomBar/index.tsx
Labels: type: bug

#1114 fix: handle chat completion state with enter button
  web/screens/Chat/index.tsx
Labels: type: bug

#1113 fix: remote model always active badges
  web/screens/Settings/Models/Row.tsx
Labels: type: bug

#1115 fix: added tooltip for user cannot change model after starting thread
  web/containers/DropdownListSidebar/index.tsx
Labels: type: bug

#1116 fix: should not hide empty message away
  web/screens/Chat/ChatBody/index.tsx
Labels: type: bug

#1120 fix: ui issue - all models are activated
  web/screens/Settings/Models/Row.tsx
Labels: type: bug

#1124 fix: remove remote model from shortcut models dialog
  web/containers/Layout/TopBar/CommandListDownloadedModel/index.tsx
Labels: type: bug

#1142 fix: added dialog confirmation clean thread
  web/screens/Chat/ThreadList/index.tsx
Labels: type: bug

#1157 Fix token speed slow in machine has multi gpus
  extensions/inference-nitro-extension/bin/linux-start.sh
  extensions/inference-nitro-extension/bin/win-start.bat
Labels: type: bug

#1128 feat: Add codeQL analysis for push main and pr main
  .github/workflows/codeQL-analysis.yml
  docs/src/containers/Banner/index.js
  docs/src/containers/Footer/index.js
  extensions/inference-openai-extension/src/@types/global.d.ts
  extensions/inference-openai-extension/src/helpers/sse.ts
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-openai-extension/webpack.config.js
Labels: P2: nice to have, type: feature request, type: ci, type: chore

#1153 fix: error road map url
  docs/docs/handbook/product.md
  docs/src/pages/index.js
Labels: type: bug

#1122 docs: Update 01-start-thread.md
  docs/docs/guides/03-chatting/01-start-thread.md
Labels: type: documentation

#1167 chore: copy fixes
  web/containers/DropdownListSidebar/index.tsx
  web/screens/Chat/ChatBody/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/SystemMonitor/index.tsx
Labels: type: chore

#1169 docs: add troubleshooting
  docs/docs/guides/02-installation/01-mac.md
  docs/docs/guides/02-installation/03-linux.md
  docs/docs/guides/07-troubleshooting/01-stuck-on-broken-build.mdx
  docs/docs/guides/07-troubleshooting/README.md
Labels: type: documentation, roadmap: Jan Docs

#1186 fix: darkmode broken color
  web/app/layout.tsx
  web/containers/Layout/index.tsx
  web/screens/Chat/index.tsx
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
  web/screens/Settings/index.tsx
  web/screens/SystemMonitor/index.tsx
Labels: type: bug, roadmap: UIKit & Design System

#1180 docs: update bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: documentation, type: chore, roadmap: Jan Internal Processes

#1173 docs: improve troubleshoot documentation
  docs/docs/guides/02-installation/01-mac.md
  docs/docs/guides/02-installation/02-windows.md
  docs/docs/guides/02-installation/03-linux.md
  docs/docs/guides/07-troubleshooting/01-stuck-on-broken-build.mdx
Labels: type: documentation, roadmap: Jan Docs

#1209 feat: temporary link how to import model
  web/screens/ExploreModels/index.tsx
Labels: P0: critical, type: feature request, roadmap: Jan Hub

#1214 Fix switch thread crash nitro windows linux
  extensions/inference-nitro-extension/bin/linux-start.sh
  extensions/inference-nitro-extension/bin/win-start.bat
  extensions/inference-nitro-extension/src/module.ts
Labels: type: bug

#1215 add sleep 500ms if platform is windows before starting nitro process
  extensions/inference-nitro-extension/src/module.ts
Labels: type: chore

#1197 docs: Update 02-import-manually.mdx
  docs/docs/guides/04-using-models/02-import-manually.mdx
Labels: P0: critical, type: documentation

#1229 chore: Update issue templates
  .github/ISSUE_TEMPLATE/epic-request.md
Labels: type: chore

#1222 docs: improve 02-import-manually
  docs/docs/guides/04-using-models/02-import-manually.mdx
  docs/docs/guides/04-using-models/assets/download-model.png
Labels: type: documentation, roadmap: Jan Docs

#1226 feat: users should be able to switch models mid-thread
  web/containers/DropdownListSidebar/index.tsx
  web/hooks/useSendChatMessage.ts
Labels: type: feature request

#1225 fix: Cleared thread last message is not updated
  web/hooks/useDeleteThread.ts
Labels: type: bug

#1218 fix: enable enter command on dialog confirmation delete thread
  web/screens/Chat/ThreadList/index.tsx
Labels: type: bug

#1217 fix: remove delay tooltip and click event
  web/containers/DropdownListSidebar/index.tsx
  web/containers/Providers/index.tsx
Labels: type: bug

#1239 fix: #1183 Reveal in finder does not work on windows
  core/src/api/index.ts
  core/src/core.ts
  electron/handlers/app.ts
  web/containers/CardSidebar/index.tsx
  web/next.config.js
  web/screens/Chat/Sidebar/index.tsx
  web/screens/Settings/CoreExtensions/ExtensionsCatalog/index.tsx
  web/types/index.d.ts
Labels: type: bug

#1238 feat: Deprecate model.json ready state in favor of .download ext
  core/src/types/model/modelEntity.ts
  electron/handlers/download.ts
  extensions/conversational-extension/src/index.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/module.ts
  extensions/model-extension/src/index.ts
  web/containers/Layout/BottomBar/DownloadingState/index.tsx
  web/containers/ModalCancelDownload/index.tsx
  web/containers/Providers/EventListener.tsx
  web/hooks/useDownloadModel.ts
  web/hooks/useEngineSettings.ts
  web/screens/Chat/ChatBody/index.tsx
  web/utils/model.ts
  web/utils/model_param.ts
Labels: type: feature request

#1241 Fix bug #1178 high ram on windows
  extensions/inference-nitro-extension/src/module.ts
  extensions/monitoring-extension/src/module.ts
Labels: type: bug

#1252 fix: engine settings GUI - feature toggle
  web/screens/Chat/Sidebar/index.tsx
Labels: type: bug

#1254 fix: remove redundant gpu detection prompt event
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-openai-extension/src/index.ts
  web/containers/Providers/EventHandler.tsx
Labels: type: bug

#1255 fix: mac users should not see GPU settings
  web/containers/Providers/index.tsx
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#1213 Adding new model to the Hub
  extensions/model-extension/package.json
  models/codeninja-1.0-7b/model.json
  models/magicoder-s-ds-7b/model.json
  models/stealth-v1.2-7b/model.json
  models/trinity-v1-7b/model.json
Labels: P2: nice to have

#1258 feat: update posthog configuration
  web/utils/posthog.ts
Labels: type: feature request

#1259 fix: input message duplicated due with some input sources
  web/screens/Chat/index.tsx
Labels: type: bug

#1261 fix: enable command enter on dialog confirmation clean thread
  web/screens/Chat/ThreadList/index.tsx
Labels: type: bug

#1266 Fix wrong linux nitro path
  extensions/inference-nitro-extension/bin/linux-start.sh
  extensions/inference-nitro-extension/bin/win-start.bat
  extensions/inference-nitro-extension/src/module.ts
Labels: type: bug

#1267 fix ci test run failed
  extensions/inference-nitro-extension/package.json
Labels: type: bug

#1268 feat: add swagger /docs to localhost:1337
  docs/docs/guides/05-using-server/01-server.md
  docs/openapi/jan.yaml
  server/index.ts
  server/package.json
Labels: type: feature request

#1274 fix: support markdown break line
  web/styles/components/message.scss
Labels: type: bug
