Repository menloresearch/jan, pull requests merged in 2023-11, with the labels that each got.

#525 feat: Experimental Feature Toggle
  electron/main.ts
  electron/preload.ts
  electron/tests/navigation.e2e.spec.ts
  web/app/_components/LeftHeaderAction/index.tsx
  web/containers/Providers/index.tsx
  web/containers/Sidebar/Left.tsx
  web/helpers/FeatureToggleWrapper.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/CorePlugins/PluginsCatalog.tsx
  web/screens/Settings/index.tsx
Labels: P1: important, type: feature request

#529 Chore/update yarn dev script
  package.json
  plugins/inference-plugin/package.json
Labels: type: chore

#532 Bump nitro version to 0.1.4
  plugins/inference-plugin/nitro/version.txt
  plugins/inference-plugin/package.json
Labels: type: chore

#542 Add install nitro mac intel inference plugin build locally
  plugins/inference-plugin/package.json
Labels: type: chore

#576 Fix build plugins macos codesiging error
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  package.json
Labels: type: ci

#578 Fix error CI e2e run failed on windows
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  package.json
  plugins/inference-plugin/package.json
Labels: type: ci

#579 Add set yarn network timeout for uikit
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  plugins/inference-plugin/package.json
Labels: type: ci

#581 Bump nitro version from 0.1.4 to 0.1.6
  plugins/inference-plugin/nitro/version.txt
Labels: type: chore

#615 Chore/refactor yarn script
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  .github/workflows/jan-plugin-core.yml
  .github/workflows/jan-plugins.yml
  package.json
  plugins/conversational-json/package.json
  plugins/conversational-plugin/package.json
  plugins/inference-plugin/package.json
  plugins/model-plugin/package.json
  plugins/monitoring-plugin/package.json
  server/main.ts
  server/nodemon.json
  server/package.json
  server/tsconfig.json
Labels: type: chore

#617 Restore cpx nitro step in yarn script
  plugins/inference-plugin/package.json
Labels: type: bug

#625 Refactor Jan Documentation
  docs/docs/about/about.md
  docs/docs/docs/specs/assistants.md
  docs/docs/docs/specs/chats.md
  docs/docs/docs/specs/files.md
  docs/docs/docs/specs/messages.md
  docs/docs/docs/specs/models.md
  docs/docs/docs/specs/threads.md
  docs/docs/getting-started/img/chat.png
  docs/docs/getting-started/img/downloading.png
  docs/docs/getting-started/img/explore-model.png
  docs/docs/getting-started/img/jan-download.png
  docs/docs/getting-started/img/model-catelog.png
  docs/docs/getting-started/img/model-version.png
  docs/docs/getting-started/img/set-up.png
  docs/docs/getting-started/img/start-model.png
  docs/docs/getting-started/img/window-defender.png
  docs/docs/getting-started/install/linux.md
  docs/docs/getting-started/install/mac.md
  docs/docs/getting-started/install/windows.md
  docs/docs/getting-started/troubleshooting.md
  docs/docs/guides/overview.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: type: documentation, type: chore

#620 Add run-script-os
  .github/scripts/auto-sign.sh
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  electron/package.json
  package.json
  plugins/inference-plugin/package.json
Labels: type: chore

#598 refactor: move file to jan root
  core/src/events.ts
  core/src/fs.ts
  core/src/index.ts
  core/src/types/index.ts
  electron/.prettierrc
  electron/handlers/download.ts
  electron/handlers/fs.ts
  electron/handlers/plugin.ts
  electron/handlers/update.ts
  electron/main.ts
  electron/managers/plugin.ts
  electron/preload.ts
  plugins/conversational-json/package.json
  plugins/conversational-json/src/index.ts
  plugins/conversational-json/webpack.config.js
  plugins/conversational-plugin/src/index.ts
  plugins/inference-plugin/src/index.ts
  plugins/inference-plugin/src/module.ts
  plugins/model-plugin/.prettierrc
  plugins/model-plugin/package.json
  plugins/model-plugin/src/helpers/cloudNative.ts
  plugins/model-plugin/src/helpers/modelParser.ts
  plugins/model-plugin/src/index.ts
  plugins/model-plugin/webpack.config.js
  web/containers/Layout/BottomBar/index.tsx
  web/containers/Layout/TopBar/CommandListDownloadedModel/index.tsx
  web/containers/ModalCancelDownload/index.tsx
  web/containers/Providers/EventHandler.tsx
  web/containers/Providers/EventListener.tsx
  web/helpers/atoms/ChatMessage.atom.ts
  web/helpers/atoms/Conversation.atom.ts
  web/hooks/useActiveModel.ts
  web/hooks/useCreateConversation.ts
  web/hooks/useDeleteConversation.ts
  web/hooks/useDeleteModel.ts
  web/hooks/useDownloadModel.ts
  web/hooks/useGetInputState.ts
  web/hooks/useGetUserConversations.ts
  web/hooks/useSendChatMessage.ts
  web/models/ChatMessage.ts
  web/screens/Chat/ChatItem/index.tsx
  web/screens/Chat/HistoryList/index.tsx
  web/screens/Chat/SimpleTextMessage/index.tsx
  web/screens/Chat/index.tsx
  web/screens/ExploreModels/ExploreModelItem/index.tsx
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
  web/screens/ExploreModels/ExploreModelList/index.tsx
  web/screens/ExploreModels/ModelVersionItem/index.tsx
  web/screens/ExploreModels/ModelVersionList/index.tsx
  web/screens/MyModels/index.tsx
  web/services/coreService.ts
  web/types/chatMessage.d.ts
  web/utils/dummy.ts
  web/utils/message.ts
Labels: type: chore

#629 Update README.md
  README.md
Labels: type: documentation

#641 Model specs
  docs/docs/docs/specs/models.md
Labels: P1: important, type: documentation, type: chore

#649 Fix: specs revision
  docs/docs/docs/specs/architecture.md
  docs/docs/docs/specs/assistants.md
  docs/docs/docs/specs/chats.md
  docs/docs/docs/specs/files.md
  docs/docs/docs/specs/fine-tuning.md
  docs/docs/docs/specs/messages.md
  docs/docs/docs/specs/models.md
  docs/docs/docs/specs/threads.md
Labels: P0: critical, type: discussion, type: documentation

#655 Preliminary Restructure of Docs
  docs/docs/events/nvidia-llm-day-nov-23.md
  docs/docs/features/acceleration.md
  docs/docs/features/ai-models.md
  docs/docs/features/control.md
  docs/docs/features/extensions.md
  docs/docs/features/features.md
  docs/docs/features/unlimited.md
  docs/docs/getting-started/troubleshooting.md
  docs/docs/guide/assistants.md
  docs/docs/guide/models.md
  docs/docs/guide/modules.md
  docs/docs/guide/server.md
  docs/docs/guide/themes.md
  docs/docs/guide/tools.md
  docs/docs/install/linux.md
  docs/docs/install/mac.md
  docs/docs/install/windows.md
  docs/docs/intro/how-jan-works.md
  docs/docs/intro/introduction.md
  docs/docs/intro/quickstart.md
  docs/docs/specs/architecture.md
  docs/docs/specs/assistants.md
  docs/docs/specs/chats.md
  docs/docs/specs/data-structures.md
  docs/docs/specs/files.md
  docs/docs/specs/fine-tuning.md
  docs/docs/specs/jan.md
  docs/docs/specs/messages.md
  docs/docs/specs/models.md
  docs/docs/specs/threads.md
  docs/docs/specs/user-interface.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/static/img/chat.png
  docs/static/img/downloading.png
  docs/static/img/explore-model.png
  docs/static/img/jan-download.png
  docs/static/img/jan-views.png
  docs/static/img/model-catelog.png
  docs/static/img/model-version.png
  docs/static/img/set-up.png
  docs/static/img/start-model.png
  docs/static/img/window-defender.png
  docs/yarn.lock
Labels: type: documentation, type: chore

#623 docs: add OpenAI swagger file
  docs/docusaurus.config.js
  docs/openapi/OpenAIAPI.yaml
  docs/openapi/OpenAPISpec.json
  docs/package.json
Labels: P1: important, type: documentation, type: enhancement, type: chore

#653 bug: fix compatibility content not fully display
  web/screens/ExploreModels/ExploreModelItem/index.tsx
  web/screens/ExploreModels/ModelVersionItem/index.tsx
Labels: type: bug

#652 bug: fix titles should have spaces in between
  web/containers/Layout/TopBar/index.tsx
Labels: type: bug

#668 bug: fix anchor link sidebar openapi
  docs/src/styles/base.scss
Labels: type: bug

#674 Enhance Cross-Platform Argument Handling for Nitro Startup Scripts
  plugins/inference-plugin/nitro/win-start.bat
Labels: type: chore

#673 chore: Update based on team discussion on Nov 20
  docs/docs/specs/models.md
Labels: type: documentation, type: enhancement

#670 chore/update package docs
  docs/docusaurus.config.js
  docs/package.json
  docs/redocly.yaml
  docs/yarn.lock
Labels: type: chore

#672 chore/add-mermaid
  docs/docusaurus.config.js
  docs/package.json
  docs/yarn.lock
Labels: type: chore

#664 docs: update installation guide
  docs/docs/install/from-source.md
  docs/docs/install/linux.md
  docs/docs/install/mac.md
  docs/docs/install/overview.md
  docs/docs/install/windows.md
  docs/sidebars.js
Labels: type: documentation, type: enhancement

#683 bug: fix footer and section spacing landing page
  docs/docusaurus.config.js
  docs/package.json
  docs/src/components/Footer/index.js
  docs/yarn.lock
Labels: type: bug

#687 Add Instruction to publish docs
  docs/README.md
Labels: type: chore

#691 Chore: refactor to makefile
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  Makefile
  README.md
Labels: type: ci, type: chore

#695 bug: fix padding quotations and numbering list
  docs/src/styles/tweaks.scss
Labels: type: bug

#698 Revert docs CICD trigger on push to main instead of tag-based
  .github/workflows/jan-docs.yml
Labels: type: ci, type: chore

#702 Fix error docs pipeline run failed
  .github/workflows/jan-docs.yml
  docs/README.md
Labels: type: ci

#704 [docs] Update Docusaurus to 3.0 and fix closing tag issue in Handbook
  docs/docs/handbook/handbook.md
  docs/docs/install/windows.md
  docs/package.json
  docs/sidebars.js
  docs/yarn.lock
Labels: type: documentation, type: chore

#705 docs: upgrade mdx-js package
  docs/package.json
  docs/yarn.lock
Labels: P2: nice to have, type: chore

#712 Add windows code sign to CI
  .github/workflows/jan-electron-build.yml
  Makefile
Labels: type: enhancement

#679 API Reference for Models, Messages, Threads
  docs/docs/specs/messages.md
  docs/docs/specs/models.md
  docs/docs/specs/threads.md
  docs/docusaurus.config.js
  docs/openapi/jan.yaml
  docs/openapi/specs/messages.yaml
  docs/openapi/specs/models.yaml
  docs/openapi/specs/threads.yaml
Labels: type: documentation, type: chore

#708 docs/improve install docs
  docs/docs/install/linux.md
  docs/docs/install/mac.md
  docs/docs/install/windows.md
  docs/docs/intro/introduction.md
Labels: type: documentation

#706 docs: Refactor Jan Site Structure
  docs/docs/community/community.md
  docs/docs/specs/chats.md
  docs/docs/specs/data-structures.md
  docs/docs/specs/files.md
  docs/docs/specs/home.md
  docs/docs/specs/hub.md
  docs/docs/specs/messages.md
  docs/docs/specs/models.md
  docs/docs/specs/system-monitor.md
  docs/docs/specs/threads.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: P1: important, type: documentation

#707 docs: assistant spec
  docs/docs/specs/assistants.md
  docs/sidebars.js
Labels: P1: important, type: discussion, type: documentation

#722 bug: fix clickable small download button on chat screen
  web/screens/Chat/index.tsx
Labels: type: bug

#723 bug: fix filter list menu from command base on search type and make a symbol base on OS
  uikit/src/command/index.tsx
  web/containers/Layout/BottomBar/index.tsx
  web/containers/Layout/TopBar/CommandListDownloadedModel/index.tsx
  web/containers/Layout/TopBar/CommandSearch/index.tsx
  web/containers/Shortcut/index.tsx
  web/hooks/useOs.ts
  web/screens/Chat/index.tsx
  web/screens/Welcome/index.tsx
Labels: type: bug

#721 chore: app raises error when attempting to start a model that is already starting
  web/hooks/useActiveModel.ts
Labels: type: bug

#720 chore: fs module should not cover app logic
  core/src/core.ts
  core/src/fs.ts
  core/src/index.ts
  plugins/inference-plugin/src/index.ts
Labels: type: chore

#725 docs/enable-seo-docusaurus
  docs/docusaurus.config.js
Labels: type: documentation, type: enhancement

#736 fix: error when switching between threads
  plugins/inference-plugin/src/module.ts
  web/hooks/useActiveModel.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/ChatInstruction/index.tsx
  web/screens/Chat/HistoryList/index.tsx
  web/screens/Chat/index.tsx
Labels: type: bug

#781 Switch from .zip to .tar.gz for nitro url inference plugin
  .github/workflows/jan-electron-build.yml
  Makefile
  plugins/inference-plugin/download.bat
  plugins/inference-plugin/package.json
Labels: type: chore

#788 Fix Makefile Indentation Issue
  Makefile
Labels: type: bug, type: chore

#784 fix: messages sync is not threadsafe
  electron/handlers/fs.ts
  electron/package.json
  web/services/coreService.ts
Labels: type: bug

#794 Add nightly build ci
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build.yml
  electron/package.json
Labels: type: ci, type: chore
