Repository menloresearch/jan, pull requests merged in 2024-01, with the labels that each got.

#1275 feat: added keyboard shortcut list in setting page
  web/containers/Layout/TopBar/CommandSearch/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/index.tsx
Labels: type: enhancement, type: feature request

#1284 fix: swagger CSP issue
  .gitignore
  README.md
  core/src/api/index.ts
  electron/docs/openapi/.gitkeep
  electron/handlers/app.ts
  electron/main.ts
  electron/package.json
  package.json
  server/index.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#1281 docs: update README.md
  README.md
Labels: type: documentation

#1282 Switch from systeminformation to os-utils to resolve Bitdefender false positive and memory leak issue
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/module.ts
  extensions/monitoring-extension/package.json
  extensions/monitoring-extension/src/module.ts
  web/hooks/useGetSystemResources.ts
Labels: P0: critical, type: bug

#1283 fix: posthog configuration
  web/utils/posthog.ts
Labels: P0: critical

#1286 Switch from Gigabyte to Gibibyte - System monitor
  web/containers/DropdownListSidebar/index.tsx
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
  web/screens/ExploreModels/ModelVersionItem/index.tsx
  web/screens/Settings/Models/Row.tsx
  web/screens/SystemMonitor/index.tsx
  web/utils/converter.ts
Labels: type: bug

#1292 fix: user should be able to access Swagger docs from localhost:1337
  server/index.ts
Labels: type: bug

#1287 Refactor CI by create shared jobs output
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build.yml
  Makefile
  README.md
Labels: type: ci

#1294 Enrich discord message for nightly build url
  .github/workflows/jan-electron-build-nightly.yml
  README.md
Labels: type: chore

#1296 fix: disable process logging from server
  core/src/node/index.ts
  core/src/node/log.ts
  server/index.ts
Labels: type: bug

#1297 fix: should check app dir before spawning log
  core/src/node/log.ts
Labels: type: bug

#1298 Fix memory on mac included cached and swap
  extensions/monitoring-extension/package.json
  extensions/monitoring-extension/src/module.ts
  web/hooks/useGetSystemResources.ts
Labels: type: bug, type: chore

#1295 Bring social media links
  electron/main.ts
  web/containers/Layout/Ribbon/index.tsx
Labels: type: enhancement

#1304 chore: github PR template
  .github/pull_request_template.md
Labels: type: chore

#1305 docs: contributor docs overview
  docs/docs/docs/README.md
Labels: type: documentation

#1307 docs: update pm handbook
  docs/docs/handbook/product.md
Labels: type: documentation

#1311 correct type utf-8
  core/src/node/extension/manager.ts
  core/src/node/extension/store.ts
  extensions/inference-nitro-extension/src/module.ts
Labels: type: bug

#1288 docs: update using models documentation
  docs/docs/guides/04-using-models/02-import-manually.mdx
  docs/docs/guides/04-using-models/03-integrate-with-remote-server.mdx
  docs/docs/guides/04-using-models/04-customize-models.md
  docs/docs/guides/04-using-models/05-package-models.md
  docs/docs/guides/04-using-models/assets/02-manually-import-local-model.png
  docs/docs/guides/04-using-models/assets/03-oai-compatible-configuration.png
  docs/docs/guides/04-using-models/assets/03-openai-platform-configuration.png
Labels: type: documentation

#1320 fix: app getting stuck at downloading 99% while downloading model
  electron/handlers/download.ts
  web/containers/Providers/EventListener.tsx
  web/hooks/useDownloadState.ts
Labels: type: bug

#1309 refactor: deprecate the appVersion IPC and use the predefined VERSION
  core/src/api/index.ts
  core/src/node/extension/manager.ts
  core/src/node/extension/store.ts
  electron/handlers/app.ts
  web/containers/Layout/BottomBar/index.tsx
  web/hooks/useGetAppVersion.ts
  web/screens/Settings/CoreExtensions/ExtensionsCatalog/index.tsx
  web/services/restService.ts
Labels: type: chore

#1327 docs: Update 01-server.md
  docs/docs/guides/05-using-server/01-server.md
Labels: type: documentation

#1326 docs: Update product.md
  docs/docs/handbook/product.md
Labels: type: documentation

#1325 feat: move social media from left panel into footer
  web/containers/Layout/BottomBar/SystemItem/index.tsx
  web/containers/Layout/BottomBar/index.tsx
  web/containers/Layout/Ribbon/index.tsx
  web/package.json
Labels: type: enhancement, type: feature request

#1332 fix: Error occurred: Unexpected token "d", "data: ..." is not a valid JSON
  extensions/inference-nitro-extension/src/helpers/sse.ts
  extensions/inference-openai-extension/src/helpers/sse.ts
Labels: type: bug

#1351 Add detect cuda version jan app
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/download.bat
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/module.ts
Labels: P0: critical, type: bug

#1345 fix: show a proper error message on download failure
  web/containers/Providers/EventListener.tsx
  web/hooks/useDownloadState.ts
Labels: type: bug

#1353 Chore add docs usage how to switch run mode jan app
  USAGE.md
  docs/static/img/usage/jan-gpu-enable-setting.png
  docs/static/img/usage/jan-open-home-directory.png
  docs/static/img/usage/jan-open-settings-1.png
  docs/static/img/usage/jan-open-settings-2.png
  docs/static/img/usage/jan-open-settings-3.png
  web/containers/GPUDriverPromptModal/index.tsx
Labels: P0: critical, type: chore

#1347 bugs: fix stop streaming when user delete or clean thread
  web/screens/Chat/ThreadList/index.tsx
Labels: type: bug

#1374 fix: show hide section engine params
  web/screens/Chat/Sidebar/index.tsx
Labels: type: bug

#1376 fix: wrong condition for displaying error message
  web/hooks/useDownloadState.ts
Labels: type: bug

#1360 docs: fix chat payload and cURL
  docs/openapi/jan.yaml
  docs/openapi/specs/assistants.yaml
  docs/openapi/specs/chat.yaml
  docs/openapi/specs/messages.yaml
  docs/openapi/specs/models.yaml
  docs/openapi/specs/threads.yaml
Labels: P1: important, type: documentation

#1378 fix: model migration stopped working
  extensions/model-extension/src/index.ts
Labels: type: bug

#1392 fix: GET /models does not work due to new default model dir
  core/src/node/api/common/builder.ts
Labels: type: bug

#1390 docs: add-install-nightly-guide
  docs/docs/guides/02-installation/05-nightly-build.md
  docs/docs/guides/02-installation/06-hardware.md
  docs/docs/guides/02-installation/README.mdx
Labels: type: documentation

#1394 docs: improve docs syntax
  docs/docs/guides/02-installation/04-from-source.md
  docs/docs/guides/04-using-models/02-import-manually.mdx
  docs/docs/guides/04-using-models/03-integrate-with-remote-server.mdx
  docs/docs/guides/07-troubleshooting/01-stuck-on-broken-build.mdx
  docs/docusaurus.config.js
Labels: type: documentation, type: chore

#1398 docs: Troubleshoot Failed To Fetch
  docs/docs/guides/07-troubleshooting/02-failed-to-fetch.mdx
Labels: type: documentation

#1399 docs: gpu not detected
  docs/docs/guides/07-troubleshooting/02-failed-to-fetch.mdx
  docs/docs/guides/07-troubleshooting/03-gpu-not-used.mdx
Labels: type: documentation

#1401 Update USAGE docs for linux
  USAGE.md
  docs/docs/guides/07-troubleshooting/03-gpu-not-used.mdx
Labels: type: chore

#1405 docs: improve gpu not used guide
  docs/docs/guides/07-troubleshooting/03-gpu-not-used.mdx
Labels: type: documentation

#1414 Update warning url from github md file to jan.ai docs site
  web/containers/GPUDriverPromptModal/index.tsx
Labels: type: chore

#1416 docs: Update 01-server.md
  docs/docs/guides/05-using-server/01-server.md
Labels: type: documentation

#1417 docs: explain each docs page intent
  docs/docs/developer/01-overview/README.md
  docs/docs/docs/README.md
  docs/docs/guides/00-overview.md
  docs/docusaurus.config.js
Labels: type: documentation

#1418 chore: clean up use os hook
  extensions/model-extension/src/index.ts
  web/containers/Layout/BottomBar/index.tsx
  web/containers/Shortcut/index.tsx
  web/hooks/useOs.ts
Labels: type: chore

#1393 Fix Bug for Chat Reply Goes off Screen
  web/screens/Chat/index.tsx
Labels: type: enhancement

#1419 docs: fix typo in docs
  docs/docs/developer/01-overview/README.md
  docs/docs/guides/02-installation/01-mac.md
  docs/docs/guides/02-installation/02-windows.md
  docs/docs/guides/02-installation/04-from-source.md
  docs/docs/guides/02-installation/README.mdx
  docs/docs/guides/07-troubleshooting/02-failed-to-fetch.mdx
  docs/docs/handbook/onboarding.md
  docs/docs/handbook/product.md
  docs/docs/support/support.md
Labels: type: documentation

#1438 docs: jan framework principles
  docs/docs/about/about.md
  docs/docs/docs/01-README.md
  docs/docs/docs/02-integrations/README.md
  docs/docs/docs/02-integrations/langchain.md
  docs/docs/docs/02-integrations/llamacpp.md
  docs/docs/docs/02-integrations/ollama.md
  docs/docs/docs/02-integrations/openai.md
  docs/docs/docs/02-integrations/openrouter.md
  docs/docs/docs/02-integrations/tensorrt.md
  docs/docs/docs/03-engineering/README.mdx
  docs/docs/docs/03-engineering/assistants.md
  docs/docs/docs/03-engineering/chats.md
  docs/docs/docs/03-engineering/engine.md
  docs/docs/docs/03-engineering/files.md
  docs/docs/docs/03-engineering/fine-tuning.md
  docs/docs/docs/03-engineering/messages.md
  docs/docs/docs/03-engineering/models.md
  docs/docs/docs/03-engineering/prompts.md
  docs/docs/docs/03-engineering/threads.md
  docs/docs/docs/03-product/README.mdx
  docs/docs/docs/03-product/chat.md
  docs/docs/docs/03-product/hub.md
  docs/docs/docs/03-product/jan.md
  docs/docs/docs/03-product/settings.md
  docs/docs/docs/03-product/system-monitor.md
  docs/docs/docs/README.md
  docs/docs/docs/assets/CleanArchitecture.jpg
  docs/docs/docs/assets/ExtensionCallouts.png
  docs/docs/docs/image.png
Labels: type: documentation

#1441 fix: render external links
  web/styles/components/message.scss
Labels: type: bug, type: enhancement

#1443 docs: revenue philosophy
  docs/docs/about/about.md
Labels: type: documentation

#1442 Feature linux support app image format
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/update-release-url.yml
  README.md
  electron/package.json
Labels: type: feature request

#1446 Correct AppImage path
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/update-release-url.yml
  README.md
Labels: type: bug

#1454 docs: add-missing-path
  docs/docs/guides/04-using-models/01-install-from-hub.mdx
Labels: type: documentation

#1455 docs: adding customize engine settings
  docs/docs/guides/04-using-models/04-customize-engine-settings.mdx
Labels: type: documentation

#1448 Chore: Update model.json for UI
  extensions/model-extension/package.json
  models/capybara-34b/model.json
  models/codeninja-1.0-7b/model.json
  models/deepseek-coder-1.3b/model.json
  models/deepseek-coder-34b/model.json
  models/dolphin-2.7-mixtral-8x7b/model.json
  models/llama2-chat-70b-q4/model.json
  models/llama2-chat-7b-q4/model.json
  models/magicoder-s-ds-7b/model.json
  models/mistral-ins-7b-q4/model.json
  models/mixtral-8x7b-instruct/model.json
  models/noromaid-7b/model.json
  models/openchat-3.5-7b/model.json
  models/openhermes-neural-7b/model.json
  models/pandora-10.7b-v1/cover.png
  models/pandora-10.7b-v1/model.json
  models/phi-2-3b/model.json
  models/phind-34b/model.json
  models/solar-10.7b-slerp/model.json
  models/starling-7b/model.json
  models/stealth-v1.2-7b/model.json
  models/tinyllama-1.1b/model.json
  models/trinity-v1.2-7b/model.json
  models/tulu-2-70b/model.json
  models/wizardcoder-13b/model.json
  models/yarn-mistral-7b/model.json
  models/yi-34b/model.json
Labels: P1: important

#1458 Bump nitro version to 0.2.6
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#1460 fix: suppress all main node JS error message dialog
  electron/main.ts
  electron/utils/clean.ts
Labels: type: bug

#1465 docs: Update about.md
  docs/docs/about/about.md
Labels: type: documentation

#1469 docs: Update 02-import-manually.mdx
  docs/docs/guides/04-using-models/02-import-manually.mdx
Labels: type: documentation

#1473 chore: error message update
  core/src/types/message/messageEntity.ts
  extensions/inference-nitro-extension/src/index.ts
  web/containers/Providers/EventHandler.tsx
  web/screens/Chat/ChatBody/index.tsx
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/SimpleTextMessage/index.tsx
Labels: type: chore

#1474 Bump nitro to 0.2.7
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#1480 Chore update docs jan - add AppImage instruction to docusaurus
  .github/workflows/update-release-url.yml
  README.md
  docs/docs/guides/02-installation/03-linux.md
  docs/src/containers/DownloadApp/index.js
  docs/src/containers/Elements/dropdown.js
  electron/package.json
Labels: type: documentation

#1476 Bump nitro to 0.2.8 and change Jan App to support cuda >= 11.7
  .github/workflows/jan-electron-linter-and-test.yml
  README.md
  USAGE.md
  docs/docs/guides/08-troubleshooting/03-gpu-not-used.mdx
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/download.bat
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/module.ts
Labels: type: chore

#1478 docs: minor fix
  docs/docs/about/about.md
  docs/docs/guides/07-integrations/01-integrate-continue.mdx
Labels: type: documentation

#1491 Revert nitro to 0.2.6
  README.md
  docs/docs/guides/08-troubleshooting/03-gpu-not-used.mdx
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/download.bat
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/module.ts
Labels: type: bug

#1497 chore: enable agolia
  docs/docusaurus.config.js
  docs/package.json
  docs/yarn.lock
Labels: type: chore

#1447 refactor: add app and nitro log - resolve dependencies issue
  core/rollup.config.ts
  core/src/api/index.ts
  core/src/core.ts
  core/src/fs.ts
  core/src/node/api/common/builder.ts
  core/src/node/api/routes/download.ts
  core/src/node/api/routes/extension.ts
  core/src/node/api/routes/fs.ts
  core/src/node/api/routes/v1.ts
  core/src/node/download.ts
  core/src/node/extension/extension.ts
  core/src/node/extension/manager.ts
  core/src/node/log.ts
  electron/handlers/app.ts
  electron/handlers/fileManager.ts
  electron/main.ts
  electron/utils/extension.ts
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/@types/global.d.ts
  extensions/inference-nitro-extension/src/helpers/nvidia.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/module.ts
  extensions/inference-nitro-extension/webpack.config.js
  extensions/model-extension/src/index.ts
  server/index.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: chore

#1440 feat: hub recommendation labels
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Labels: type: feature request

#1502 Revert URL release in readme to version 0.4.3
  README.md
Labels: type: chore

#1457 fix: stop word update
  extensions/model-extension/package.json
  models/capybara-34b/model.json
  models/codeninja-1.0-7b/model.json
  models/deepseek-coder-1.3b/model.json
  models/deepseek-coder-34b/model.json
  models/dolphin-2.7-mixtral-8x7b/model.json
  models/llama2-chat-70b-q4/model.json
  models/llama2-chat-7b-q4/model.json
  models/mistral-ins-7b-q4/model.json
  models/mixtral-8x7b-instruct/model.json
  models/noromaid-7b/model.json
  models/openchat-3.5-7b/model.json
  models/openhermes-neural-7b/model.json
  models/phi-2-3b/model.json
  models/phind-34b/model.json
  models/solar-10.7b-slerp/model.json
  models/starling-7b/model.json
  models/stealth-v1.2-7b/model.json
  models/tinyllama-1.1b/model.json
  models/trinity-v1.2-7b/model.json
  models/tulu-2-70b/model.json
  models/wizardcoder-13b/model.json
  models/yarn-mistral-7b/model.json
  models/yi-34b/model.json
  web/containers/CardSidebar/index.tsx
  web/hooks/useUpdateModelParameters.ts
Labels: type: bug

#1517 docs: fix algolia configuration
  docs/docusaurus.config.js
Labels: type: documentation

#1516 feat: [hub] update compatibility tags colors
  uikit/src/badge/index.tsx
  uikit/src/badge/styles.scss
  uikit/src/button/styles.scss
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Labels: type: feature request

#1518 docs: fix algolia configuration
  docs/.env.example
Labels: type: documentation

#1520 chore: fix darkmode docs
  docs/src/css/custom.css
Labels: type: chore

#1529 Feature integrate antivirus scanner to ci
  .github/workflows/jan-electron-linter-and-test.yml
  README.md
  docs/docs/guides/08-troubleshooting/03-gpu-not-used.mdx
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/download.bat
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/module.ts
Labels: type: bug, type: feature request

#1532 docs: fix x handles
  docs/docusaurus.config.js
  docs/src/containers/Banner/index.js
  docs/src/containers/Footer/index.js
Labels: type: documentation

#1522 fix: adjust calculation hub labels using total RAM instead remaining RAM
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Labels: type: bug

#1536 fix: gpu check module export does not work in extension
  extensions/inference-nitro-extension/src/helpers/nvidia.ts
  extensions/inference-nitro-extension/src/module.ts
Labels: type: bug

#1547 fix: could not change model params settings
  web/containers/DropdownListSidebar/index.tsx
  web/utils/componentSettings.ts
Labels: type: bug

#1552 feat: add compatibility tag to model selection in right panel
  web/containers/DropdownListSidebar/index.tsx
Labels: type: enhancement, type: feature request

#1568 chore: Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: chore

#1576 fix: #1569 - Does not apply thread settings when loading model
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/module.ts
  web/hooks/useActiveModel.ts
Labels: type: bug

#1577 chore: issues should auto close with PRs through template
  .github/pull_request_template.md
Labels: type: chore

#1578 chore: teach how to attach logs
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: chore

#1585 fix: enable user set value manually model setting from input
  web/containers/SliderRightPanel/index.tsx
Labels: type: bug

#1588 fix: #1559 Inference Parameters displayed on new thread with Openai GPT Model
  web/containers/DropdownListSidebar/index.tsx
Labels: type: bug

#1580 docs: add 04-how-to-get-error-logs.mdx
  docs/docs/guides/08-troubleshooting/02-somethings-amiss.mdx
  docs/docs/guides/08-troubleshooting/03-gpu-not-used.mdx
  docs/docs/guides/08-troubleshooting/04-how-to-get-error-logs.mdx
Labels: type: documentation

#1597 fix: switch model caused app crash
  web/containers/DropdownListSidebar/index.tsx
Labels: type: bug

#1600 fix: #1548 - duplicate command shortcut instruction
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#1595 fix: #1594 - Model settings - change thread model - go back does not see according settings
  web/hooks/useSetActiveThread.ts
Labels: type: bug

#1628 fix: correct footer
  docs/src/containers/Footer/index.js
Labels: type: bug

#1631 docs: add troubleshooting permission denied
  docs/docs/guides/08-troubleshooting/05-permission-denied.mdx
Labels: type: documentation

#1626 fix: enable check for update on all supported platforms
  electron/main.ts
  electron/utils/menu.ts
Labels: type: bug

#1630 refactor: introduce node module in nitro extension
  core/package.json
  core/src/types/model/modelEntity.ts
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/rollup.config.ts
  extensions/inference-nitro-extension/src/@types/global.d.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/module.ts
  extensions/inference-nitro-extension/src/node/execute.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/inference-nitro-extension/src/node/nvidia.ts
  extensions/inference-nitro-extension/tsconfig.json
  extensions/inference-nitro-extension/webpack.config.js
Labels: type: chore

#1638 fix: wrong selected model ref
  web/containers/DropdownListSidebar/index.tsx
Labels: type: bug

#1645 fix: auto select text when collapse panel
  web/containers/Layout/TopBar/index.tsx
Labels: type: bug

#1625 Update CI follow git flow
  .github/workflows/codeQL-analysis.yml
  .github/workflows/jan-docs.yml
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build-pre-release.yml
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-build-windows-x64.yml
  .github/workflows/template-get-update-version.yml
  .github/workflows/template-noti-discord-and-update-url-readme.yml
  electron/package.json
Labels: P0: critical, type: feature request

#1648 feat: relayout left panel setting page
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/index.tsx
Labels: type: feature request

#1641 docs: add antivirus compatibility testing
  docs/docs/guides/02-installation/06-hardware.md
  docs/docs/guides/02-installation/07-antivirus-compatibility-testing.md
Labels: type: documentation

#1653 Feature add schedule clean cloudflare page and r2
  .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
  .github/workflows/jan-docs.yml
  .github/workflows/jan-electron-build-nightly.yml
Labels: type: feature request

#1660 docs: add QA Script
  docs/docs/template/QA_script.md
Labels: type: documentation

#1663 fix bug #1650 hogging resources
  extensions/inference-nitro-extension/src/node/index.ts
Labels: P0: critical, type: bug

#1665 Cherrypick cicd to main branch to apply new gitflow
  .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
  .github/workflows/codeQL-analysis.yml
  .github/workflows/jan-docs.yml
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build-pre-release.yml
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-build-windows-x64.yml
  .github/workflows/template-get-update-version.yml
  .github/workflows/template-noti-discord-and-update-url-readme.yml
  electron/package.json
Labels: P0: critical, type: ci

#1562 feat: HTTP proxy support
  .gitignore
  core/README.md
  core/src/core.ts
  core/src/extensions/model.ts
  core/src/node/api/common/builder.ts
  core/src/node/api/routes/common.ts
  core/src/node/api/routes/download.ts
  core/src/types/model/modelInterface.ts
  electron/handlers/download.ts
  extensions/model-extension/src/index.ts
  web/context/FeatureToggle.tsx
  web/hooks/useDownloadModel.ts
  web/hooks/useDownloadState.ts
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/CoreExtensions/ExtensionsCatalog/index.tsx
Labels: P1: important, type: feature request

#1668 docs: update 02-somethings-amiss
  docs/docs/guides/08-troubleshooting/02-somethings-amiss.mdx
Labels: type: documentation

#1676 refactor: file prefix replace utils & add unit test
  Makefile
  core/.gitignore
  core/jest.config.js
  core/package.json
  core/src/node/api/routes/download.ts
  core/src/node/index.ts
  core/src/node/path.ts
  core/tests/node/path.test.ts
  core/tsconfig.json
  electron/handlers/download.ts
  electron/handlers/fileManager.ts
  electron/handlers/fs.ts
  package.json
  web/context/FeatureToggle.tsx
  web/hooks/useCreateNewThread.ts
  web/hooks/useDownloadModel.ts
  web/package.json
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/CoreExtensions/PreferenceExtensions/index.tsx
  web/screens/Settings/CoreExtensions/index.tsx
  web/screens/Settings/index.tsx
Labels: type: chore

#1677 refactor: deprecate extension type implementation
  core/README.md
  core/src/events.ts
  core/src/extension.ts
  core/src/extensions/assistant.ts
  core/src/extensions/conversational.ts
  core/src/extensions/inference.ts
  core/src/extensions/model.ts
  core/src/extensions/monitoring.ts
  extensions/assistant-extension/src/index.ts
  extensions/conversational-extension/src/index.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-triton-trtllm-extension/src/index.ts
  extensions/model-extension/src/index.ts
  extensions/monitoring-extension/src/index.ts
  web/containers/Providers/EventHandler.tsx
  web/extension/ExtensionManager.ts
  web/hooks/useActiveModel.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useDeleteModel.ts
  web/hooks/useDeleteThread.ts
  web/hooks/useDownloadModel.ts
  web/hooks/useGetAssistants.ts
  web/hooks/useGetConfiguredModels.ts
  web/hooks/useGetDownloadedModels.ts
  web/hooks/useGetSystemResources.ts
  web/hooks/useSendChatMessage.ts
  web/hooks/useSetActiveThread.ts
  web/hooks/useThreads.ts
  web/hooks/useUpdateModelParameters.ts
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/MessageToolbar/index.tsx
  web/screens/Chat/index.tsx
  web/services/extensionService.ts
Labels: type: chore

#1693 fix: stoping model show starting model
  web/containers/Loader/ModelStart.tsx
Labels: type: bug

#1700 fix: hot-fix algolia search
  docs/docusaurus.config.js
Labels: type: bug

#1649 feat: allow user to move jan folder
  core/.prettierrc
  core/src/api/index.ts
  core/src/core.ts
  core/src/node/api/common/builder.ts
  core/src/node/api/routes/download.ts
  core/src/node/api/routes/extension.ts
  core/src/node/api/routes/fileManager.ts
  core/src/node/api/routes/fs.ts
  core/src/node/extension/extension.ts
  core/src/node/extension/index.ts
  core/src/node/extension/manager.ts
  core/src/node/index.ts
  core/src/node/log.ts
  core/src/node/utils/index.ts
  core/src/types/config/appConfigEntity.ts
  core/src/types/config/index.ts
  core/src/types/index.ts
  electron/.eslintrc.js
  electron/@global/index.ts
  electron/handlers/app.ts
  electron/handlers/download.ts
  electron/handlers/extension.ts
  electron/handlers/fileManager.ts
  electron/handlers/fs.ts
  electron/main.ts
  electron/utils/extension.ts
  electron/utils/migration.ts
  electron/utils/path.ts
  electron/utils/setup.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/inference-nitro-extension/src/node/nvidia.ts
  extensions/model-extension/src/index.ts
  extensions/monitoring-extension/src/module.ts
  server/index.ts
  web/hooks/useGetSystemResources.ts
  web/hooks/usePath.ts
  web/hooks/useServerLog.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: feature request

#1702 fix: Jan server is showing blank page
  server/package.json
  web/screens/LocalServer/Logs.tsx
Labels: type: bug

#1703 fix: Jan server - v1/chat/completions is throwing ERR_REQUIRE_ESM
  electron/package.json
  server/index.ts
Labels: type: bug

#1704 feat: improvement ux for local api server
  web/containers/DropdownListSidebar/index.tsx
  web/containers/Layout/TopBar/index.tsx
  web/screens/LocalServer/index.tsx
  web/screens/Settings/Models/Row.tsx
Labels: type: feature request

#1705 fix: API chat/completion is blocked by CORS
  core/src/node/api/common/builder.ts
Labels: type: bug

#1724 Correct download url readme
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build-pre-release.yml
  README.md
Labels: P1: important, type: bug

#1711 docs: add troubleshoot unexpected token
  docs/docs/guides/08-troubleshooting/06-unexpected-token.mdx
Labels: type: documentation

#1727 Fix autoupdater nightly build error
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-build-windows-x64.yml
Labels: P0: critical, type: bug

#1719 fix: active model when start server
  web/screens/LocalServer/index.tsx
Labels: type: bug

#1736 Fix error nightly build schedule run failed
  .github/workflows/jan-electron-build-nightly.yml
Labels: type: bug, type: ci

#1741 fix: input port have range validation
  web/containers/Layout/Ribbon/index.tsx
  web/screens/LocalServer/index.tsx
Labels: type: bug

#1738 feat: update UI allow user change folder
  uikit/src/button/index.tsx
  uikit/src/button/styles.scss
  uikit/src/input/styles.scss
  web/containers/Layout/index.tsx
  web/containers/ShortcutModal/index.tsx
  web/hooks/useVaultDirectory.ts
  web/screens/Settings/Advanced/DataFolder/ModalChangeDirectory.tsx
  web/screens/Settings/Advanced/DataFolder/ModalErrorSetDestGlobal.tsx
  web/screens/Settings/Advanced/DataFolder/ModalSameDirectory.tsx
  web/screens/Settings/Advanced/DataFolder/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/CoreExtensions/index.tsx
  web/screens/Settings/index.tsx
Labels: type: feature request

#1756 fix: bring back open app directory
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#1757 Hotfix CI pre-release not trigger
  .github/workflows/jan-electron-build-pre-release.yml
Labels: type: bug, type: ci

#1767 Combine 2 ci pipeline pre-release and nightly into one
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build-pre-release.yml
Labels: type: ci

#1769 Correct bash script syntax in ci
  .github/workflows/jan-electron-build-nightly.yml
Labels: type: bug, type: ci

#1772 regression fix: input port not accept alphabets
  web/screens/LocalServer/index.tsx
Labels: type: bug

#1774 fix: can not start model when server is not enabled from model settings page
  web/screens/Settings/Models/Row.tsx
Labels: type: bug

#1779 fix: could not delete model
  web/screens/Settings/Models/Row.tsx
Labels: type: bug

#1782 Docs publish to github page trigger on push to docs branch
  .github/workflows/jan-docs.yml
Labels: type: ci, type: chore

#1783 Docs publish to github page trigger on push to docs branch
  .github/workflows/jan-docs.yml
Labels: type: ci, type: chore

#1786 Update 06-unexpected-token.mdx
  docs/docs/guides/08-troubleshooting/06-unexpected-token.mdx
Labels: type: documentation

#1789 fix: api settings are not applied on changes
  core/src/types/config/appConfigEvent.ts
  core/src/types/config/index.ts
  extensions/inference-openai-extension/src/index.ts
  web/hooks/useEngineSettings.ts
Labels: type: bug

#1790 fix: app log not being printed
  core/src/node/log.ts
  web/hooks/useVaultDirectory.ts
Labels: type: bug

#1759 adds devcontainer
  .devcontainer/devcontainer.json
Labels: P2: nice to have

#1793 fix: clean last message when user clean thread message
  web/hooks/useDeleteThread.ts
Labels: type: bug

#1798 CI nightly update trigger to 3AM UTC +7 Tuesday, Wednesday, and Thursday
  .github/workflows/jan-electron-build-nightly.yml
Labels: type: ci

#1794 docs: add OpenAI model list
  docs/docs/guides/04-using-models/03-integrate-with-remote-server.mdx
Labels: type: documentation

#1777 chore: clean up code and remove some lint suppression
  .gitignore
  extensions/assistant-extension/src/index.ts
  extensions/monitoring-extension/src/index.ts
  web/containers/Layout/index.tsx
  web/containers/Providers/EventHandler.tsx
  web/containers/Providers/EventListener.tsx
  web/hooks/useGetConfiguredModels.ts
  web/screens/Chat/MessageToolbar/index.tsx
Labels: type: chore

#1800 regression fix: input disabled darkmode
  uikit/src/input/styles.scss
  uikit/src/select/styles.scss
  web/screens/LocalServer/index.tsx
Labels: type: bug

#1799 fix: stop openai inference raises something amiss
  extensions/inference-openai-extension/src/index.ts
Labels: type: bug

#1801 fix: user can't use a model in model hub
  web/containers/DropdownListSidebar/index.tsx
  web/containers/OpenAiKeyInput/index.tsx
  web/hooks/useEngineSettings.ts
  web/hooks/useRecommendedModel.ts
  web/screens/Chat/Sidebar/index.tsx
  web/screens/LocalServer/index.tsx
Labels: type: bug

#1802 fix: model selection does not show in API settings page
  web/containers/DropdownListSidebar/index.tsx
  web/screens/LocalServer/index.tsx
Labels: type: bug

#1805 fix: cannot change jan data folder
  web/containers/Layout/index.tsx
  web/screens/Settings/Advanced/DataFolder/ModalChangeDirectory.tsx
  web/screens/Settings/Advanced/DataFolder/ModalErrorSetDestGlobal.tsx
  web/screens/Settings/Advanced/DataFolder/ModalSameDirectory.tsx
  web/screens/Settings/Advanced/DataFolder/index.tsx
Labels: type: bug

#1807 fix: user can't view model setting in local api server
  web/hooks/usePath.ts
  web/screens/Settings/Advanced/DataFolder/index.tsx
Labels: type: bug

#1821 Autofocus text input when start new chat
  web/screens/Chat/ChatInput/index.tsx
Labels: type: feature request

#1828 fix: model selection does not show in API settings page
  web/containers/Layout/TopBar/index.tsx
Labels: type: bug

#1832 Update release url on README to default branch instead of main branch
  .github/workflows/update-release-url.yml
  README.md
Labels: type: ci

#1833 chore: resolve main conflict
  extensions/inference-openai-extension/src/index.ts
  web/containers/Layout/TopBar/index.tsx
Labels: type: chore

#1831 fix: highlight menu dropdown server options
  web/screens/LocalServer/index.tsx
Labels: type: bug

#1818 perf: remove unnecessary rerender when user typing input
  web/containers/Providers/EventHandler.tsx
  web/helpers/atoms/ChatMessage.atom.ts
  web/hooks/useInference.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/ChatBody/index.tsx
  web/screens/Chat/ChatInput/index.tsx
  web/screens/Chat/MessageQueuedBanner/index.tsx
  web/screens/Chat/index.tsx
Labels: type: enhancement

#1820 feat: put timestamp under thread name in left panel
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/ThreadList/index.tsx
Labels: type: feature request

#1841 Add code sign step for darwin assistant extension
  extensions/assistant-extension/package.json
Labels: type: bug
