Repository menloresearch/jan, pull requests merged in 2024-03, with the labels that each got.

#2161 docs: update API Reference listModel from DevDocs
  docs/openapi/jan.yaml
Labels: type: documentation

#2169 docs: update API Reference model_id from DevDocs
  docs/openapi/jan.yaml
Labels: type: documentation

#2170 docs: update API Reference download model from DevDocs
  docs/openapi/jan.yaml
Labels: type: documentation

#2171 docs: update API Reference chatCompletions from DevDocs
  docs/openapi/jan.yaml
Labels: type: documentation

#2215 chore: clean up some redundant code
  web/containers/Providers/index.tsx
  web/context/FeatureToggle.tsx
  web/helpers/atoms/ApiServer.atom.ts
  web/helpers/atoms/AppConfig.atom.ts
  web/hooks/useConvertHuggingFaceModel.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useDownloadModel.ts
  web/screens/Chat/ChatInput/index.tsx
  web/screens/Chat/Sidebar/index.tsx
  web/screens/Chat/index.tsx
  web/screens/ExploreModels/index.tsx
  web/screens/LocalServer/index.tsx
  web/screens/Settings/Advanced/index.tsx
Labels: type: chore

#2213 fix: comment from QA regarding import model
  electron/handlers/native.ts
  web/containers/ItemCardSidebar/index.tsx
  web/hooks/useDropModelBinaries.ts
  web/screens/Settings/EditModelInfoModal/index.tsx
  web/screens/Settings/SelectingModelModal/index.tsx
Labels: type: bug

#2214 fix: import from HuggingFace with random string is causing app crash
  web/hooks/useGetHFRepoData.ts
  web/screens/ExploreModels/HuggingFaceRepoDataLoadedModal/index.tsx
  web/screens/ExploreModels/HuggingFaceSearchErrorModal/index.tsx
Labels: type: bug

#2220 feat: add turborepo
  .gitignore
  electron/package.json
  package.json
  turbo.json
Labels: type: feature request

#2221 Revert feat: temporary remove dark mode
  uikit/src/button/styles.scss
  uikit/src/checkbox/styles.scss
  uikit/src/input/styles.scss
  uikit/src/main.scss
  uikit/src/progress/styles.scss
  uikit/src/select/styles.scss
  uikit/src/slider/styles.scss
  uikit/src/switch/styles.scss
  uikit/src/tooltip/styles.scss
  web/app/layout.tsx
  web/containers/CardSidebar/index.tsx
  web/containers/Checkbox/index.tsx
  web/containers/DropdownListSidebar/index.tsx
  web/containers/GPUDriverPromptModal/index.tsx
  web/containers/Layout/BottomBar/DownloadingState/index.tsx
  web/containers/Layout/BottomBar/ImportingModelState/index.tsx
  web/containers/Layout/Ribbon/index.tsx
  web/containers/Layout/TopBar/index.tsx
  web/containers/Loader/index.tsx
  web/containers/ModalTroubleShoot/AppLogs.tsx
  web/containers/ModalTroubleShoot/DeviceSpecs.tsx
  web/containers/ModalTroubleShoot/index.tsx
  web/containers/ModelConfigInput/index.tsx
  web/containers/OpenAiKeyInput/index.tsx
  web/containers/Providers/Theme.tsx
  web/containers/ServerLogs/index.tsx
  web/containers/SliderRightPanel/index.tsx
  web/containers/Toast/index.tsx
  web/hooks/useUserConfigs.ts
  web/screens/Chat/CleanThreadModal/index.tsx
  web/screens/Chat/DeleteThreadModal/index.tsx
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/Sidebar/index.tsx
  web/screens/Chat/ThreadList/index.tsx
  web/screens/ExploreModels/HuggingFaceSearchModal/index.tsx
  web/screens/ExploreModels/index.tsx
  web/screens/LocalServer/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/Appearance/TogglePrimary.tsx
  web/screens/Settings/Appearance/ToggleTheme.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/EditModelInfoModal/index.tsx
  web/screens/Settings/ImportModelOptionModal/ImportModelOptionSelection.tsx
  web/screens/Settings/ImportSuccessIcon/index.tsx
  web/screens/Settings/ImportingModelModal/ImportingModelItem.tsx
  web/screens/Settings/ImportingModelModal/index.tsx
  web/screens/Settings/Models/Row.tsx
  web/screens/Settings/SelectingModelModal/index.tsx
  web/screens/Settings/SettingMenu/index.tsx
  web/screens/Settings/index.tsx
  web/styles/components/message.scss
  web/types/appearance.d.ts
Labels: type: enhancement

#2231 docs: add command run API server without frontend
  README.md
Labels: type: documentation

#2233 Chore: add prefix latest for task clean r2 bucket
  .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
Labels: type: chore

#2237 fix: drag and drop support image format to support vision model
  web/screens/Chat/ChatInput/index.tsx
  web/screens/Chat/index.tsx
Labels: type: bug

#2238 fix: replaced user path from app log
  web/hooks/useLogs.tsx
  web/hooks/usePath.ts
Labels: type: bug

#2243 docs: Fix Dark Mode on the Hub page and Update the Navbar functionality
  docs/src/components/HomepagePrimaryFeatures/index.js
  docs/src/components/HomepagePrimaryFeatures/styles.module.css
  docs/src/components/HomepageSecondaryFeatures/index.js
  docs/src/components/HomepageSecondaryFeatures/styles.module.css
  docs/src/components/HomepageTerinaryFeatures/index.js
  docs/src/components/HomepageTerinaryFeatures/styles.module.css
  docs/src/pages/docs.js
  docs/src/pages/docs.module.css
  docs/src/theme/Layout/index.js
  docs/src/theme/NavbarExtension/NavPageContainer.jsx
  docs/src/theme/NavbarExtension/NavPageContainer.module.css
  docs/src/theme/NavbarExtension/index.js
  docs/src/theme/NavbarExtension/index.module.css
  docs/tailwind.config.js
Labels: type: documentation, roadmap: Jan Docs

#2245 docs: Update content for Hub page and Guides section
  docs/docs/guides/advanced-settings/advanced-settings.mdx
  docs/docs/guides/advanced-settings/http-proxy.mdx
  docs/docs/guides/best-practices.mdx
  docs/docs/guides/common-error/not-using-gpu.mdx
  docs/src/components/HomepagePrimaryFeatures/index.js
  docs/src/components/HomepageSecondaryFeatures/index.js
  docs/src/components/HomepageTerinaryFeatures/index.js
  docs/src/theme/NavbarExtension/index.js
Labels: type: documentation

#2247 docs: sync docs hub fixes from dev to docs branch
  README.md
  docs/docs/guides/advanced-settings/advanced-settings.mdx
  docs/docs/guides/advanced-settings/http-proxy.mdx
  docs/docs/guides/best-practices.mdx
  docs/docs/guides/common-error/not-using-gpu.mdx
  docs/src/components/HomepagePrimaryFeatures/index.js
  docs/src/components/HomepagePrimaryFeatures/styles.module.css
  docs/src/components/HomepageSecondaryFeatures/index.js
  docs/src/components/HomepageSecondaryFeatures/styles.module.css
  docs/src/components/HomepageTerinaryFeatures/index.js
  docs/src/components/HomepageTerinaryFeatures/styles.module.css
  docs/src/pages/docs.js
  docs/src/pages/docs.module.css
  docs/src/theme/Layout/index.js
  docs/src/theme/NavbarExtension/NavPageContainer.jsx
  docs/src/theme/NavbarExtension/NavPageContainer.module.css
  docs/src/theme/NavbarExtension/index.js
  docs/src/theme/NavbarExtension/index.module.css
  docs/tailwind.config.js
Labels: type: documentation

#2242 fix: error message being sent along with conversation when inference
  core/src/types/message/messageEntity.ts
  extensions/inference-openai-extension/src/helpers/sse.ts
  extensions/inference-openai-extension/src/index.ts
  web/screens/Chat/ChatBody/index.tsx
  web/screens/Chat/ErrorMessage/index.tsx
  web/utils/errorMessage.ts
Labels: type: bug

#2248 fix: image upload button and drag event are not enabled
  extensions/model-extension/package.json
  web/containers/DropdownListSidebar/index.tsx
  web/hooks/useUpdateModelParameters.ts
  web/screens/Chat/ChatInput/index.tsx
  web/screens/Chat/index.tsx
  web/utils/modelParam.ts
Labels: type: bug

#2253 docs: Fix navbar issues. Keep stay when clicked other menu items from the sidebar
  docs/src/theme/Layout/index.js
Labels: P1: important, type: documentation

#2258 fix: should not attach error messages to the completion request
  extensions/inference-openai-extension/src/helpers/sse.ts
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-triton-trtllm-extension/src/index.ts
  web/helpers/atoms/ChatMessage.atom.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/MessageToolbar/index.tsx
  web/screens/Settings/Advanced/DataFolder/ModalErrorSetDestGlobal.tsx
  web/utils/errorMessage.ts
Labels: type: bug

#2261 feat: prompt user to download an update manually
  electron/handlers/update.ts
  web/containers/Layout/BottomBar/UpdateFailedModal/index.tsx
  web/containers/Layout/BottomBar/index.tsx
  web/containers/Providers/AppUpdateListener.tsx
  web/containers/Providers/Jotai.tsx
Labels: type: feature request

#2266 chore: temporary remove convert model
  web/screens/ExploreModels/index.tsx
Labels: type: chore

#2271 feat: changeEditUrl
  docs/docusaurus.config.js
Labels: type: feature request

#2197 feat: add quick ask
  .gitignore
  core/package.json
  core/src/api/index.ts
  core/src/node/api/restful/helper/startStopModel.ts
  core/src/types/miscellaneous/appUpdate.ts
  core/src/types/miscellaneous/index.ts
  core/src/types/model/modelEntity.ts
  electron/handlers/common.ts
  electron/handlers/native.ts
  electron/handlers/update.ts
  electron/icons/icon-tray.png
  electron/icons/icon-tray@2x.png
  electron/main.ts
  electron/managers/mainWindowConfig.ts
  electron/managers/quickAskWindowConfig.ts
  electron/managers/window.ts
  electron/package.json
  electron/utils/clean.ts
  electron/utils/selectedText.ts
  extensions/assistant-extension/package.json
  extensions/inference-nitro-extension/package.json
  server/package.json
  uikit/package.json
  web/app/search/SelectedText.tsx
  web/app/search/UserInput.tsx
  web/app/search/page.tsx
  web/containers/Providers/AppUpdateListener.tsx
  web/containers/Providers/ClipboardListener.tsx
  web/containers/Providers/DataLoader.tsx
  web/containers/Providers/EventHandler.tsx
  web/containers/Providers/EventListener.tsx
  web/containers/Providers/Jotai.tsx
  web/containers/Providers/KeyListener.tsx
  web/containers/Providers/QuickAskListener.tsx
  web/helpers/atoms/Assistant.atom.ts
  web/hooks/useActiveModel.ts
  web/hooks/useSendChatMessage.ts
  web/package.json
  web/screens/Settings/ImportingModelModal/ImportingModelItem.tsx
Labels: type: feature request

#2278 fix: reducing height title-bar drag window for enable clickable quick ask
  web/styles/base/global.scss
Labels: type: bug

#2275 docs: update about page
  docs/docs/about/about.md
Labels: type: documentation

#2273 docs: Implement Sidebar categories and Update guides content
  docs/docs/guides/faq.mdx
  docs/docs/guides/integration/groq.mdx
  docs/sidebars.js
  docs/src/css/custom.css
Labels: type: documentation

#2291 codesign script force sign
  .github/scripts/auto-sign.sh
Labels: type: bug

#2293 chore: store onboarding state under app config
  core/src/node/helper/config.ts
  core/src/types/config/appConfigEntity.ts
  web/containers/OnBoarding/AllSet/index.tsx
  web/containers/OnBoarding/Hotkey/index.tsx
  web/containers/OnBoarding/Welcome/index.tsx
  web/containers/Providers/DataLoader.tsx
  web/containers/Providers/OnBoardingListener.tsx
  web/containers/Providers/index.tsx
  web/helpers/atoms/AppConfig.atom.ts
  web/hooks/useAppConfig.ts
  web/hooks/useFactoryReset.ts
  web/hooks/useLogs.tsx
  web/hooks/usePath.ts
  web/screens/Settings/Advanced/DataFolder/index.tsx
  web/screens/Settings/EditModelInfoModal/index.tsx
  web/screens/Settings/ImportingModelModal/index.tsx
Labels: type: chore

#2302 fix: replace robotjs by nutjs (#2295)
  electron/main.ts
  electron/package.json
  electron/utils/selectedText.ts
  electron/utils/tray.ts
Labels: type: bug

#2306 docs: Fix install slug and fix navbar style in darkmode
  docs/docusaurus.config.js
  docs/src/css/custom.css
Labels: type: documentation

#2283 docs: sync updated content from dev to docs branch
  .github/scripts/auto-sign.sh
  .github/workflows/template-build-macos-arm64.yml
  .github/workflows/template-build-macos-x64.yml
  .gitignore
  README.md
  core/package.json
  core/src/api/index.ts
  core/src/node/api/restful/helper/startStopModel.ts
  core/src/types/miscellaneous/appUpdate.ts
  core/src/types/miscellaneous/index.ts
  core/src/types/model/modelEntity.ts
  docs/docs/about/about.md
  docs/docs/guides/error-codes/no-assistant-available.mdx
  docs/docs/guides/error-codes/stuck-on-loading-model.mdx
  docs/docs/guides/error-codes/thread-disappreance.mdx
  docs/docs/guides/faq.mdx
  docs/docs/guides/integration/groq.mdx
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/css/custom.css
  electron/handlers/common.ts
  electron/handlers/native.ts
  electron/handlers/update.ts
  electron/icons/icon-tray.png
  electron/icons/icon-tray@2x.png
  electron/main.ts
  electron/managers/mainWindowConfig.ts
  electron/managers/quickAskWindowConfig.ts
  electron/managers/window.ts
  electron/package.json
  electron/utils/clean.ts
  electron/utils/selectedText.ts
  electron/utils/tray.ts
  extensions/assistant-extension/package.json
  extensions/inference-nitro-extension/package.json
  server/package.json
  uikit/package.json
  web/app/search/SelectedText.tsx
  web/app/search/UserInput.tsx
  web/app/search/page.tsx
  web/containers/Layout/BottomBar/UpdateFailedModal/index.tsx
  web/containers/Layout/BottomBar/index.tsx
  web/containers/Providers/AppUpdateListener.tsx
  web/containers/Providers/ClipboardListener.tsx
  web/containers/Providers/DataLoader.tsx
  web/containers/Providers/EventHandler.tsx
  web/containers/Providers/EventListener.tsx
  web/containers/Providers/Jotai.tsx
  web/containers/Providers/KeyListener.tsx
  web/containers/Providers/QuickAskListener.tsx
  web/helpers/atoms/Assistant.atom.ts
  web/hooks/useActiveModel.ts
  web/hooks/useSendChatMessage.ts
  web/package.json
  web/screens/ExploreModels/index.tsx
  web/screens/Settings/ImportingModelModal/ImportingModelItem.tsx
  web/styles/base/global.scss
Labels: type: documentation

#2307 fix: message from quick ask not get the selected model
  web/hooks/useSendChatMessage.ts
Labels: type: bug

#2310 fix: quick ask blocks app update
  electron/handlers/update.ts
  electron/main.ts
  electron/managers/tray.ts
  electron/utils/tray.ts
Labels: type: bug

#2315 fix: quick ask not show
  electron/main.ts
  electron/managers/window.ts
Labels: type: bug

#2319 fix: jan app tray blocks app update
  electron/managers/tray.ts
Labels: type: bug

#2316 feat: quick ask support dark mode
  web/app/search/SelectedText.tsx
  web/app/search/UserInput.tsx
  web/app/search/page.tsx
Labels: type: enhancement, type: feature request

#2282 docs: update slogan
  docs/docs/about/about.md
Labels: type: documentation

#2327 fix: quick app windows, tray and dock behaviors
  electron/main.ts
  electron/managers/mainWindowConfig.ts
  electron/managers/tray.ts
  electron/managers/window.ts
  web/containers/Providers/KeyListener.tsx
Labels: type: bug

#2331 fix: gate quick ask with feature toggle
  core/src/node/helper/config.ts
  core/src/types/config/appConfigEntity.ts
  electron/main.ts
  electron/managers/tray.ts
  electron/managers/window.ts
  web/containers/Providers/DataLoader.tsx
  web/helpers/atoms/AppConfig.atom.ts
  web/hooks/useFactoryReset.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#2336 fix: do not migrate extensions from quick ask window
  web/containers/Providers/index.tsx
Labels: type: bug

#2338 fix: put quick ask feature toggle under experimental feature
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#2342 fix: add compatible check
  extensions/monitoring-extension/package.json
  extensions/monitoring-extension/src/node/index.ts
  extensions/tensorrt-llm-extension/models.json
  extensions/tensorrt-llm-extension/package.json
  extensions/tensorrt-llm-extension/rollup.config.ts
  web/screens/ExploreModels/ExploreModelItem/index.tsx
  web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
  web/screens/Settings/CoreExtensions/index.tsx
Labels: type: bug

#2344 Add icon file contain image size in file name to fix linux icon
  electron/icons/512x512.png
Labels: type: bug

#2346 fix: some costmetic issues: badges corner, recommended for tensorrt models
  uikit/src/badge/styles.scss
  web/containers/DropdownListSidebar/index.tsx
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Labels: type: bug

#2348 fix: ts error when declar var in case
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Labels: type: bug

#2349 fix: badge or progress tensorRtExtensionItem
  web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
Labels: type: bug

#2351 fix: disable rag & stream settings from tensorrt llm model.json
  extensions/tensorrt-llm-extension/models.json
  extensions/tensorrt-llm-extension/src/index.ts
  web/screens/Chat/ChatInput/index.tsx
Labels: type: bug

#2350 fix: app does not recognize GPU first launch
  extensions/monitoring-extension/src/node/index.ts
Labels: type: bug

#2353 docs: trt-llm extension guides
  docs/docs/guides/providers/README.mdx
  docs/docs/guides/providers/image.png
  docs/docs/guides/providers/llama-cpp.md
  docs/docs/guides/providers/tensorrt-llm.md
  docs/sidebars.js
Labels: type: documentation

#2357 fix: incompatible GPU error message
  extensions/tensorrt-llm-extension/models.json
  extensions/tensorrt-llm-extension/package.json
  extensions/tensorrt-llm-extension/src/index.ts
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
Labels: type: bug

#2363 fix: wrong engine handling
  extensions/tensorrt-llm-extension/src/index.ts
Labels: type: bug

#2368 fix: use model from model hub not load correct model in thread screen
  web/hooks/useCreateNewThread.ts
Labels: type: bug

#2366 docs: bump changelog v0.4.8
  docs/docs/releases/changelog/cache.json
  docs/docs/releases/changelog/changelog-v0.2.0.mdx
  docs/docs/releases/changelog/changelog-v0.2.1.mdx
  docs/docs/releases/changelog/changelog-v0.2.2.mdx
  docs/docs/releases/changelog/changelog-v0.2.3.mdx
  docs/docs/releases/changelog/changelog-v0.3.0.mdx
  docs/docs/releases/changelog/changelog-v0.3.1.mdx
  docs/docs/releases/changelog/changelog-v0.3.2.mdx
  docs/docs/releases/changelog/changelog-v0.3.3.mdx
  docs/docs/releases/changelog/changelog-v0.4.0.mdx
  docs/docs/releases/changelog/changelog-v0.4.1.mdx
  docs/docs/releases/changelog/changelog-v0.4.2.mdx
  docs/docs/releases/changelog/changelog-v0.4.3.mdx
  docs/docs/releases/changelog/changelog-v0.4.4.mdx
  docs/docs/releases/changelog/changelog-v0.4.5.mdx
  docs/docs/releases/changelog/changelog-v0.4.6.mdx
  docs/docs/releases/changelog/changelog-v0.4.7.mdx
  docs/docs/releases/changelog/changelog-v0.4.8.mdx
  docs/plugins/changelog-plugin/fetchData.js
  docs/plugins/changelog-plugin/index.js
Labels: type: documentation

#2367 docs: api reference 2.0
  docs/docusaurus.config.js
  docs/openapi/jan.json
  docs/package.json
  docs/yarn.lock
Labels: type: documentation, roadmap: Jan Docs

#2381 docs: fix broken link by redirecting to the right paths
  docs/docusaurus.config.js
Labels: type: documentation

#2384 docs: sync updated content to main page
  README.md
  docs/docs/about/faq.md
  docs/docs/releases/changelog/cache.json
  docs/docs/releases/changelog/changelog-v0.2.0.mdx
  docs/docs/releases/changelog/changelog-v0.2.1.mdx
  docs/docs/releases/changelog/changelog-v0.2.2.mdx
  docs/docs/releases/changelog/changelog-v0.2.3.mdx
  docs/docs/releases/changelog/changelog-v0.3.0.mdx
  docs/docs/releases/changelog/changelog-v0.3.1.mdx
  docs/docs/releases/changelog/changelog-v0.3.2.mdx
  docs/docs/releases/changelog/changelog-v0.3.3.mdx
  docs/docs/releases/changelog/changelog-v0.4.0.mdx
  docs/docs/releases/changelog/changelog-v0.4.1.mdx
  docs/docs/releases/changelog/changelog-v0.4.2.mdx
  docs/docs/releases/changelog/changelog-v0.4.3.mdx
  docs/docs/releases/changelog/changelog-v0.4.4.mdx
  docs/docs/releases/changelog/changelog-v0.4.5.mdx
  docs/docs/releases/changelog/changelog-v0.4.6.mdx
  docs/docs/releases/changelog/changelog-v0.4.7.mdx
  docs/docs/releases/changelog/changelog-v0.4.8.mdx
  docs/docusaurus.config.js
  docs/openapi/jan.json
  docs/package.json
  docs/plugins/changelog-plugin/fetchData.js
  docs/plugins/changelog-plugin/index.js
  docs/sidebars.js
  docs/yarn.lock
  extensions/tensorrt-llm-extension/models.json
  extensions/tensorrt-llm-extension/package.json
  extensions/tensorrt-llm-extension/src/index.ts
  web/hooks/useCreateNewThread.ts
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
Labels: type: documentation

#2380 fix: some regressions for tensorrt nightly build
  extensions/model-extension/src/index.ts
  extensions/tensorrt-llm-extension/package.json
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
Labels: type: bug

#2386 chore: temporary remove linux from tensorrt support
  extensions/tensorrt-llm-extension/package.json
Labels: type: chore

#2390 fix: line height typography blog and docs
  docs/docusaurus.config.js
  docs/src/styles/components/typography.scss
  docs/src/styles/tweaks/markdown.scss
Labels: type: bug

#2328 docs: Update sidebar and content for http proxy and import model
  docs/docs/developer/03-build-engine/02-engine-anatomy.md
  docs/docs/developer/03-build-engine/asset/plugin.png
  docs/docs/guides/advanced-settings/http-proxy.mdx
  docs/docs/guides/install.mdx
  docs/docs/guides/models/import-models.mdx
  docs/sidebars.js
Labels: type: documentation

#2399 fix: clean working dir with long space support on Windows
  .github/workflows/jan-electron-linter-and-test.yml
Labels: type: bug

#2401 fix: fail-fast would cancel matrix jobs as soon as one job fails
  .github/workflows/jan-electron-linter-and-test.yml
Labels: type: bug

#2402 fix: unable to start web with quick ask
  web/containers/Providers/QuickAskListener.tsx
Labels: type: bug

#2404 chore: update path for tensorrt engine
  extensions/tensorrt-llm-extension/package.json
  extensions/tensorrt-llm-extension/rollup.config.ts
  extensions/tensorrt-llm-extension/src/@types/global.d.ts
  extensions/tensorrt-llm-extension/src/index.ts
  extensions/tensorrt-llm-extension/src/node/index.ts
Labels: type: chore

#2400 fix: move tensorrt executable to engine
  core/src/api/index.ts
  core/src/core.ts
  core/src/extensions/ai-engines/LocalOAIEngine.ts
  core/src/extensions/monitoring.ts
  core/src/fs.ts
  core/src/node/api/processors/fsExt.ts
  core/src/node/extension/store.ts
  core/src/types/miscellaneous/systemResourceInfo.ts
  extensions/monitoring-extension/src/index.ts
  extensions/monitoring-extension/src/node/index.ts
  extensions/tensorrt-llm-extension/package.json
  extensions/tensorrt-llm-extension/rollup.config.ts
  extensions/tensorrt-llm-extension/src/@types/global.d.ts
  extensions/tensorrt-llm-extension/src/index.ts
  extensions/tensorrt-llm-extension/src/node/index.ts
  web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
  web/services/appService.ts
Labels: type: bug

#2411 fix: turn off experimental settings should also turn off quick ask
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#2412 fix: app glitches 1s generating response before starting model
  web/hooks/useSendChatMessage.ts
Labels: type: bug

#2414 fix: disable experimental feature should also disable vulkan
  .github/workflows/jan-electron-linter-and-test.yml
  web/hooks/useSettings.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#2413 fix: fallback when WMIC is not installed on user's windows
  core/src/node/helper/config.ts
  core/src/node/helper/resource.ts
Labels: type: bug

#2415 feat: TensorRT-LLM engine update support
  core/package.json
  core/src/api/index.ts
  core/src/extension.ts
  core/src/fs.ts
  core/src/node/api/processors/fsExt.ts
  extensions/tensorrt-llm-extension/models.json
  extensions/tensorrt-llm-extension/package.json
  extensions/tensorrt-llm-extension/rollup.config.ts
  extensions/tensorrt-llm-extension/src/index.ts
  web/containers/Providers/index.tsx
  web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
  web/screens/Settings/CoreExtensions/UpdateExtensionModal.tsx
Labels: type: feature request

#2375 chore: add prompt template tensorrtllm
  extensions/tensorrt-llm-extension/models.json
  extensions/tensorrt-llm-extension/src/node/index.ts
Labels: type: chore

#2419 fix: correct tensorrt mistral model.json
  extensions/tensorrt-llm-extension/models.json
Labels: type: bug

#2409 feat: download page
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/containers/DownloadApp/index.js
  docs/src/containers/Footer/index.js
  docs/src/pages/download.js
  docs/src/pages/index.js
  docs/yarn.lock
Labels: type: enhancement, type: feature request

#2424 docs: fix website thumbnail
  docs/blog/01-january-10-2024-bitdefender-false-positive-flag.mdx
  docs/docs/developer/01-overview/01-architecture.md
  docs/docs/developer/01-overview/02-file-based.md
  docs/docs/developer/01-overview/03-user-interface.md
  docs/docs/developer/01-overview/04-install-and-prerequisites.md
  docs/docs/developer/01-overview/README.md
  docs/docs/developer/04-build-extension/01-your-first-extension.md
  docs/docs/guides/error-codes/permission-denied.mdx
  docs/docs/guides/extensions/setup-ext.mdx
  docs/docs/hardware/concepts/gpu-and-vram.md
  docs/docs/hardware/recommendations/by-budget.md
  docs/docusaurus.config.js
  docs/static/img/og-image.png
Labels: type: bug, type: documentation

#2425 fix: hot-fix thumbnail
  README.md
  docs/blog/01-january-10-2024-bitdefender-false-positive-flag.mdx
  docs/docs/developer/01-overview/01-architecture.md
  docs/docs/developer/01-overview/02-file-based.md
  docs/docs/developer/01-overview/03-user-interface.md
  docs/docs/developer/01-overview/04-install-and-prerequisites.md
  docs/docs/developer/01-overview/README.md
  docs/docs/developer/04-build-extension/01-your-first-extension.md
  docs/docs/guides/error-codes/permission-denied.mdx
  docs/docs/guides/extensions/setup-ext.mdx
  docs/docs/hardware/concepts/gpu-and-vram.md
  docs/docs/hardware/recommendations/by-budget.md
  docs/docusaurus.config.js
  docs/static/img/og-image.png
Labels: type: bug

#2434 docs: update new website stats
  docs/src/pages/index.js
Labels: type: documentation

#2416 fix: remove decodeURI for avoid URI malformed
  web/screens/Chat/SimpleTextMessage/index.tsx
Labels: type: bug

#2447 docs: Fixed the Hero section
  docs/src/components/HomepagePrimaryFeatures/index.js
  docs/src/pages/docs.js
  docs/src/pages/docs.module.css
Labels: type: documentation

#2347 fix: refactor inference engines to extends AIEngine
  core/src/core.ts
  core/src/extensions/ai-engines/AIEngine.ts
  core/src/extensions/ai-engines/LocalOAIEngine.ts
  core/src/extensions/ai-engines/OAIEngine.ts
  core/src/extensions/ai-engines/RemoteOAIEngine.ts
  core/src/extensions/ai-engines/helpers/sse.ts
  core/src/extensions/ai-engines/index.ts
  extensions/inference-groq-extension/package.json
  extensions/inference-groq-extension/src/@types/global.d.ts
  extensions/inference-groq-extension/src/helpers/sse.ts
  extensions/inference-groq-extension/src/index.ts
  extensions/inference-groq-extension/webpack.config.js
  extensions/inference-nitro-extension/jest.config.js
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/babel.config.js
  extensions/inference-nitro-extension/src/helpers/sse.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/node/execute.test.ts
  extensions/inference-nitro-extension/src/node/execute.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/inference-openai-extension/README.md
  extensions/inference-openai-extension/package.json
  extensions/inference-openai-extension/src/@types/global.d.ts
  extensions/inference-openai-extension/src/helpers/sse.ts
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-openai-extension/webpack.config.js
  extensions/inference-triton-trtllm-extension/src/@types/global.d.ts
  extensions/inference-triton-trtllm-extension/src/helpers/sse.ts
  extensions/inference-triton-trtllm-extension/src/index.ts
  extensions/tensorrt-llm-extension/src/index.ts
  models/groq-llama2-70b/model.json
  models/groq-mixtral-8x7b-instruct/model.json
  web/containers/DropdownListSidebar/index.tsx
  web/screens/Settings/Models/Row.tsx
  web/services/extensionService.ts
Labels: type: bug

#2453 chore: log system information for debugging
  electron/main.ts
  electron/utils/system.ts
  extensions/monitoring-extension/src/node/index.ts
  web/containers/ModalTroubleShoot/AppLogs.tsx
  web/containers/ModalTroubleShoot/DeviceSpecs.tsx
  web/containers/ServerLogs/index.tsx
  web/hooks/useLogs.tsx
Labels: type: chore

#2455 fix: post to /v1/threads not found
  core/src/node/api/restful/common.ts
Labels: type: bug

#2173 docs: add blog post Get to GPT-3.5 performance
  docs/docs/pending-blogpost/02-surpassing-chatgpt-with-open-source-alternatives.mdx
  docs/docs/pending-blogpost/assets/mistral-comparasion.png
  docs/docs/pending-blogpost/assets/nitro-on-jan.png
  docs/docs/pending-blogpost/assets/rag-comparasion.png
  docs/docs/pending-blogpost/assets/stealth-comparasion.png
  docs/package.json
  docs/yarn.lock
Labels: type: documentation

#2134 docs: How to fine-tune LLMs
  docs/docs/pending-blogpost/finetune-with-docs.mdx
  docs/docs/pending-blogpost/img/about-nitro.png
  docs/docs/pending-blogpost/img/finetuned-respond-2.png
  docs/docs/pending-blogpost/img/finetuned-response.png
Labels: type: documentation

#2457 fix: only allow 4 stop words for openai
  core/src/node/api/restful/helper/builder.ts
Labels: type: bug

#2456 fix: deleting threads manually breaks model settings and document upload
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/ThreadList/index.tsx
Labels: type: bug

#2460 fix: app shows wrong toast on stopping inference
  extensions/tensorrt-llm-extension/src/index.ts
Labels: type: bug

#2464 fix: move jan to not empty destination folder not functioning
  web/screens/Settings/Advanced/DataFolder/index.tsx
Labels: type: bug

#2392 fix: turborepo extensions
  .github/workflows/codeQL-analysis.yml
  .github/workflows/jan-electron-linter-and-test.yml
  Makefile
  extensions/package.json
  extensions/turbo.json
  package.json
  turbo.json
  web/package.json
Labels: type: bug

#2466 fix: app raises port not available error
  extensions/tensorrt-llm-extension/src/node/index.ts
Labels: type: bug

#2459 chore: remove rmdirsync from core api since it is deprecated
  core/src/api/index.ts
  core/src/extensions/ai-engines/AIEngine.ts
  core/src/fs.ts
  core/src/node/api/processors/fs.ts
  core/src/node/api/processors/fsExt.ts
  core/src/node/extension/extension.ts
  extensions/assistant-extension/src/index.ts
  extensions/conversational-extension/src/index.ts
  extensions/huggingface-extension/src/index.ts
  extensions/inference-groq-extension/src/index.ts
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-triton-trtllm-extension/src/index.ts
  extensions/model-extension/src/index.ts
  extensions/tensorrt-llm-extension/src/index.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: chore

#2488 fix: docker build fails
  Dockerfile
  Dockerfile.gpu
  charts/server/values.yaml
  docs/openapi/.gitkeep
  docs/openapi/jan.json
  docs/openapi/jan.yaml
  docs/openapi/specs/assistants.yaml
  docs/openapi/specs/chat.yaml
  docs/openapi/specs/messages.yaml
  docs/openapi/specs/models.yaml
  docs/openapi/specs/threads.yaml
Labels: type: chore

#2493 refactor: introduce inference tools
  core/src/browser/extensions/engines/AIEngine.ts
  core/src/browser/extensions/engines/EngineManager.ts
  core/src/browser/extensions/engines/OAIEngine.ts
  core/src/browser/extensions/engines/helpers/sse.ts
  core/src/browser/index.ts
  core/src/browser/tools/index.ts
  core/src/browser/tools/manager.ts
  core/src/browser/tools/tool.ts
  core/src/types/model/modelEntity.ts
  extensions/assistant-extension/src/index.ts
  extensions/assistant-extension/src/tools/retrieval.ts
  web/containers/Providers/EventHandler.tsx
  web/hooks/useActiveModel.ts
  web/hooks/useSendChatMessage.ts
  web/services/coreService.ts
Labels: type: chore

#2470 refactor: inference engine provider and accessibility
  core/src/browser/core.ts
  core/src/browser/events.ts
  core/src/browser/extension.ts
  core/src/browser/extensions/assistant.ts
  core/src/browser/extensions/conversational.ts
  core/src/browser/extensions/engines/AIEngine.ts
  core/src/browser/extensions/engines/EngineManager.ts
  core/src/browser/extensions/engines/LocalOAIEngine.ts
  core/src/browser/extensions/engines/OAIEngine.ts
  core/src/browser/extensions/engines/RemoteOAIEngine.ts
  core/src/browser/extensions/engines/helpers/sse.ts
  core/src/browser/extensions/engines/index.ts
  core/src/browser/extensions/huggingface.ts
  core/src/browser/extensions/index.ts
  core/src/browser/extensions/inference.ts
  core/src/browser/extensions/model.ts
  core/src/browser/extensions/monitoring.ts
  core/src/browser/fs.ts
  core/src/browser/index.ts
  core/src/browser/tools/index.ts
  core/src/browser/tools/manager.ts
  core/src/browser/tools/tool.ts
  core/src/extensions/ai-engines/RemoteOAIEngine.ts
  core/src/index.ts
  core/src/node/api/common/adapter.ts
  core/src/node/api/common/handler.ts
  core/src/node/api/processors/download.ts
  core/src/node/api/restful/app/download.ts
  core/src/node/index.ts
  core/src/types/api/index.ts
  core/src/types/index.ts
  core/src/types/model/modelEntity.ts
  extensions/assistant-extension/src/index.ts
  extensions/assistant-extension/src/tools/retrieval.ts
  extensions/inference-nitro-extension/src/index.ts
  web/containers/DropdownListSidebar/index.tsx
  web/containers/Providers/EventHandler.tsx
  web/extension/ExtensionManager.ts
  web/hooks/useActiveModel.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/FileUploadPreview/index.tsx
  web/screens/Chat/SimpleTextMessage/index.tsx
  web/services/coreService.ts
  web/utils/messageRequestBuilder.ts
  web/utils/threadMessageBuilder.ts
Labels: type: chore

#2504 fix: uploading a document mid-thread does not work
  extensions/assistant-extension/src/node/index.ts
  extensions/assistant-extension/src/node/retrieval.ts
  extensions/assistant-extension/src/tools/retrieval.ts
  extensions/model-extension/package.json
  models/groq-llama2-70b/model.json
  models/groq-mixtral-8x7b-instruct/model.json
  web/utils/messageRequestBuilder.ts
Labels: type: bug

#2505 fix: error invoking remote method readDirSync
  extensions/assistant-extension/src/index.ts
  extensions/conversational-extension/src/index.ts
Labels: type: bug

#2511 fix: rag is not working for nitro
  extensions/assistant-extension/src/node/retrieval.ts
Labels: type: bug

#2516 Add CI auto assign current milestone for merged PR
  .github/workflows/auto-assign-milestone.yml
Labels: type: feature request

#2498 fix: load model fails - generating button is not updated
  web/hooks/useActiveModel.ts
  web/hooks/useSendChatMessage.ts
Labels: type: bug

#2517 fix: model recommendation label is not based on VRAM
  web/containers/ModelLabel/NotEnoughMemoryLabel.tsx
  web/containers/ModelLabel/index.tsx
  web/helpers/atoms/SystemBar.atom.ts
  web/hooks/useGetSystemResources.ts
  web/hooks/useSettings.ts
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Labels: type: bug

#2522 fix: duplicate api definition
  core/src/browser/fs.ts
  core/src/node/api/processors/fsExt.ts
  core/src/types/api/index.ts
  extensions/tensorrt-llm-extension/src/node/index.ts
Labels: type: bug

#2524 fix: remove files and memory when user clean thread
  web/hooks/useDeleteThread.ts
Labels: type: bug

#2533 fix: display default error message
  core/src/browser/extensions/engines/OAIEngine.ts
  core/src/types/message/messageEntity.ts
  web/containers/AutoLink/index.tsx
  web/screens/Chat/ErrorMessage/index.tsx
Labels: type: bug

#2538 fix: image model does not work when retrieval tool is enabled
  extensions/assistant-extension/src/tools/retrieval.ts
  web/containers/AutoLink/index.tsx
  web/screens/Chat/ErrorMessage/index.tsx
Labels: type: bug

#2543 fix: quick ask improvement
  README.md
  web/app/layout.tsx
  web/app/page.tsx
  web/app/search/SelectedText.tsx
  web/app/search/layout.tsx
  web/containers/Layout/TopBar/index.tsx
  web/containers/Layout/index.tsx
  web/containers/MainViewContainer/index.tsx
  web/containers/Providers/ClipboardListener.tsx
  web/containers/Providers/QuickAskListener.tsx
  web/containers/Providers/index.tsx
  web/package.json
  web/services/extensionService.ts
  web/styles/base/global.scss
Labels: type: bug
