Repository menloresearch/jan, pull requests merged in 2024-07, with the labels that each got.

#3126 fix: set specific version for terminate
  extensions/inference-nitro-extension/package.json
Labels: type: bug

#3129 feat: add claude 3.5 sonnet
  extensions/inference-anthropic-extension/package.json
  extensions/inference-anthropic-extension/resources/models.json
Labels: type: feature request

#3131 feat: add options config spell check for chat input
  web/helpers/atoms/Setting.atom.ts
  web/screens/Settings/Appearance/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx
Labels: type: enhancement, type: feature request

#3130 fix: toggle button for expand log section on modal troubleshoot
  web/containers/ModalTroubleShoot/index.tsx
Labels: type: bug, type: enhancement

#3138 fix: add tooltip messages toolbar
  web/screens/Thread/ThreadCenterPanel/MessageToolbar/index.tsx
Labels: type: bug

#3149 fix: handle error message when apikey is not setup
  core/src/types/message/messageEntity.ts
  web/containers/ErrorMessage/index.tsx
Labels: type: bug

#3148 fix: title thread not updated on input edit title
  web/screens/Thread/ThreadLeftPanel/ModalEditTitleThread/index.tsx
Labels: type: bug

#3152 fix: validate path in fs
  core/src/browser/fs.ts
  core/src/node/api/processors/download.ts
  core/src/node/api/processors/fs.ts
  core/src/node/api/processors/fsExt.ts
  core/src/node/helper/config.ts
  core/src/node/helper/path.ts
  core/src/types/api/index.ts
  extensions/model-extension/package.json
  extensions/model-extension/src/index.ts
Labels: type: bug

#3156 fix: missing keyboard sand shortcuts screen
  web/screens/Settings/SettingDetail/index.tsx
  web/screens/Settings/index.tsx
Labels: type: bug

#3147 fix: model dropdown search result always show downloaded models first
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#3150 feat: add shortcut app logs on system monitor
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
Labels: type: feature request

#3160 fix: move Jan folder
  core/src/browser/fs.ts
  core/src/node/api/processors/fsExt.ts
  core/src/types/api/index.ts
  electron/preload.ts
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
  web/screens/Settings/Advanced/DataFolder/index.tsx
  web/screens/Settings/CoreExtensions/ExtensionItem.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: bug

#3174 chore: update ui new hub screen
  joi/src/core/Button/styles.scss
  joi/src/core/Table/index.tsx
  web/components/Discord.tsx
  web/components/GitHub.tsx
  web/containers/CenterPanelContainer/index.tsx
  web/containers/Layout/RibbonPanel/index.tsx
  web/helpers/atoms/Setting.atom.ts
  web/hooks/useLoadTheme.ts
  web/screens/HubScreen2/components/BuiltInModelCard.tsx
  web/screens/HubScreen2/components/BuiltInModelGroup.tsx
  web/screens/HubScreen2/components/Carousel.tsx
  web/screens/HubScreen2/components/DetailModelGroup.tsx
  web/screens/HubScreen2/components/Filter.tsx
  web/screens/HubScreen2/components/HeaderModal.tsx
  web/screens/HubScreen2/components/HfListModel.tsx
  web/screens/HubScreen2/components/HuggingFaceModelCard.tsx
  web/screens/HubScreen2/components/HuggingFaceModelGroup.tsx
  web/screens/HubScreen2/components/ListModel.tsx
  web/screens/HubScreen2/components/ModelInformation.tsx
  web/screens/HubScreen2/components/ModelSearchBar.tsx
  web/screens/HubScreen2/components/RemoteModelGroup.tsx
  web/screens/HubScreen2/components/SetUpApiKeyModal.tsx
  web/screens/HubScreen2/components/Slider.tsx
  web/screens/HubScreen2/components/SliderItem.tsx
  web/screens/HubScreen2/components/Tab.tsx
  web/screens/HubScreen2/index.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/EngineSetting/index.tsx
  web/screens/Settings/MyModels/ModelItem/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
  web/screens/Thread/index.tsx
  web/styles/main.scss
  web/styles/markdown.scss
Labels: type: enhancement, type: chore

#3182 chore: minor UI hub
  web/hooks/useSendMessage.ts
  web/screens/HubScreen2/components/BuiltInModelGroup.tsx
  web/screens/HubScreen2/components/HeaderModal.tsx
  web/screens/HubScreen2/components/HuggingFaceModelGroup.tsx
  web/screens/HubScreen2/components/RemoteModelGroup.tsx
  web/screens/HubScreen2/components/SetUpRemoteModelModal.tsx
  web/screens/Settings/MyModels/ModelItem/index.tsx
  web/screens/Thread/ThreadLeftPanel/ThreadItem/index.tsx
  web/screens/Thread/ThreadLeftPanel/TypingAnimated/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
  web/styles/base/global.scss
Labels: type: enhancement, type: chore

#3165 fix: logic show modal migration
  core/src/types/api/index.ts
  electron/handlers/native.ts
  web/containers/Providers/ModalMigrations.tsx
  web/helpers/atoms/AppConfig.atom.ts
  web/hooks/useMigratingData.ts
Labels: type: bug

#3188 chore: models group search blank state
  web/screens/HubScreen2/components/DetailModelGroup.tsx
Labels: type: enhancement, type: chore

#3189 chore: set state thread and models migration using getOnInit
  web/containers/Providers/ModalMigrations.tsx
  web/helpers/atoms/AppConfig.atom.ts
Labels: type: enhancement

#3193 fix: jan app copy nits
  extensions/monitoring-extension/resources/settings.json
  web/screens/Settings/Advanced/DataFolder/index.tsx
  web/screens/Settings/Advanced/FactoryReset/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/Hotkeys/index.tsx
Labels: type: bug

#3192 chore: system monitor show engine model
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
Labels: type: enhancement, type: chore

#3195 chore: added loader detail model
  web/screens/HubScreen2/components/HfListModel.tsx
  web/screens/HubScreen2/components/ListModel.tsx
  web/screens/HubScreen2/components/ModelInformation.tsx
Labels: type: enhancement, type: chore

#3202 chore: minor UI feedback
  web/containers/Layout/TopPanel/index.tsx
  web/screens/HubScreen2/components/BuiltInModelCard.tsx
  web/screens/HubScreen2/components/Filter.tsx
Labels: type: enhancement, type: chore

#3213 chore: set container max width for chat message and new hub screen
  web/screens/HubScreen2/index.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: enhancement, type: chore

#3217 feat: new starter screen
  Makefile
  electron/download.bat
  web/helpers/atoms/SetupRemoteModel.atom.ts
  web/screens/HubScreen2/components/SetUpApiKeyModal.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/OnDeviceListStarter.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/index.tsx
  web/screens/Thread/index.tsx
Labels: type: feature request
