Repository menloresearch/jan, pull requests merged in 2024-04, with the labels that each got.

#2525 fix: quick ask blocks app update
  electron/handlers/update.ts
  electron/main.ts
  electron/managers/window.ts
  web/screens/Chat/ErrorMessage/index.tsx
Labels: type: bug

#2573 chore: some wordings in extension settings
  extensions/inference-groq-extension/resources/settings.json
  web/screens/Settings/SettingMenu/index.tsx
Labels: type: chore

#2535 Change npm registry to nexus for CI test and enable turbo remote cache
  .github/workflows/jan-electron-linter-and-test.yml
  Makefile
  extensions/turbo.json
  web/yarn.lock
Labels: type: chore

#2576 Change release download url to cloudflare worker proxy and update download model tensorrt llm to aws s3 endpoint
  .github/workflows/template-noti-discord-and-update-url-readme.yml
  .github/workflows/update-release-url.yml
  README.md
  extensions/tensorrt-llm-extension/models.json
Labels: type: chore

#2578 fix: disabling Vulkan causes users to be stuck in GPU-accelerated mode
  web/hooks/useSettings.ts
Labels: type: bug

#2580 fix: broken auto link
  web/screens/Chat/ErrorMessage/index.tsx
Labels: type: bug

#2581 fix: missing load model error message
  web/hooks/useActiveModel.ts
  web/screens/Chat/ChatBody/index.tsx
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/LoadModelError/index.tsx
Labels: type: bug

#2584 fix: groq frequently stops during long responses
  core/src/browser/extensions/engines/helpers/sse.ts
Labels: type: bug

#2592 fix: does not register global shortcut when quick ask is disabled
  electron/main.ts
Labels: type: bug

#2596 Move out from cloudflare r2 to aws s3
  .github/workflows/clean-cloudflare-r2.yml
  extensions/monitoring-extension/download.bat
  extensions/monitoring-extension/package.json
Labels: type: chore

#2588 chore: update place holder for api key of groq and openai
  extensions/inference-groq-extension/resources/settings.json
  extensions/inference-openai-extension/resources/settings.json
Labels: type: chore

#2593 fix: app does not gracefully stop a model
  server/index.ts
  web/hooks/useActiveModel.ts
Labels: type: bug

#2606 fix: wrong response header for non streamed responses
  core/src/node/api/restful/helper/builder.ts
Labels: type: bug

#2602 fix: duplicated error message
  web/screens/Chat/ChatBody/index.tsx
Labels: type: bug

#2605 chore: add open log dir to troubleshooting modal
  web/containers/ModalTroubleShoot/AppLogs.tsx
  web/containers/ServerLogs/index.tsx
  web/hooks/usePath.ts
Labels: type: chore

#2609 Enable trigger for pull_request_target ci linter
  .github/workflows/jan-electron-linter-and-test.yml
Labels: type: chore

#2603 fix: copied logs line break
  web/containers/ModalTroubleShoot/AppLogs.tsx
  web/containers/ModalTroubleShoot/DeviceSpecs.tsx
  web/containers/ServerLogs/index.tsx
Labels: type: bug

#2607 fix: cancel loading model with stop action
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/node/index.ts
  web/containers/Loader/ModelReload.tsx
  web/containers/Loader/ModelStart.tsx
  web/containers/Providers/EventHandler.tsx
  web/hooks/useActiveModel.ts
  web/hooks/useCreateNewThread.ts
  web/screens/Chat/ChatInput/index.tsx
  web/screens/Chat/EditChatInput/index.tsx
  web/screens/Chat/LoadModelError/index.tsx
  web/screens/Settings/Models/Row.tsx
Labels: type: bug

#2612 docs: Update README.md
  README.md
Labels: type: documentation

#2611 Change condition for trigger PR from forked repo
  .github/workflows/jan-electron-linter-and-test.yml
Labels: type: chore

#2623 fix: object is destroyed block app exit
  core/src/node/api/restful/helper/builder.ts
  electron/managers/window.ts
  web/hooks/useCreateNewThread.ts
  web/screens/Chat/ChatInput/index.tsx
  web/screens/Chat/EditChatInput/index.tsx
Labels: type: bug

#2629 Correct condition checking cuda dependencies windows
  extensions/monitoring-extension/src/node/index.ts
Labels: type: chore

#2642 fix: quick ask could not register global shortcuts
  electron/main.ts
  electron/utils/shortcut.ts
Labels: type: bug

#2628 chore: add GPU driver and toolkit status
  extensions/monitoring-extension/src/node/index.ts
  web/containers/GPUDriverPromptModal/index.tsx
  web/containers/Providers/index.tsx
  web/hooks/useSettings.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: chore

#2626 fix: redirect to extension setting
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/LoadModelError/index.tsx
Labels: type: bug

#2648 Feature playwright integrate report portal
  .github/workflows/jan-electron-linter-and-test.yml
  Makefile
  electron/package.json
Labels: type: feature request

#2651 fix: model selector lack of warning message when no models downloaded
  web/containers/DropdownListSidebar/index.tsx
Labels: type: bug

#2653 chore: filter gguf files when importing model on windows
  core/src/types/miscellaneous/selectFiles.ts
  electron/handlers/native.ts
  web/screens/Settings/ChooseWhatToImportModal/index.tsx
Labels: type: chore

#2650 fix: api server - server url prefix is not updated
  server/index.ts
Labels: type: bug

#2649 fix: unload model while loading cause unknown error
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/inference-triton-trtllm-extension/resources/settings.json
  web/hooks/useActiveModel.ts
  web/screens/Chat/Sidebar/index.tsx
Labels: type: bug

#2645 fix: missing api key error handling
  core/src/browser/extensions/engines/helpers/sse.ts
  core/src/types/message/messageEntity.ts
  web/screens/Chat/ErrorMessage/index.tsx
Labels: type: bug

#2652 Bump nitro version to 0.3.18
  core/src/node/api/restful/helper/startStopModel.ts
  extensions/huggingface-extension/src/node/index.ts
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/download.bat
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/node/execute.test.ts
  extensions/inference-nitro-extension/src/node/execute.ts
Labels: type: chore

#2663 Bump nitro to 0.3.19
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#2668 Change report portal description to git commit hash
  .github/workflows/jan-electron-linter-and-test.yml
Labels: type: bug, type: chore

#2662 feat: move log into monitoring extension
  core/src/node/api/processors/app.ts
  core/src/node/api/restful/helper/startStopModel.ts
  core/src/node/helper/config.ts
  core/src/node/helper/index.ts
  core/src/node/helper/log.ts
  core/src/node/helper/logger.ts
  core/src/node/helper/resource.ts
  core/src/types/monitoring/monitoringInterface.ts
  electron/main.ts
  electron/utils/log.ts
  extensions/assistant-extension/README.md
  extensions/huggingface-extension/README.md
  extensions/inference-groq-extension/README.md
  extensions/inference-nitro-extension/README.md
  extensions/inference-triton-trtllm-extension/README.md
  extensions/model-extension/README.md
  extensions/monitoring-extension/README.md
  extensions/monitoring-extension/resources/settings.json
  extensions/monitoring-extension/rollup.config.ts
  extensions/monitoring-extension/src/index.ts
  extensions/monitoring-extension/src/node/index.ts
  extensions/monitoring-extension/src/node/logger.ts
  server/helpers/logger.ts
  server/index.ts
  web/containers/ServerLogs/index.tsx
  web/extension/ExtensionManager.ts
  web/hooks/useLogs.tsx
  web/screens/Settings/CoreExtensions/TensorRtExtensionItem.tsx
  web/screens/Settings/ExtensionSetting/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailToggleItem/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/index.tsx
  web/screens/Settings/SettingMenu/index.tsx
Labels: type: feature request

#2673 Enable ci linter workflow_dispatch event
  .github/workflows/jan-electron-linter-and-test.yml
Labels: type: chore

#2669 fix: add fallback as default endpoint for inference engine
  core/src/browser/extensions/engines/OAIEngine.ts
  extensions/inference-groq-extension/resources/settings.json
  extensions/inference-groq-extension/src/index.ts
  extensions/inference-mistral-extension/resources/settings.json
  extensions/inference-mistral-extension/src/index.ts
  extensions/inference-openai-extension/resources/settings.json
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-triton-trtllm-extension/resources/settings.json
  extensions/inference-triton-trtllm-extension/src/index.ts
Labels: type: bug

#2674 feat: nitro additional dependencies
  core/src/browser/extension.ts
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/rollup.config.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/model-extension/src/index.ts
  extensions/monitoring-extension/src/node/index.ts
  extensions/tensorrt-llm-extension/src/index.ts
  web/containers/Layout/BottomBar/InstallingExtension/index.tsx
  web/hooks/useSettings.ts
  web/screens/Chat/LoadModelError/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/CoreExtensions/ExtensionItem.tsx
  web/screens/Settings/CoreExtensions/UpdateExtensionModal.tsx
  web/screens/Settings/CoreExtensions/index.tsx
  web/screens/Settings/ExtensionSetting/index.tsx
  web/screens/Settings/SettingMenu/index.tsx
Labels: type: feature request

#2677 fix: can't read the setting at first time
  core/src/browser/extensions/engines/OAIEngine.ts
  extensions/inference-groq-extension/src/index.ts
  extensions/inference-mistral-extension/src/index.ts
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-triton-trtllm-extension/src/index.ts
Labels: type: bug

#2679 fix: wrong monitoring system information type
  core/src/browser/extensions/monitoring.ts
  core/src/types/miscellaneous/systemResourceInfo.ts
  core/src/types/monitoring/monitoringInterface.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/monitoring-extension/src/index.ts
  extensions/tensorrt-llm-extension/src/index.ts
  extensions/tensorrt-llm-extension/src/node/index.ts
  web/screens/Settings/CoreExtensions/ExtensionItem.tsx
  web/screens/Settings/CoreExtensions/index.tsx
Labels: type: bug

#2680 bump nitro version to 0.3.21
  .github/workflows/jan-electron-linter-and-test.yml
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#2681 fix: better kill process tensorrt-llm
  extensions/tensorrt-llm-extension/package.json
  extensions/tensorrt-llm-extension/src/node/index.ts
Labels: type: bug

#2683 fix: race condition issue - reading settings.json file
  extensions/assistant-extension/package.json
  extensions/conversational-extension/package.json
  extensions/huggingface-extension/package.json
  extensions/inference-groq-extension/package.json
  extensions/inference-mistral-extension/package.json
  extensions/inference-nitro-extension/package.json
  extensions/inference-openai-extension/package.json
  extensions/inference-triton-trtllm-extension/package.json
  extensions/model-extension/package.json
  extensions/monitoring-extension/package.json
  extensions/monitoring-extension/src/node/index.ts
  extensions/tensorrt-llm-extension/package.json
  web/hooks/useActiveModel.ts
  web/hooks/useFactoryReset.ts
Labels: type: bug

#2687 fix: not able to update model setting in local api
  web/containers/Checkbox/index.tsx
  web/containers/ModelConfigInput/index.tsx
  web/containers/SliderRightPanel/index.tsx
  web/screens/Chat/EngineSetting/index.tsx
  web/screens/Chat/ModelSetting/SettingComponent.tsx
  web/screens/Chat/ModelSetting/index.tsx
  web/screens/Chat/Sidebar/index.tsx
  web/screens/LocalServer/index.tsx
Labels: type: bug

#2690 I test add clean jan folder and revert download url notification on discord
  .github/workflows/jan-electron-linter-and-test.yml
  .github/workflows/template-noti-discord-and-update-url-readme.yml
Labels: type: chore

#2691 fix: add markdown support for extension description
  extensions/inference-nitro-extension/package.json
  web/screens/Settings/CoreExtensions/ExtensionItem.tsx
  web/screens/Settings/CoreExtensions/index.tsx
Labels: type: bug

#2695 fix: allow smaller min width
  electron/managers/mainWindowConfig.ts
Labels: type: bug

#2696 fix: broken thread settings - component disabled
  web/screens/Chat/ModelSetting/index.tsx
Labels: type: bug

#2699 chore: Revert bump to 0.3.14 due to Nitro issue
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#2700 chore: Revert to 0.3.16 due to Nitro issue
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#2701 fix: add new shortcut to create new thread
  web/containers/Providers/KeyListener.tsx
  web/containers/ShortcutModal/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/Appearance/index.tsx
Labels: type: bug

#2711 fix: scrollable modal component
  uikit/src/modal/styles.scss
Labels: type: bug

#2712 enhancement: update input component dynamic text alignment
  core/src/types/setting/settingComponent.ts
  extensions/monitoring-extension/resources/settings.json
  uikit/src/input/index.tsx
  uikit/src/input/styles.scss
  web/containers/SliderRightPanel/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
Labels: type: enhancement

#2727 fix: cannot cancel model which is progress at 0 percent
  core/src/node/api/processors/download.ts
  core/src/node/helper/download.ts
Labels: type: bug

#2732 fix: log is not generated after clear log from setting
  core/src/types/api/index.ts
  extensions/monitoring-extension/src/node/logger.ts
Labels: type: bug

#2738 fix: the log server does not write to the log file
  server/helpers/logger.ts
Labels: type: bug

#2744 fix: user cannot click on copy icon of model id
  web/containers/DropdownListSidebar/index.tsx
Labels: type: bug

#2745 fix: cannot download phin34 model
  extensions/inference-nitro-extension/resources/models/phind-34b/model.json
Labels: type: bug

#2746 chore: default context length to 2048
  core/src/browser/extensions/model.ts
  extensions/inference-nitro-extension/resources/default_settings.json
  extensions/model-extension/resources/default-model.json
  extensions/model-extension/src/index.ts
  web/helpers/atoms/Model.atom.ts
  web/hooks/useModels.ts
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
Labels: type: chore

#2751 chore: correct copy for Jan data folder to highlight original Jan data folder intact upon relocation
  web/screens/Settings/Advanced/DataFolder/ModalChangeDirectory.tsx
Labels: type: chore

#2762 fix: broken stop word input - support multiple stop words
  web/hooks/useUpdateModelParameters.ts
  web/utils/componentSettings.ts
Labels: type: bug

#2766 feat: add LaTeX extension support via Marked
  web/package.json
  web/screens/Chat/SimpleTextMessage/index.tsx
Labels: type: feature request

#2765 fix: thread title not persisted
  web/containers/Providers/EventHandler.tsx
Labels: type: bug

#2769 refactor: good bye react-scroll-to-bottom
  web/containers/ListContainer/index.tsx
  web/screens/Chat/ChatBody/index.tsx
Labels: type: chore

#2770 fix: wrong condition for GPU acceleration
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#2789 fix: override cpu_threads setting from model.json
  core/src/node/api/restful/helper/startStopModel.ts
  extensions/assistant-extension/src/node/engine.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/monitoring-extension/src/node/logger.ts
  web/containers/ServerLogs/index.tsx
  web/screens/Chat/ModelSetting/predefinedComponent.ts
Labels: type: bug

#2807 fix: stop server if failed to load model
  web/hooks/useActiveModel.ts
  web/screens/LocalServer/index.tsx
Labels: type: bug

#2810 fix: infinite talking in auto thread titles generators
  web/containers/Providers/EventHandler.tsx
Labels: type: bug

#2778 Add workflow test openai api
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build.yml
  .github/workflows/jan-electron-linter-and-test.yml
  .github/workflows/jan-openai-api-test.yml
  .github/workflows/jan-server-build-nightly.yml
  .github/workflows/jan-server-build.yml
  docs/openapi/version.txt
  docs/tests/conftest.py
  docs/tests/pytest.ini
Labels: type: feature request

#2814 Fix macos ci
  .github/workflows/template-build-macos-x64.yml
Labels: type: bug

#2819 fix: remove scroll animation chat screen
  web/containers/ListContainer/index.tsx
Labels: type: bug
