Repository menloresearch/jan, pull requests merged in 2024-06, with the labels that each got.

#2978 feat: add input actions for setting item
  core/src/types/setting/settingComponent.ts
  extensions/model-extension/resources/settings.json
  web/.eslintrc.js
  web/helpers/atoms/AppConfig.atom.ts
  web/hooks/useLogs.ts
  web/screens/Settings/CoreExtensions/ExtensionItem.tsx
  web/screens/Settings/CoreExtensions/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailToggleItem/index.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: feature request

#2980 fix: missing markdown list and blockquotes
  web/styles/components/message.scss
Labels: type: bug

#2979 fix: quickask missing color schema
  web/app/search/SelectedText.tsx
  web/app/search/layout.tsx
Labels: type: bug

#2983 chore: upgrade version model extension for hf auth token
  extensions/model-extension/package.json
Labels: type: chore

#2982 fix: scan the models folder recursive to find model metadata file
  extensions/model-extension/src/index.ts
Labels: type: bug

#2989 fix: specific version for turbo
  Makefile
Labels: type: bug

#3011 fix: loading jan browser
  web/hooks/useLoadTheme.ts
Labels: type: chore

#3006 fix: duplicate role inside messages cause some model to refuse to answer
  extensions/inference-nitro-extension/bin/version.txt
  web/hooks/useSendChatMessage.ts
  web/utils/Stack.ts
Labels: type: bug

#3021 feat: update icon alert warning and copies tooltip model dropdown
  web/containers/Loader/ProgressCircle.tsx
  web/containers/ModelDropdown/index.tsx
  web/containers/ModelLabel/NotEnoughMemoryLabel.tsx
  web/containers/ModelLabel/SlowOnYourDeviceLabel.tsx
Labels: type: enhancement, type: feature request

#3019 feat: enable hotkey collapse right panel
  web/containers/Providers/KeyListener.tsx
  web/screens/Settings/Hotkeys/index.tsx
Labels: type: feature request

#3027 chore: Bump-cortex-0.4.13
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#3028 fix: enable window control button on linux
  web/containers/Layout/TopPanel/index.tsx
Labels: type: bug

#3034 chore: update some copy
  web/containers/ModelDropdown/index.tsx
Labels: type: chore

#3035 chore: Refactor/issue template and extension version bump
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  extensions/model-extension/package.json
Labels: type: chore

#3033 chore: Remove OpenAI test coverage
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/jan-openai-api-test.yml
Labels: type: chore

#3039 chore: update template check box
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: type: chore

#3051 chore: release 0.5.1 to main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/discussion-thread.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/epic-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/jan-openai-api-test.yml
  .github/workflows/jan-server-build-nightly.yml
  .github/workflows/nightly-integrate-cortex-cpp.yml
  Makefile
  electron/handlers/native.ts
  electron/managers/mainWindowConfig.ts
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/qwen2-7b/model.json
  extensions/inference-nitro-extension/rollup.config.ts
  extensions/inference-nvidia-extension/README.md
  extensions/inference-nvidia-extension/package.json
  extensions/inference-nvidia-extension/resources/models.json
  extensions/inference-nvidia-extension/resources/settings.json
  extensions/inference-nvidia-extension/src/index.ts
  extensions/inference-nvidia-extension/tsconfig.json
  extensions/inference-nvidia-extension/webpack.config.js
  extensions/model-extension/package.json
  extensions/model-extension/src/index.ts
  web/containers/Layout/TopPanel/index.tsx
  web/containers/Loader/ProgressCircle.tsx
  web/containers/ModelDropdown/index.tsx
  web/containers/ModelLabel/NotEnoughMemoryLabel.tsx
  web/containers/ModelLabel/SlowOnYourDeviceLabel.tsx
  web/containers/Providers/KeyListener.tsx
  web/hooks/useLoadTheme.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Settings/Hotkeys/index.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
  web/utils/Stack.ts
Labels: type: chore

#3049 chore: bump version marked-katex-extension
  web/package.json
Labels: type: enhancement, type: chore

#3048 fix: handle long words without space to avoid right panel disappears
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: bug

#3058 fix: position dropdown on my model
  web/screens/Settings/MyModels/MyModelList/index.tsx
Labels: type: bug

#3047 fix: model dropdown search by configured model
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#3080 fix: disable flash_attn if vulkan is enabled
  web/hooks/useActiveModel.ts
Labels: type: bug

#3083 chore: bump version (#3082)
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/aya-23-35b/model.json
  extensions/inference-nitro-extension/resources/models/aya-23-8b/model.json
  extensions/inference-nitro-extension/resources/models/codeninja-1.0-7b/model.json
  extensions/inference-nitro-extension/resources/models/codestral-22b/model.json
  extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
  extensions/inference-nitro-extension/resources/models/deepseek-coder-1.3b/model.json
  extensions/inference-nitro-extension/resources/models/deepseek-coder-34b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-2b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-7b/model.json
  extensions/inference-nitro-extension/resources/models/llama2-chat-70b/model.json
  extensions/inference-nitro-extension/resources/models/llama2-chat-7b/model.json
  extensions/inference-nitro-extension/resources/models/llama3-8b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/llama3-hermes-8b/model.json
  extensions/inference-nitro-extension/resources/models/llamacorn-1.1b/model.json
  extensions/inference-nitro-extension/resources/models/mistral-ins-7b-q4/model.json
  extensions/inference-nitro-extension/resources/models/noromaid-7b/model.json
  extensions/inference-nitro-extension/resources/models/openchat-3.5-7b/model.json
  extensions/inference-nitro-extension/resources/models/phi3-3.8b/model.json
  extensions/inference-nitro-extension/resources/models/phi3-medium/model.json
  extensions/inference-nitro-extension/resources/models/phind-34b/model.json
  extensions/inference-nitro-extension/resources/models/qwen-7b/model.json
  extensions/inference-nitro-extension/resources/models/qwen2-7b/model.json
  extensions/inference-nitro-extension/resources/models/stable-zephyr-3b/model.json
  extensions/inference-nitro-extension/resources/models/stealth-v1.2-7b/model.json
  extensions/inference-nitro-extension/resources/models/tinyllama-1.1b/model.json
  extensions/inference-nitro-extension/resources/models/trinity-v1.2-7b/model.json
  extensions/inference-nitro-extension/resources/models/vistral-7b/model.json
  extensions/inference-nitro-extension/resources/models/wizardcoder-13b/model.json
  extensions/inference-nitro-extension/resources/models/yi-34b/model.json
Labels: type: chore

#3098 chore: cortex version update
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#3101 fix: handle words without space
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: bug

#3108 feat: enable right click to show setting on thread items
  web/screens/Thread/ThreadLeftPanel/ModalCleanThread/index.tsx
  web/screens/Thread/ThreadLeftPanel/ModalDeleteThread/index.tsx
  web/screens/Thread/ThreadLeftPanel/ModalEditTitleThread/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
Labels: type: feature request

#3107 fix: handle long thread title without space
  web/containers/ModelDropdown/index.tsx
  web/screens/Thread/ThreadLeftPanel/ModalCleanThread/index.tsx
  web/screens/Thread/ThreadLeftPanel/ModalDeleteThread/index.tsx
  web/screens/Thread/ThreadLeftPanel/ModalEditTitleThread/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
  web/screens/Thread/ThreadRightPanel/Tools/index.tsx
Labels: type: bug

#3111 chore: Bump-cortex-0.4.17
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore
