Repository menloresearch/jan, pull requests merged in 2024-09, with the labels that each got.

#3480 fix: electron window
  electron/managers/mainWindowConfig.ts
Labels: type: bug

#3538 fix: using type text instead number for avoid region issue
  web/containers/SliderRightPanel/index.tsx
Labels: type: bug

#3554 feat: add setting options to dropdown menu
  core/src/types/api/index.ts
  electron/managers/window.ts
  electron/utils/menu.ts
  web/containers/Layout/index.tsx
Labels: type: feature request

#3514 fix: disabled UI RAG and tools
  joi/src/core/Tabs/index.tsx
  joi/src/core/Tabs/styles.scss
  web/containers/ModelDropdown/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: bug

#3553 chore: copy edit for model setting
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: chore

#3540 chore: setup jest for unit test hooks and component from joi
  .gitignore
  joi/jest.config.js
  joi/jest.setup.js
  joi/package.json
  joi/src/core/Accordion/Accordion.test.tsx
  joi/src/core/Badge/Badge.test.tsx
  joi/src/core/Badge/index.tsx
  joi/src/core/Button/Button.test.tsx
  joi/src/core/Button/index.tsx
  joi/src/hooks/useClickOutside/useClickOutside.test.tsx
  joi/src/hooks/useClipboard/useClipboard.test.ts
  joi/src/hooks/useMediaQuery/useMediaQuery.test.ts
  joi/src/hooks/useOs/useOs.test.ts
  joi/src/hooks/usePageLeave/usePageLeave.test.ts
  joi/src/hooks/useTextSelection/useTextSelection.test.ts
  joi/tsconfig.json
Labels: type: chore

#3466 feat: enable search model dropdown by configured model
  web/containers/ModelDropdown/index.tsx
Labels: type: feature request

#3498 test: add core modules test cases
  .github/workflows/jan-electron-linter-and-test.yml
  .gitignore
  Makefile
  core/jest.config.js
  core/package.json
  core/src/browser/core.test.ts
  core/src/browser/events.test.ts
  core/src/browser/extension.test.ts
  core/src/browser/extensions/engines/helpers/sse.test.ts
  core/src/browser/index.test.ts
  core/src/node/api/common/adapter.test.ts
  core/src/node/api/common/handler.test.ts
  core/src/node/api/processors/app.test.ts
  core/src/node/api/processors/download.test.ts
  core/src/node/api/processors/extension.test.ts
  core/src/node/api/processors/fs.test.ts
  core/src/node/api/processors/fsExt.test.ts
  core/src/node/api/processors/processor.test.ts
  core/src/node/api/restful/app/download.test.ts
  core/src/node/api/restful/app/handlers.test.ts
  core/src/node/api/restful/common.test.ts
  core/src/node/api/restful/helper/configuration.test.ts
  core/src/node/api/restful/v1.test.ts
  core/src/node/extension/extension.test.ts
  core/src/node/extension/manager.test.ts
  core/src/node/extension/store.test.ts
  core/src/node/helper/config.test.ts
  core/src/node/helper/download.test.ts
  core/src/node/helper/logger.test.ts
  core/src/node/helper/module.test.ts
  core/src/node/helper/path.test.ts
  core/src/node/helper/resource.test.ts
  core/src/types/assistant/assistantEvent.test.ts
  core/src/types/file/index.ts
  core/testRunner.js
  core/tests/node/path.test.ts
  core/tsconfig.json
  jest.config.js
  web/utils/Stack.test.ts
  web/utils/componentSettings.test.ts
  web/utils/datetime.test.ts
  web/utils/jsonToCssVariables.test.ts
  web/utils/memory.test.ts
  web/utils/predefinedComponent.test.ts
  web/utils/thread.test.ts
  web/utils/titleUtils.test.ts
Labels: type: chore

#3581 test: fix import from components
  .github/workflows/jan-electron-linter-and-test.yml
  web/helpers/atoms/HuggingFace.atom.ts
  web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/index.tsx
  web/utils/predefinedComponent.ts
Labels: type: chore

#3585 chore: update copy when retrieval turn off
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: chore

#3609 fix: missing type number for slider input right panel
  web/containers/SliderRightPanel/index.tsx
Labels: type: bug

#3588 test: finished all ui components test
  joi/package.json
  joi/src/core/Button/Button.test.tsx
  joi/src/core/Checkbox/Checkbox.test.tsx
  joi/src/core/Input/Input.test.tsx
  joi/src/core/Input/index.tsx
  joi/src/core/Modal/Modal.test.tsx
  joi/src/core/Progress/Progress.test.tsx
  joi/src/core/Progress/index.tsx
  joi/src/core/ScrollArea/ScrollArea.test.tsx
  joi/src/core/Select/Select.test.tsx
  joi/src/core/Slider/Slider.test.tsx
  joi/src/core/Switch/Switch.test.tsx
  joi/src/core/Tabs/Tabs.test.tsx
  joi/src/core/TextArea/TextArea.test.tsx
  joi/src/core/Tooltip/Tooltip.test.tsx
Labels: type: chore

#3615 test: add tests to model settings's Slider Input
  .gitignore
  electron/.eslintrc.js
  web/.eslintrc.js
  web/containers/SliderRightPanel/index.test.tsx
  web/containers/SliderRightPanel/index.tsx
  web/hooks/useCreateNewThread.ts
  web/jest.config.js
  web/package.json
  web/tsconfig.json
Labels: type: chore

#3602 fix: #3549, #3552 - Inference on CPU is slower on Jan 0.5.3
  .github/workflows/nightly-integrate-cortex-cpp.yml
  core/src/node/api/restful/helper/startStopModel.ts
  extensions/inference-nitro-extension/download.bat
  extensions/inference-nitro-extension/download.sh
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/rollup.config.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/node/execute.test.ts
  extensions/inference-nitro-extension/src/node/execute.ts
  extensions/inference-nitro-extension/src/node/index.test.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/inference-nitro-extension/tsconfig.json
Labels: type: bug

#3635 fix: prevent value empty string on slider right panel
  .github/workflows/jan-electron-linter-and-test.yml
  web/containers/SliderRightPanel/index.test.tsx
  web/containers/SliderRightPanel/index.tsx
Labels: type: bug

#3654 chore: deprecate preserve thread settings
  electron/.eslintrc.js
  web/.eslintrc.js
  web/screens/Settings/Advanced/index.tsx
Labels: type: chore

#3655 fix: change Phi-3 Mini Instruct 4K to cortexso repository
  extensions/inference-groq-extension/resources/models.json
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/aya-23-8b/model.json
  extensions/inference-nitro-extension/resources/models/deepseek-coder-1.3b/model.json
  extensions/inference-nitro-extension/resources/models/deepseek-coder-34b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-1.1-7b/model.json
  extensions/inference-nitro-extension/resources/models/llama3-8b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/llama3.1-70b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/llama3.1-8b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/mistral-ins-7b-q4/model.json
  extensions/inference-nitro-extension/resources/models/phi3-3.8b/model.json
  extensions/inference-nitro-extension/resources/models/phi3-medium/model.json
  extensions/inference-nitro-extension/resources/models/qwen2-7b/model.json
Labels: type: bug

#3644 fix: issue responsive and missing size on starter screen
  web/containers/Layout/RibbonPanel/index.tsx
  web/jest.config.js
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.test.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/screens/Thread/index.tsx
Labels: type: bug

#3663 chore: temporary disabled starter screen
  web/hooks/useStarterScreen.ts
  web/screens/Thread/index.tsx
Labels: type: chore

#3665 fix: correct prompt template for Phi3 Medium model
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/phi3-medium/model.json
Labels: type: bug

#3670 fix: phi3 medium prompt template
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/phi3-medium/model.json
Labels: type: bug

#3687 fix: #3667 - The recommended label should be hidden
  web/containers/ModelLabel/ModelLabel.test.tsx
  web/containers/ModelLabel/index.tsx
Labels: type: bug

#3661 fix: small leftover issues with new starter screen
  electron/tests/e2e/thread.e2e.spec.ts
  web/containers/Layout/RibbonPanel/index.tsx
  web/containers/Layout/TopPanel/index.tsx
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useStarterScreen.ts
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/screens/Thread/index.test.tsx
Labels: type: bug

#3695 feat: textarea auto resize
  joi/src/core/TextArea/TextArea.test.tsx
  joi/src/core/TextArea/index.tsx
  web/containers/ModelConfigInput/index.tsx
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: feature request

#3694 chore: Copyfix
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
  web/screens/LocalServer/LocalServerLeftPanel/index.tsx
  web/screens/Settings/Advanced/FactoryReset/ModalConfirmReset.tsx
  web/screens/Settings/Advanced/FactoryReset/index.tsx
  web/screens/Settings/CancelModelImportModal/index.tsx
Labels: type: chore

#3702 fix: update the condition for generating the title
  web/containers/Providers/EventHandler.tsx
Labels: type: bug

#3706 fix: enhance various minor UI elements
  web/helpers/atoms/Setting.atom.ts
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/MyModels/MyModelList/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
Labels: type: bug

#3710 fix: remove title local API server page
  web/screens/LocalServer/LocalServerLeftPanel/index.tsx
Labels: type: bug

#3707 test: update test coverage UI component Joi
  joi/src/hooks/useClickOutside/index.tsx
  joi/src/hooks/useClickOutside/useClickOutside.test.tsx
  joi/src/hooks/useMediaQuery/index.ts
  joi/src/hooks/useMediaQuery/useMediaQuery.test.ts
  joi/src/hooks/useOs/index.tsx
  joi/src/hooks/useOs/useOs.test.ts
  joi/src/index.test.ts
Labels: type: chore

#3709 fix: #3693 broken thread.json should not break the entire threads
  extensions/conversational-extension/jest.config.js
  extensions/conversational-extension/package.json
  extensions/conversational-extension/src/Conversational.test.ts
  extensions/conversational-extension/src/index.ts
  extensions/conversational-extension/src/jsonUtil.ts
  extensions/conversational-extension/tsconfig.json
  extensions/model-extension/src/helpers/path.test.ts
  extensions/model-extension/src/helpers/path.ts
  jest.config.js
  web/containers/ErrorMessage/index.test.tsx
  web/containers/ListContainer/index.test.tsx
  web/containers/ListContainer/index.tsx
  web/containers/Loader/GenerateResponse.test.tsx
  web/containers/Loader/ModelReload.test.tsx
  web/containers/Loader/ProgressCircle.test.tsx
  web/containers/Loader/ProgressCircle.tsx
  web/containers/ModalTroubleShoot/AppLogs.test.tsx
  web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.test.tsx
Labels: type: bug

#3720 fix: toolbar overlap chat input
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: bug

#3723 chore: The monorepo jest configs should not cover extensions - they would be moved to mini repositories soon
  jest.config.js
Labels: type: chore

#3725 fix: #3558 wrong model metadata import or download from HuggingFace
  extensions/model-extension/src/index.test.ts
  extensions/model-extension/src/index.ts
  extensions/model-extension/src/node/index.ts
  extensions/model-extension/src/node/node.test.ts
Labels: type: bug

#3724 fix: #3513 - Anthropic extension does not forward the system prompt
  extensions/inference-anthropic-extension/jest.config.js
  extensions/inference-anthropic-extension/package.json
  extensions/inference-anthropic-extension/src/anthropic.test.ts
  extensions/inference-anthropic-extension/src/index.ts
  extensions/inference-anthropic-extension/tsconfig.json
Labels: type: bug

#3721 fix: #3515 - The default assistant instructions are ignored
  web/hooks/useCreateNewThread.test.ts
  web/hooks/useCreateNewThread.ts
Labels: type: bug

#3728 fix: #3698 - o1 preview models do not work with max_tokens
  extensions/inference-openai-extension/jest.config.js
  extensions/inference-openai-extension/src/OpenAIExtension.test.ts
  extensions/inference-openai-extension/src/index.ts
  extensions/inference-openai-extension/tsconfig.json
Labels: type: bug

#3730 enhance: tabs component in model selection
  joi/src/core/Tabs/Tabs.test.tsx
  joi/src/core/Tabs/index.tsx
  joi/src/core/Tabs/styles.scss
  web/containers/ModelDropdown/index.test.tsx
  web/containers/ModelDropdown/index.tsx
Labels: enhancement

#3729 fix: #3673 - API responds with Request body is too large
  core/src/node/api/restful/helper/builder.test.ts
  core/src/node/api/restful/helper/builder.ts
  server/index.ts
Labels: type: bug

#3731 fix: #3727 LLM model download fail can still be used
  core/src/node/api/processors/download.test.ts
  core/src/node/api/processors/download.ts
Labels: type: bug

#3732 fix: #3703 - Deepseek-Coder-33B-Instruct is incompatible
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/deepseek-coder-1.3b/model.json
  extensions/inference-nitro-extension/resources/models/deepseek-coder-34b/model.json
Labels: type: bug

#3733 fix: wrong model download location when there is a mismatch model_id
  core/src/node/api/processors/download.ts
  core/src/types/file/index.ts
  core/src/types/model/modelInterface.ts
  extensions/model-extension/src/index.test.ts
  extensions/model-extension/src/index.ts
Labels: type: bug

#3734 ci: auto trigger jan docs ci for new release
  .github/workflows/auto-trigger-jan-docs.yaml
Labels: type: ci

#3741 fix: #3491 - Unable to use tensorrt-llm
  extensions/tensorrt-llm-extension/jest.config.js
  extensions/tensorrt-llm-extension/package.json
  extensions/tensorrt-llm-extension/rollup.config.ts
  extensions/tensorrt-llm-extension/src/index.test.ts
  extensions/tensorrt-llm-extension/src/index.ts
  extensions/tensorrt-llm-extension/tsconfig.json
  web/hooks/useDownloadModel.ts
Labels: type: bug

#3736 fix: correct model dropdown for local models
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
  web/containers/ModelDropdown/index.test.tsx
  web/containers/ModelDropdown/index.tsx
  web/containers/Providers/EventHandler.tsx
  web/containers/SetupRemoteModel/index.tsx
  web/helpers/atoms/Model.atom.test.ts
  web/helpers/atoms/Model.atom.ts
  web/hooks/useStarterScreen.ts
  web/screens/Settings/MyModels/MyModelList/index.tsx
  web/screens/Settings/MyModels/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadRightPanel/index.tsx
  web/utils/modelEngine.test.ts
  web/utils/modelEngine.ts
Labels: type: bug

#3742 fix: model dropdown should show recommended models to download
  web/helpers/atoms/Model.atom.test.ts
  web/helpers/atoms/Model.atom.ts
Labels: type: bug
