Repository menloresearch/jan, pull requests merged in 2024-05, with the labels that each got.

#2860 chore: remove nutjs
  electron/package.json
  electron/utils/selectedText.ts
Labels: type: chore

#2856 Fix scrolling issue on edit chat input
  web/screens/Chat/EditChatInput/index.tsx
Labels: type: enhancement

#2868 feat: add remote model command-r
  extensions/inference-cohere-extension/resources/models.json
Labels: type: feature request

#2836 feat: add model gpt-4 turbo
  extensions/inference-openai-extension/resources/models.json
Labels: type: feature request

#2870 fix: validate max_token from context_length value
  web/hooks/useCreateNewThread.ts
  web/screens/Chat/ModelSetting/SettingComponent.tsx
  web/screens/Chat/Sidebar/index.tsx
Labels: type: bug

#2869 feat: implement-inference-martian-extension
  extensions/inference-martian-extension/README.md
  extensions/inference-martian-extension/package.json
  extensions/inference-martian-extension/resources/models.json
  extensions/inference-martian-extension/resources/settings.json
  extensions/inference-martian-extension/src/index.ts
  extensions/inference-martian-extension/tsconfig.json
  extensions/inference-martian-extension/webpack.config.js
Labels: P2: nice to have

#2871 fix: validate context length
  web/screens/Chat/ModelSetting/SettingComponent.tsx
  web/screens/Chat/ModelSetting/predefinedComponent.ts
Labels: type: bug

#2867 Feat: Correct context length for models
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/codeninja-1.0-7b/model.json
  extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
  extensions/inference-nitro-extension/resources/models/deepseek-coder-1.3b/model.json
  extensions/inference-nitro-extension/resources/models/deepseek-coder-34b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-2b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-7b/model.json
  extensions/inference-nitro-extension/resources/models/mistral-ins-7b-q4/model.json
  extensions/inference-nitro-extension/resources/models/mixtral-8x7b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/noromaid-7b/model.json
  extensions/inference-nitro-extension/resources/models/openchat-3.5-7b/model.json
  extensions/inference-nitro-extension/resources/models/phind-34b/model.json
  extensions/inference-nitro-extension/resources/models/qwen-7b/model.json
  extensions/inference-nitro-extension/resources/models/stealth-v1.2-7b/model.json
  extensions/inference-nitro-extension/resources/models/trinity-v1.2-7b/model.json
  extensions/inference-nitro-extension/resources/models/vistral-7b/model.json
  extensions/inference-nitro-extension/resources/models/wizardcoder-13b/model.json
Labels: type: feature request

#2874 fix: stop auto scroll if user manually scrolling up
  web/containers/ListContainer/index.tsx
  web/screens/Chat/ChatBody/index.tsx
Labels: type: bug

#2883 feat: add deeplink support
  core/src/types/api/index.ts
  electron/handlers/native.ts
  electron/main.ts
  electron/managers/window.ts
  electron/package.json
  electron/utils/dev.ts
  web/containers/Layout/index.tsx
  web/containers/LoadingModal/index.tsx
  web/containers/Providers/DeepLinkListener.tsx
  web/containers/Providers/index.tsx
Labels: type: feature request

#2893 fix: deeplink when app not open on linux
  electron/managers/window.ts
  web/containers/LoadingModal/index.tsx
  web/containers/Providers/DeepLinkListener.tsx
Labels: type: bug

#2907 fix: cohere stream param does not work
  core/src/browser/extensions/engines/helpers/sse.ts
  extensions/inference-cohere-extension/src/index.ts
Labels: type: bug

#2910 Change mac arm64 build use github runner
  .github/workflows/template-build-macos-arm64.yml
  .github/workflows/template-build-macos-x64.yml
Labels: type: chore

#2912 chore: replace nitro by cortex-cpp
  core/src/node/api/restful/helper/consts.ts
  core/src/node/api/restful/helper/startStopModel.ts
  core/src/node/helper/resource.ts
  extensions/assistant-extension/src/node/index.ts
  extensions/assistant-extension/src/node/retrieval.ts
  extensions/assistant-extension/src/tools/retrieval.ts
  extensions/inference-nitro-extension/.gitignore
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/download.bat
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/rollup.config.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/node/execute.test.ts
  extensions/inference-nitro-extension/src/node/execute.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/tensorrt-llm-extension/src/node/index.ts
Labels: type: chore

#2921 fix: cortex process is not terminated properly
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/src/node/index.ts
Labels: type: bug

#2928 Fix: Phi-3 doesn't display
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/phi3-3.8b/model.json
  extensions/inference-nitro-extension/rollup.config.ts
Labels: type: bug

#2931 fix: fix crash when model name not ready
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelSegmentInfo/index.tsx
Labels: type: bug

#2935 Replace deprecated steps github action
  .github/workflows/jan-electron-build.yml
Labels: type: chore

#2939 docs: Update README.md
  README.md
Labels: type: chore

#2937 fix: unchange title and last message when clean or delete message
  web/helpers/atoms/ChatMessage.atom.ts
  web/hooks/useDeleteThread.ts
  web/screens/Chat/MessageToolbar/index.tsx
Labels: type: bug

#2962 chore: Bump-cortex-0.4.11
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#2963 fix: adjustment minor UI from qa feedback
  themes/dark-dimmed/theme.json
  web/containers/Layout/BottomPanel/DownloadingState/index.tsx
  web/containers/Layout/RibbonPanel/index.tsx
  web/containers/Layout/TopPanel/index.tsx
  web/containers/LeftPanelContainer/index.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/EditModelInfoModal/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadLeftPanel/ModalEditTitleThread/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
Labels: type: bug, type: enhancement

#2966 Chore: Model Hub update
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/codestral-22b/model.json
  extensions/inference-nitro-extension/resources/models/mistral-ins-7b-q4/model.json
  extensions/inference-nitro-extension/resources/models/phi3-medium/model.json
  extensions/inference-nitro-extension/rollup.config.ts
  extensions/model-extension/resources/default-model.json
Labels: Release Comms

#2967 fix: wrong direction icon collapse right panel
  electron/utils/setup.ts
  joi/src/core/Modal/styles.scss
  joi/src/core/ScrollArea/index.tsx
  web/app/layout.tsx
  web/containers/CenterPanelContainer/index.tsx
  web/containers/Layout/BottomPanel/index.tsx
  web/containers/Layout/TopPanel/index.tsx
  web/containers/ModalTroubleShoot/AppLogs.tsx
  web/containers/ModalTroubleShoot/DeviceSpecs.tsx
  web/containers/ModalTroubleShoot/index.tsx
  web/containers/ModelDropdown/index.tsx
  web/containers/ServerLogs/index.tsx
  web/screens/LocalServer/LocalServerRightPanel/index.tsx
  web/screens/Settings/Appearance/index.tsx
Labels: type: bug

#2970 fix: clickable remote model
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#2974 feat: allow user to register their access token
  extensions/model-extension/resources/settings.json
  extensions/model-extension/rollup.config.ts
  extensions/model-extension/src/index.ts
Labels: type: feature request

#2975 fix: theme migration overwrite existing theme
  electron/utils/migration.ts
Labels: type: bug

#2972 feat: update setting tooltip explainer
  web/utils/predefinedComponent.ts
Labels: type: enhancement, type: feature request

#2976 fix: glitch modal troubleshoot
  web/containers/ModalTroubleShoot/AppLogs.tsx
  web/containers/ModalTroubleShoot/DeviceSpecs.tsx
  web/containers/ModalTroubleShoot/index.tsx
  web/containers/ServerLogs/index.tsx
Labels: type: bug
