Repository menloresearch/jan, pull requests merged in 2024-11, with the labels that each got.

#3925 chore: beta version add discord notification
  .github/workflows/jan-electron-build-beta.yml
Labels: type: chore

#3917 feat: expand the clickable areas ribbon panel
  web/containers/Layout/RibbonPanel/index.tsx
Labels: type: feature request

#3919 ui: minor update list model running system monitor
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
Labels: type: enhancement

#3927 fix: text align my model list and import model
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
  web/screens/Settings/MyModels/MyModelList/index.tsx
Labels: type: bug

#3926 feat: show model id on local api serve page
  web/screens/LocalServer/LocalServerRightPanel/index.tsx
Labels: type: feature request

#3928 fix: edit chat input
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: bug

#3940 fix: slate react version
  web/package.json
Labels: type: bug

#3936 fix: inconsistent left panel background when responsive
  themes/joi-dark/theme.json
Labels: type: bug

#3937 ui: reduced aggressive blur effect on the modal component
  joi/src/core/Modal/styles.scss
  themes/dark-dimmed/theme.json
  themes/joi-light/theme.json
  themes/night-blue/theme.json
Labels: type: enhancement

#3941 ux: auto-focus the chat input box
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
Labels: type: enhancement

#3938 ui: remove redundant animation
  web/containers/Layout/RibbonPanel/index.tsx
  web/screens/Settings/SettingLeftPanel/SettingItem/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
Labels: type: enhancement

#3942 ui: system monitor should not cover input box
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
Labels: type: enhancement

#3948 feat: new nightly app channel
  .github/scripts/rename-app-beta.sh
  .github/scripts/rename-app.sh
  .github/scripts/rename-uninstaller.sh
  .github/scripts/rename-workspace.sh
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos-arm64.yml
  .github/workflows/template-build-macos-x64.yml
  .github/workflows/template-build-windows-x64.yml
  electron/package.json
Labels: type: feature request

#3949 ui: remove generation interrupted message
  web/containers/ErrorMessage/index.test.tsx
  web/containers/ErrorMessage/index.tsx
Labels: type: enhancement

#3956 fix: Inconsistent model hub and download bar
  core/src/node/api/processors/download.ts
  core/src/types/file/index.ts
  web/containers/Layout/BottomPanel/DownloadingState/index.tsx
  web/containers/ModalCancelDownload/index.tsx
  web/hooks/useDownloadModel.ts
  web/hooks/useDownloadState.ts
  web/screens/Settings/MyModels/MyModelList/index.tsx
Labels: type: bug

#3957 fix: update themes migrations
  electron/utils/migration.ts
Labels: type: bug

#3960 chore: clean dangling process on exit and relaunch
  extensions/inference-cortex-extension/src/index.ts
Labels: type: chore

#3959 fix: remove tooltip and update text color model ID API server page
  web/screens/LocalServer/LocalServerRightPanel/index.tsx
Labels: type: bug

#3958 fix: text alignment on import model dialog
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
Labels: type: bug

#3962 chore: revert change app name
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos-arm64.yml
  .github/workflows/template-build-macos-x64.yml
  .github/workflows/template-build-windows-x64.yml
Labels: type: chore

#3961 chore: support customized OpenAI model.json
  extensions/model-extension/src/legacy/model-json.ts
  web/hooks/useModels.ts
Labels: type: chore

#3964 fix: make input clickable for copying instead of just the copy icon
  web/screens/LocalServer/LocalServerRightPanel/index.tsx
Labels: type: bug

#3965 fix: remove click outside system monitor panel
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
Labels: type: bug

#3967 fix: codeblock responsive push right panel
  web/styles/components/code-block.scss
Labels: type: bug

#3968 fix: starter screen text alignment and missing model size
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
Labels: type: bug

#3966 fix: export PATH env to engine destination folder to have additional dlls scoped
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-cortex-extension/src/node/index.ts
  extensions/model-extension/src/index.ts
Labels: type: bug

#3969 fix: handle edge cases syntax highlight
  web/screens/LocalServer/LocalServerRightPanel/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
  web/styles/components/code-block.scss
  web/styles/main.scss
Labels: type: bug

#3975 fix: ux edit message and copy api_key
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
  web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx
Labels: type: bug

#3963 chore: enable notification nightly
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos-arm64.yml
  .github/workflows/template-build-macos-x64.yml
  .github/workflows/template-build-windows-x64.yml
Labels: type: chore

#3978 chore: add cortex log into modal troubleshoot
  web/containers/ModalTroubleShoot/CortexLogs.tsx
  web/containers/ModalTroubleShoot/index.tsx
Labels: type: chore

#3979 fix: correct chat input cursor behavior when content is scrollable
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
Labels: type: bug

#3976 chore: retrieves the exact model running status upon message error
  core/src/browser/extensions/model.ts
  extensions/model-extension/src/cortex.ts
  extensions/model-extension/src/index.ts
  web/containers/Providers/EventHandler.tsx
  web/hooks/useModels.ts
Labels: type: chore

#3977 fix: update copy error message
  web/containers/ErrorMessage/index.tsx
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
Labels: type: bug

#3981 fix: alignment stop model btn system monitor
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
Labels: type: bug

#3980 chore: bump to latest release
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#3982 chore: proxies Jan APIs to cortex.cpp
  core/src/node/api/restful/common.ts
  core/src/node/api/restful/helper/builder.test.ts
  core/src/node/api/restful/helper/builder.ts
  core/src/node/api/restful/helper/consts.ts
Labels: type: chore

#3983 fix: migrate model settings and parameters but still allow model.yml editing
  extensions/model-extension/src/cortex.ts
  extensions/model-extension/src/index.ts
  web/containers/Providers/EventListener.tsx
  web/hooks/useModels.ts
Labels: type: bug

#3984 fix: edge cases highlight codeblock
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
Labels: type: bug, type: enhancement

#3989 fix: Model import name and ID are incorrect on Windows
  electron/utils/migration.ts
  web/hooks/useImportModel.ts
  web/package.json
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#3991 fix: inconsistent model dropdown list and my models
  core/src/node/api/processors/download.ts
  core/src/node/api/processors/fs.ts
  core/src/node/api/processors/fsExt.ts
  core/src/node/helper/path.ts
  extensions/model-extension/src/index.ts
  web/containers/ModelDropdown/index.tsx
  web/screens/Settings/SelectingModelModal/index.tsx
Labels: type: bug

#3993 fix: update the payload transform for OpenAI preview models
  extensions/inference-openai-extension/src/index.ts
Labels: type: bug

#3997 fix: remove cuda toolkit error message and bring back incremental model import
  web/hooks/useDropModelBinaries.ts
  web/hooks/useImportModel.ts
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
Labels: type: bug

#3999 fix: calculate base layout with system monitor panel
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
Labels: type: bug

#3998 chore: add qwen2.5-coder 14B and 32B models
  extensions/inference-cortex-extension/package.json
  extensions/inference-cortex-extension/resources/models/qwen2.5-coder-14b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/qwen2.5-coder-32b-instruct/model.json
  extensions/inference-cortex-extension/rollup.config.ts
  extensions/inference-cortex-extension/src/@types/global.d.ts
  extensions/inference-cortex-extension/src/index.ts
  extensions/model-extension/src/cortex.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: chore

#4018 chore: correct discord message notification
  .github/workflows/template-noti-discord-and-update-url-readme.yml
Labels: type: chore

#4010 feat: new UI code block and Enable copying of code blocks or plain text mid-stream
  web/containers/ListContainer/index.tsx
  web/jest.config.js
  web/mock/empty-mock.tsx
  web/package.json
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
  web/styles/components/code-block.scss
  web/styles/components/message.scss
  web/utils/codeLanguageExtension.ts
Labels: type: feature request

#4026 fix: max tokens params OpenRouter
  extensions/inference-openrouter-extension/resources/models.json
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
Labels: type: bug

#4027 fix: api local server max ctx len not update when switch model
  web/screens/LocalServer/LocalServerRightPanel/index.tsx
Labels: type: bug

#4031 fix: Jan 0.5.8 - Couldn’t upload documents to threads
  extensions/assistant-extension/src/node/engine.ts
  extensions/assistant-extension/src/node/retrieval.ts
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: bug

#4022 feat: support cortex.cpp engine variants
  .gitignore
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rollup.config.ts
  extensions/inference-cortex-extension/src/@types/global.d.ts
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-cortex-extension/src/node/execute.test.ts
  extensions/inference-cortex-extension/src/node/execute.ts
  extensions/inference-cortex-extension/src/node/index.ts
  web/hooks/useImportModel.ts
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
Labels: type: feature request

#4042 fix: improper line break on response message
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: bug

#4044 fix: model import edge cases
  extensions/inference-cortex-extension/src/index.ts
  extensions/model-extension/src/index.ts
  extensions/model-extension/src/legacy/delete.ts
  extensions/model-extension/src/legacy/model-json.ts
  web/hooks/useModels.ts
Labels: type: bug

#4050 fix: handle symlink model import failure - fallback to legacy model run
  extensions/inference-cortex-extension/src/index.ts
Labels: type: bug

#4051 fix: inconsistent error handling
  web/hooks/useActiveModel.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
Labels: type: bug

#4049 fix: correct OpenAI o1 model parameters
  core/src/browser/extensions/engines/helpers/sse.ts
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-openai-extension/resources/models.json
  extensions/inference-openai-extension/src/index.ts
  extensions/model-extension/package.json
  extensions/model-extension/src/index.ts
Labels: type: bug

#4052 fix: bump cortex.cpp to latest version - recursively scanning models folder should also include remote models
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-openrouter-extension/src/index.ts
  extensions/model-extension/src/index.ts
Labels: type: bug

#4058 fix: disable timeout on model load
  extensions/inference-cortex-extension/src/index.ts
Labels: type: bug

#4059 chore: remote models error handling
  core/src/browser/extensions/engines/helpers/sse.ts
  extensions/inference-cohere-extension/src/index.ts
  extensions/inference-openai-extension/package.json
  extensions/inference-openai-extension/resources/models.json
  extensions/inference-openai-extension/src/index.ts
  web/containers/ErrorMessage/index.test.tsx
  web/containers/ErrorMessage/index.tsx
  web/containers/Providers/EventHandler.tsx
Labels: type: chore

#4064 fix: temporary create a deps folder to have cortex.cpp work
  extensions/inference-cortex-extension/download.sh
Labels: type: bug

#4065 fix: correct download script to relocate dll files properly
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
Labels: type: bug

#4061 fix: edge cases empty code block
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
  web/styles/components/code-block.scss
Labels: type: bug

#4068 feat: configure HuggingfaceToken via cortex.cpp
  extensions/model-extension/src/index.ts
  extensions/monitoring-extension/src/node/index.ts
  web/hooks/useSettings.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: feature request

#4070 chore: version bump 0.5.9
  web/package.json
Labels: type: chore

#4075 fix: Phi 3 Mini Instruct model download url replacement
  extensions/inference-cortex-extension/package.json
  extensions/inference-cortex-extension/resources/models/phi3-3.8b/model.json
  extensions/inference-cortex-extension/resources/models/phi3-medium/model.json
  web/hooks/useModels.ts
Labels: type: bug

#4079 fix: factory reset hang on wiping data
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-cortex-extension/src/node/cpuInfo.ts
  extensions/inference-cortex-extension/src/node/execute.ts
  web/hooks/useFactoryReset.test.ts
  web/hooks/useFactoryReset.ts
Labels: type: bug

#4077 fix: model params settings local api server
  joi/src/core/Slider/index.tsx
  joi/src/core/Slider/styles.scss
  web/helpers/atoms/LocalServer.atom.ts
  web/screens/LocalServer/LocalServerLeftPanel/index.tsx
  web/screens/LocalServer/LocalServerRightPanel/index.tsx
Labels: type: bug

#4083 fix: auto select model when finished download from starter screen
  web/hooks/useStarterScreen.ts
Labels: type: bug

#4076 fix: responsive vulkan support
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#4074 fix: disabled shortcut create new thread on starter screen
  web/containers/Providers/KeyListener.tsx
Labels: type: bug

#4072 fix: reorder alphabetical cloud model on starter screen
  web/screens/Settings/Hotkeys/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
Labels: type: bug

#4099 fix: vulkan responsive
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#4109 fix: handle case markdown value no space
  web/styles/components/message.scss
Labels: type: bug

#4116 fix: 4086 - editing message should not send follow-up messages
  web/hooks/useSendChatMessage.ts
  web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx
Labels: type: bug

#4113 feat: stop word model setting
  core/src/types/setting/settingComponent.ts
  web/containers/EngineSetting/index.tsx
  web/containers/ModelConfigInput/index.tsx
  web/containers/ModelSetting/SettingComponent.tsx
  web/containers/ModelSetting/index.tsx
  web/containers/TagInput/index.test.tsx
  web/containers/TagInput/index.tsx
  web/screens/LocalServer/LocalServerRightPanel/index.tsx
  web/screens/Settings/ExtensionSetting/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/index.tsx
  web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.tsx
  web/screens/Thread/ThreadRightPanel/PromptTemplateSetting/index.tsx
  web/screens/Thread/ThreadRightPanel/index.tsx
  web/utils/componentSettings.ts
  web/utils/predefinedComponent.ts
Labels: type: feature request

#4105 fix: Line-number and border color code block UI
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
  web/styles/components/code-block.scss
Labels: type: bug

#4120 chore: remove a couple of deprecated server logics
  core/src/node/api/restful/common.ts
  core/src/node/api/restful/helper/builder.test.ts
  core/src/node/api/restful/helper/builder.ts
  core/src/node/api/restful/helper/startStopModel.test.ts
  core/src/node/api/restful/helper/startStopModel.ts
Labels: type: chore

#4112 enhancement: increased max-token limit claude-3.5
  extensions/inference-anthropic-extension/package.json
  extensions/inference-anthropic-extension/resources/models.json
Labels: type: enhancement

#4129 fix: memory leak when the code block response is too long
  web/package.json
Labels: type: bug

#4119 fix: 3986 - invalid request should show clear error message
  electron/tests/e2e/thread.e2e.spec.ts
  web/containers/ErrorMessage/index.tsx
Labels: type: bug

#4131 fix: 4012 - active model should be gone as soon as cortex.cpp server is killed
  extensions/inference-cortex-extension/src/index.ts
Labels: type: bug

#4130 feat: update Jan’s client request to adapt API changes from Cortex
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-cortex-extension/src/node/execute.test.ts
Labels: type: feature request

#4080 feat: Privacy docs
  docs/src/pages/docs/_meta.json
  docs/src/pages/docs/privacy.mdx
  web/package.json
Labels: type: feature request

#4132 fix: 4094 - gpu mode toggle on by default but not affect for the first time launch
  extensions/inference-cortex-extension/src/index.ts
  extensions/monitoring-extension/src/index.ts
Labels: type: bug

#4133 fix: 4096 - failed to get huggingface models
  core/src/browser/core.test.ts
  core/src/browser/core.ts
  core/src/node/api/processors/download.test.ts
  core/src/node/api/processors/download.ts
  core/src/types/api/index.ts
  web/containers/ModelSearch/index.tsx
  web/utils/huggingface.test.ts
  web/utils/huggingface.ts
Labels: type: bug

#4135 fix: default local model from starter screen
  web/screens/Thread/ThreadLeftPanel/index.tsx
Labels: type: bug

#4134 fix: memory leak lowlight dependencies
  web/package.json
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: bug

#4139 fix: 4098 - factory reset closes the app & never opens again on Linux
  core/src/types/api/index.ts
  electron/handlers/native.ts
  electron/utils/migration.ts
  web/hooks/useFactoryReset.test.ts
  web/hooks/useFactoryReset.ts
Labels: type: bug

#4144 chore: use rehype-highlight v6 update latex language
  web/package.json
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: chore

#4145 fix: handle case stop word too long
  web/containers/TagInput/index.tsx
Labels: type: bug

#4146 fix: app re-render issues caused by bad state handling
  web/containers/Layout/index.tsx
  web/containers/MainViewContainer/index.tsx
  web/containers/Providers/CoreConfigurator.tsx
  web/containers/Providers/index.tsx
  web/helpers/atoms/AppConfig.atom.ts
  web/helpers/atoms/Model.atom.ts
  web/helpers/atoms/Setting.atom.ts
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useStarterScreen.ts
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
  web/screens/Thread/index.tsx
Labels: type: bug

#4150 fix: convo component re-render every single token yield
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatItem/index.tsx
Labels: type: bug

#4152 fix: scroll bottom when switch thread
  web/containers/ListContainer/index.tsx
Labels: type: bug

#4156 fix: remove filter on recommend model
  web/hooks/useRecommendedModel.ts
  web/screens/Thread/ThreadLeftPanel/index.tsx
Labels: type: bug

#4160 chore: bump cortex.cpp and engine version
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rollup.config.ts
Labels: type: chore

#4159 fix: token speed should not be calculated based on state updates
  web/containers/Providers/ModelHandler.tsx
  web/helpers/atoms/ChatMessage.atom.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
  web/types/token.d.ts
Labels: type: bug

#4161 chore: bump cortex 1.0.4-rc4
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4163 chore: display error message from response
  web/containers/ModelSearch/index.tsx
  web/utils/huggingface.test.ts
  web/utils/huggingface.ts
Labels: type: chore
