Repository menloresearch/jan, pull requests merged in 2024-02, with the labels that each got.

#1862 feat: add start/stop model via http api
  core/src/node/api/common/builder.ts
  core/src/node/api/common/consts.ts
  core/src/node/api/common/startStopModel.ts
  core/src/node/api/routes/common.ts
  core/src/node/utils/index.ts
  core/src/types/index.ts
  core/src/types/miscellaneous/index.ts
  core/src/types/miscellaneous/promptTemplate.ts
  core/src/types/miscellaneous/systemResourceInfo.ts
  core/src/types/model/modelEntity.ts
  extensions/inference-nitro-extension/src/@types/global.d.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/inference-nitro-extension/src/node/utils.ts
  server/package.json
  web/hooks/useCreateNewThread.ts
  web/hooks/useSetActiveThread.ts
  web/screens/LocalServer/index.tsx
  web/screens/Settings/Advanced/FactoryReset/ModalConfirmReset.tsx
Labels: type: feature request

#1883 fix: the selected model auto revert back to previous used model with setting mismatch
  core/src/types/thread/threadEntity.ts
  extensions/inference-nitro-extension/bin/version.txt
  extensions/inference-nitro-extension/src/node/index.ts
  web/containers/DropdownListSidebar/index.tsx
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useDeleteThread.ts
  web/hooks/usePath.ts
  web/hooks/useRecommendedModel.ts
  web/hooks/useSendChatMessage.ts
  web/hooks/useThreads.ts
  web/hooks/useUpdateModelParameters.ts
  web/screens/Chat/ModelSetting/SettingComponent.tsx
  web/screens/Chat/SimpleTextMessage/index.tsx
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#1886 feat: Add default value for ngl
  extensions/inference-nitro-extension/src/node/index.ts
Labels: P1: important, type: feature request

#1809 feat: integrate umami
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-build-windows-x64.yml
  docs/.env.example
  electron/tests/hub.e2e.spec.ts
  electron/tests/navigation.e2e.spec.ts
  electron/tests/settings.e2e.spec.ts
  web/containers/Providers/index.tsx
  web/next.config.js
  web/screens/LocalServer/index.tsx
  web/utils/posthog.ts
  web/utils/umami.tsx
Labels: type: feature request

#1894 fix: display error message on model load fail
  core/src/node/api/common/startStopModel.ts
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/node/index.ts
  web/containers/Providers/EventHandler.tsx
  web/helpers/atoms/SystemBar.atom.ts
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useActiveModel.ts
  web/hooks/useGetSystemResources.ts
  web/hooks/useInference.ts
  web/hooks/useSendChatMessage.ts
  web/hooks/useSetActiveThread.ts
  web/screens/Chat/ChatBody/index.tsx
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/LoadModelErrorMessage/index.tsx
  web/screens/Chat/index.tsx
Labels: type: bug

#1895 fix: show generate response on message send
  web/containers/Providers/EventHandler.tsx
  web/hooks/useCreateNewThread.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/ThreadList/index.tsx
  web/screens/Settings/Advanced/FactoryReset/ModalConfirmReset.tsx
Labels: type: bug

#1898 docs: add troubleshoot undefined issue
  docs/docs/guides/08-troubleshooting/07-undefined-issue.mdx
Labels: type: documentation

#1901 fix: load model fail overlays thread message error
  web/hooks/useSetActiveThread.ts
  web/screens/Chat/ChatBody/index.tsx
  web/screens/Chat/LoadModelErrorMessage/index.tsx
  web/screens/Chat/index.tsx
Labels: type: bug

#1902 fix: openAIEmbedding now requires top level API Key configuration
  extensions/assistant-extension/src/node/tools/retrieval/index.ts
  extensions/inference-nitro-extension/src/index.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#1912 fix: broken manual import model with NA fields
  extensions/model-extension/src/index.ts
Labels: type: bug

#1913 fix: migration loading indicator
  web/containers/Providers/index.tsx
Labels: type: bug

#1918 Regression fix assitant extension codesign
  .github/scripts/auto-sign.sh
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build.yml
  .github/workflows/template-build-macos-arm64.yml
  .github/workflows/template-build-macos-x64.yml
  electron/merge-latest-ymls.js
  electron/package.json
Labels: P0: critical

#1917 Cloudflare R2 clean every 10 days
  .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
Labels: type: ci, type: chore

#1909 docs: update analytics content
  docs/docs/about/01-README.md
Labels: type: documentation

#1928 fix: umami analytics send app loaded event
  web/utils/umami.tsx
Labels: type: bug

#1927 docs: adding new feature for v0.4.6 to release checklist
  docs/docs/template/QA_script.md
Labels: type: documentation

#1923 fix: download model will close panel item hub
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
Labels: type: bug

#1930 fix: avoid users to create so many threads at the same time
  web/containers/Providers/EventHandler.tsx
  web/hooks/useCreateNewThread.ts
  web/screens/Chat/ThreadList/index.tsx
Labels: type: bug

#1730 feat: User Selectable GPUs and GPU-based Model Recommendations
  extensions/inference-nitro-extension/src/node/execute.ts
  extensions/inference-nitro-extension/src/node/nvidia.ts
  extensions/monitoring-extension/package.json
  extensions/monitoring-extension/src/module.ts
  web/containers/Layout/BottomBar/index.tsx
  web/helpers/atoms/SystemBar.atom.ts
  web/hooks/useGetSystemResources.ts
  web/hooks/useSettings.ts
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
  web/screens/Settings/Advanced/index.tsx
Labels: P1: important, type: feature request

#1944 fix: markdown render for chat completion role user
  web/screens/Chat/SimpleTextMessage/index.tsx
Labels: type: bug

#1934 feat: Playwright capture screenshot of Electron desktop app (Jan) on failures
  electron/playwright.config.ts
  electron/tests/e2e/hub.e2e.spec.ts
  electron/tests/e2e/navigation.e2e.spec.ts
  electron/tests/e2e/settings.e2e.spec.ts
  electron/tests/hub.e2e.spec.ts
  electron/tests/navigation.e2e.spec.ts
  electron/tests/pages/basePage.ts
  electron/tests/settings.e2e.spec.ts
Labels: roadmap: QA

#1949 chore: Add Author - Hiro
  docs/blog/authors.yml
Labels: P2: nice to have, type: chore

#1950 chore: Add author - Ashley
  docs/blog/authors.yml
Labels: type: chore

#1951 fix: update conditional check last status message
  web/containers/Providers/EventHandler.tsx
  web/helpers/atoms/ChatMessage.atom.ts
  web/hooks/useCreateNewThread.ts
Labels: type: bug

#1953 Update authors.yml hien
  docs/blog/authors.yml
Labels: type: chore

#1958 feat: integrate umami script locally
  web/public/umami_script.js
  web/utils/umami.tsx
Labels: type: feature request

#1973 docs: add author.yml
  docs/blog/authors.yml
Labels: type: documentation

#1971 fix: model failed to load but the server started successfully
  web/containers/Providers/EventHandler.tsx
  web/screens/LocalServer/index.tsx
Labels: type: bug

#1968 feat: add modal troubleshooting guideline
  web/containers/ModalTroubleShoot/AppLogs.tsx
  web/containers/ModalTroubleShoot/DeviceSpecs.tsx
  web/containers/ModalTroubleShoot/index.tsx
  web/containers/Providers/EventHandler.tsx
  web/containers/ServerLogs/index.tsx
  web/hooks/useLogs.tsx
  web/screens/Chat/ChatBody/index.tsx
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/LocalServer/Logs.tsx
  web/screens/LocalServer/index.tsx
  web/tsconfig.json
Labels: type: feature request

#1977 feat: revamp ui dropdown list model option
  uikit/src/select/styles.scss
  web/containers/DropdownListSidebar/index.tsx
  web/screens/LocalServer/index.tsx
Labels: type: feature request

#1984 fix: model downloads broken on nightly
  core/src/node/api/routes/download.ts
  electron/handlers/download.ts
  web/hooks/useDownloadState.ts
Labels: type: bug

#1991 Fix macos auto update failed on nightly build
  electron/package.json
Labels: type: bug

#1988 fix: retrieval stuck at generating response
  electron/main.ts
  electron/utils/dev.ts
  extensions/assistant-extension/package.json
  extensions/assistant-extension/src/index.ts
  extensions/assistant-extension/src/node/index.ts
  extensions/assistant-extension/src/node/tools/retrieval/index.ts
Labels: type: bug

#1981 docs: add Jan installation using Docker
  README.md
  docs/docs/guides/02-installation/05-docker.md
  docs/docs/guides/02-installation/07-nightly-build.md
  docs/docs/guides/02-installation/08-antivirus-compatibility-testing.md
Labels: type: documentation

#1993 fix: app fails gracefully with clear error messages
  electron/handlers/update.ts
  extensions/inference-openai-extension/src/helpers/sse.ts
  web/app/error.tsx
Labels: type: bug

#1994 fix: decouple thread summary update
  web/containers/Providers/EventHandler.tsx
Labels: type: bug

#1992 docs: update 03-gpu-not-used with RTX issues
  docs/docs/guides/08-troubleshooting/03-gpu-not-used.mdx
Labels: type: documentation

#1974 feat: add edit messages users
  web/containers/Providers/Jotai.tsx
  web/helpers/atoms/ChatMessage.atom.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/EditChatInput/index.tsx
  web/screens/Chat/MessageToolbar/index.tsx
  web/screens/Chat/SimpleTextMessage/index.tsx
Labels: type: feature request

#2001 fix: app stuck regenerating assistant response
  web/hooks/useSendChatMessage.ts
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/MessageQueuedBanner/index.tsx
  web/screens/Chat/MessageToolbar/index.tsx
Labels: type: bug

#2003 fix: lack of auto-cleaning mechanism for logs
  electron/main.ts
  electron/utils/log.ts
Labels: type: bug

#1990 feat: improvementUI GPU acceleration
  web/containers/GPUDriverPromptModal/index.tsx
  web/containers/Layout/BottomBar/index.tsx
  web/hooks/useSettings.ts
  web/screens/LocalServer/index.tsx
  web/screens/Settings/Advanced/index.tsx
Labels: type: feature request

#2011 refactor: reduce IPC & API handlers - shared node logics
  core/rollup.config.ts
  core/src/api/index.ts
  core/src/index.ts
  core/src/node/api/common/adapter.ts
  core/src/node/api/common/handler.ts
  core/src/node/api/index.ts
  core/src/node/api/processors/Processor.ts
  core/src/node/api/processors/app.ts
  core/src/node/api/processors/download.ts
  core/src/node/api/processors/extension.ts
  core/src/node/api/processors/fs.ts
  core/src/node/api/processors/fsExt.ts
  core/src/node/api/restful/app/download.ts
  core/src/node/api/restful/app/handlers.ts
  core/src/node/api/restful/common.ts
  core/src/node/api/restful/helper/builder.ts
  core/src/node/api/restful/helper/configuration.ts
  core/src/node/api/restful/helper/consts.ts
  core/src/node/api/restful/helper/startStopModel.ts
  core/src/node/api/restful/v1.ts
  core/src/node/api/routes/download.ts
  core/src/node/api/routes/extension.ts
  core/src/node/api/routes/fileManager.ts
  core/src/node/api/routes/fs.ts
  core/src/node/api/routes/index.ts
  core/src/node/api/routes/thread.ts
  core/src/node/api/routes/v1.ts
  core/src/node/extension/store.ts
  core/src/node/helper/config.ts
  core/src/node/helper/download.ts
  core/src/node/helper/index.ts
  core/src/node/helper/log.ts
  core/src/node/helper/module.ts
  core/src/node/helper/path.ts
  core/src/node/helper/resource.ts
  core/src/node/index.ts
  core/src/node/path.ts
  core/src/types/file/index.ts
  core/tests/node/path.test.ts
  electron/handlers/app.ts
  electron/handlers/common.ts
  electron/handlers/download.ts
  electron/handlers/extension.ts
  electron/handlers/fileManager.ts
  electron/handlers/fs.ts
  electron/handlers/native.ts
  electron/main.ts
  electron/utils/menu.ts
  electron/utils/path.ts
  electron/utils/versionDiff.ts
  web/services/restService.ts
Labels: type: chore

#2016 chore: bump nitro 0.3.9
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#2017 fix: resolve state update loop infinitive rerendering
  web/containers/ServerLogs/index.tsx
  web/hooks/useCreateNewThread.ts
  web/hooks/useLogs.tsx
  web/services/restService.ts
Labels: type: bug

#2018 fix: model path backward compatible
  .prettierignore
  .prettierrc
  core/src/node/api/processors/download.ts
  electron/.prettierrc
  extensions/conversational-extension/.prettierrc
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/model-extension/.prettierrc
  extensions/model-extension/src/index.ts
  web/.prettierignore
  web/.prettierrc
  web/services/restService.ts
Labels: type: bug

#2025 server install core using link instead of file
  Dockerfile
  Dockerfile.gpu
  server/package.json
Labels: type: chore

#2028 fix: local server blank parameters if there is no thread selected
  web/containers/DropdownListSidebar/index.tsx
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useThreads.ts
  web/screens/Chat/EngineSetting/index.tsx
  web/screens/Chat/ModelSetting/index.tsx
  web/screens/Chat/Sidebar/index.tsx
  web/screens/Chat/ThreadList/index.tsx
  web/screens/LocalServer/index.tsx
Labels: type: bug

#2026 fix: content setting right panel default to collapse
  web/containers/CardSidebar/index.tsx
  web/screens/Chat/Sidebar/index.tsx
Labels: type: bug

#2027 fix: factory reset not remove jan data folder
  core/src/node/api/processors/extension.ts
  electron/utils/dev.ts
  web/hooks/useFactoryReset.ts
Labels: type: bug

#2037 fix: app should generate thread title with length restriction
  web/containers/Providers/EventHandler.tsx
Labels: type: bug

#1924 docs: Updates Guide Using the Local Server
  docs/docs/guides/05-using-server/01-server.md
  docs/docs/guides/05-using-server/01-start-server.md
  docs/docs/guides/05-using-server/02-using-server.md
  docs/docs/guides/05-using-server/assets/01-choose-model.png
  docs/docs/guides/05-using-server/assets/01-local-api-view.gif
  docs/docs/guides/05-using-server/assets/01-running-server.gif
  docs/docs/guides/05-using-server/assets/01-server-options.png
  docs/docs/guides/05-using-server/assets/02-api-reference.png
  docs/docs/guides/05-using-server/assets/02-chat-example.png
Labels: type: documentation

#2046 fix: disable gpu drop down box if there's no GPU ready
  extensions/model-extension/src/index.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#2043 fix: download mutilple binaries
  extensions/model-extension/src/index.ts
  web/containers/Layout/BottomBar/DownloadingState/index.tsx
  web/containers/ModalCancelDownload/index.tsx
  web/containers/Providers/EventListener.tsx
  web/hooks/useDownloadModel.ts
  web/hooks/useDownloadState.ts
  web/screens/ExploreModels/ExploreModelItem/index.tsx
  web/screens/ExploreModels/ExploreModelItemHeader/index.tsx
  web/types/downloadState.d.ts
  web/utils/model.ts
Labels: type: bug

#2048 chore: refactor watch system resource hook
  web/containers/Layout/BottomBar/index.tsx
  web/containers/Providers/DataLoader.tsx
  web/containers/Providers/EventHandler.tsx
  web/containers/Providers/EventListener.tsx
  web/helpers/atoms/SystemBar.atom.ts
  web/hooks/useGetSystemResources.ts
Labels: type: chore

#2051 fix: update copy of message queue
  web/screens/Chat/index.tsx
Labels: type: bug

#2052 fix: local server start error should not change to started state
  core/src/node/helper/resource.ts
  server/index.ts
  web/screens/LocalServer/index.tsx
Labels: type: bug

#2053 fix: message should only be interrupted when i start another thread
  web/containers/Providers/EventHandler.tsx
  web/helpers/atoms/ChatMessage.atom.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useSetActiveThread.ts
  web/hooks/useThreads.ts
  web/screens/Chat/ChatInput/index.tsx
  web/screens/Chat/ThreadList/index.tsx
Labels: type: bug

#2054 docs:add-advanced-settings-https-proxy
  docs/docs/guides/09-advanced-settings/01-https-proxy.mdx
  docs/docs/guides/09-advanced-settings/README.mdx
  docs/docs/guides/09-advanced-settings/assets/01-https-proxy-jan-configure.png
Labels: type: documentation

#2065 fix: settings page state loop and dark theme
  core/src/node/helper/config.ts
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#2067 fix: should stop running the model when GPU settings are changed
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#2066 fix: infinity showed when haven't get total size
  web/hooks/useDownloadState.ts
Labels: type: bug

#2075 fix: check for updates should show no update are available on the latest build
  electron/handlers/update.ts
  electron/package.json
  electron/utils/menu.ts
  models/mistral-ins-7b-q4/model.json
  models/openhermes-neural-7b/model.json
  models/trinity-v1.2-7b/model.json
Labels: type: bug

#2077 fix: move jan data folder - error handling for no write permission granted
  web/screens/Settings/Advanced/DataFolder/index.tsx
Labels: type: bug

#2089 fix: server crashes on missing module
  core/src/node/api/restful/helper/builder.ts
  server/package.json
Labels: type: bug

#2091 fix: failed to send message blocks thread creation
  web/hooks/useSendChatMessage.ts
Labels: type: bug

#2083 fix: make text input scrollable
  web/screens/Chat/ChatInput/index.tsx
Labels: type: bug

#2099 fix: broken model.json update
  extensions/model-extension/package.json
  models/dolphin-phi-2/model.json
  models/llamacorn-1.1b/model.json
  models/stable-zephyr-3b/model.json
Labels: type: bug

#2098 fix: check if port is occupied before start local server
  core/src/node/api/processors/app.ts
  server/index.ts
  web/screens/LocalServer/index.tsx
Labels: type: bug

#2093 Fix bug #2005 docker blank website
  Dockerfile
  Dockerfile.gpu
  Makefile
  README.md
  docker-compose.yml
  extensions/inference-nitro-extension/src/index.ts
  server/helpers/setup.ts
  web/extension/ExtensionManager.ts
  web/next.config.js
  web/services/restService.ts
Labels: type: bug

#2102 fix: remove caret down icon when tab selected into remote model
  web/containers/DropdownListSidebar/index.tsx
Labels: type: bug

#2101 fix: failed to bind port - nitro error message copy
  extensions/inference-nitro-extension/src/index.ts
  extensions/inference-nitro-extension/src/node/index.ts
  web/containers/Providers/EventHandler.tsx
  web/screens/Chat/ErrorMessage/index.tsx
Labels: type: bug

#2110 fix: tools section should be expanded by default
  web/containers/Layout/BottomBar/index.tsx
  web/screens/Chat/Sidebar/index.tsx
Labels: type: bug

#2116 chore: add app version into log
  electron/main.ts
Labels: type: chore

#2113 fix: flow edit message
  web/containers/Layout/Ribbon/index.tsx
  web/screens/Chat/EditChatInput/index.tsx
  web/screens/Chat/MessageToolbar/index.tsx
  web/screens/Chat/ThreadList/index.tsx
Labels: type: bug, type: enhancement

#2120 fix: revert back menu actions
  electron/utils/menu.ts
Labels: type: bug

#2056 feat: Add nitro vulkan to support AMD GPU/ APU and Intel Arc GPU
  .gitignore
  extensions/inference-nitro-extension/download.bat
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/src/node/accelerator.ts
  extensions/inference-nitro-extension/src/node/execute.ts
  extensions/inference-nitro-extension/src/node/index.ts
  extensions/monitoring-extension/src/module.ts
  web/context/FeatureToggle.tsx
  web/hooks/useSettings.ts
  web/screens/Settings/Advanced/DataFolder/index.tsx
  web/screens/Settings/Advanced/index.tsx
Labels: type: feature request

#2097 feat: revamp system monitor
  electron/tests/e2e/navigation.e2e.spec.ts
  web/app/page.tsx
  web/constants/screens.ts
  web/containers/Layout/BottomBar/SystemItem/index.tsx
  web/containers/Layout/BottomBar/SystemMonitor/TableActiveModel/index.tsx
  web/containers/Layout/BottomBar/SystemMonitor/index.tsx
  web/containers/Layout/BottomBar/index.tsx
  web/containers/Layout/Ribbon/index.tsx
  web/containers/Layout/TopBar/CommandSearch/index.tsx
  web/containers/Layout/TopBar/index.tsx
  web/helpers/atoms/SystemBar.atom.ts
  web/screens/SystemMonitor/index.tsx
Labels: type: feature request

#2123 Regression: Linux vulkan binary path
  extensions/inference-nitro-extension/src/node/execute.ts
Labels: type: bug

#2124 Regression: bump nitro to 0.3.13
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: bug

#2125 fix: chore UI
  web/containers/ModalTroubleShoot/index.tsx
  web/screens/Chat/SimpleTextMessage/index.tsx
Labels: type: bug

#2128 fix: correct vulkan settings
  extensions/inference-nitro-extension/src/node/accelerator.ts
Labels: type: bug

#2127 docs: hide incomplete pages
  docs/docs/about/2035.mdx
  docs/docs/about/about.md
  docs/docs/about/roadmap.md
  docs/sidebars.js
  docs/src/containers/Footer/index.js
Labels: type: documentation

#2135 fix: system monitor ui
  web/containers/Layout/BottomBar/SystemMonitor/index.tsx
  web/containers/Layout/BottomBar/index.tsx
Labels: type: bug

#2150 docs: update run Jan in Docker mode
  docs/docs/guides/02-installation/05-docker.md
Labels: type: documentation

#1972 feat: add a simple way to convert Hugging Face model to GGUF
  core/src/extension.ts
  core/src/extensions/huggingface.ts
  core/src/extensions/index.ts
  core/src/types/huggingface/huggingfaceEntity.ts
  core/src/types/huggingface/huggingfaceInterface.ts
  core/src/types/huggingface/index.ts
  core/src/types/index.ts
  electron/package.json
  extensions/huggingface-extension/.gitignore
  extensions/huggingface-extension/.prettierrc
  extensions/huggingface-extension/README.md
  extensions/huggingface-extension/bin/mac-arm64/quantize
  extensions/huggingface-extension/download.bat
  extensions/huggingface-extension/package.json
  extensions/huggingface-extension/rollup.config.ts
  extensions/huggingface-extension/scripts/install_deps.py
  extensions/huggingface-extension/scripts/version.txt
  extensions/huggingface-extension/src/@types/global.d.ts
  extensions/huggingface-extension/src/index.ts
  extensions/huggingface-extension/src/node/index.ts
  extensions/huggingface-extension/tsconfig.json
  web/helpers/atoms/HFConverter.atom.ts
  web/hooks/useConvertHuggingFaceModel.ts
  web/hooks/useGetHFRepoData.ts
  web/screens/ExploreModels/HuggingFaceConvertingErrorModal/index.tsx
  web/screens/ExploreModels/HuggingFaceConvertingModal/index.tsx
  web/screens/ExploreModels/HuggingFaceModal/index.tsx
  web/screens/ExploreModels/HuggingFaceRepoDataLoadedModal/index.tsx
  web/screens/ExploreModels/HuggingFaceSearchErrorModal/index.tsx
  web/screens/ExploreModels/HuggingFaceSearchModal/index.tsx
  web/screens/ExploreModels/index.tsx
Labels: P1: important, type: feature request

#2152 feat: restore docusaurus style
  docs/src/styles/tweaks/markdown.scss
  docs/src/styles/tweaks/sidebar.scss
Labels: type: documentation, type: feature request

#2147 docs: update acknowledgements
  README.md
  docs/docs/acknowledgements.md
  docs/docs/how-we-work/engineering/acknowledgements.md
  docs/sidebars.js
Labels: type: documentation

#2156 chore: make convert gguf as experimental feature
  web/screens/ExploreModels/HuggingFaceConvertingErrorModal/index.tsx
  web/screens/ExploreModels/index.tsx
Labels: type: chore

#2166 Huggingface extension add codesign step for building on darwin
  extensions/huggingface-extension/package.json
  extensions/monitoring-extension/package.json
Labels: type: bug

#2158 fix: system monitor expand overlap tooltip ribbon
  web/containers/Layout/Ribbon/index.tsx
Labels: type: bug

#2172 fix: style list of gpus on system monitor
  web/containers/Layout/BottomBar/SystemMonitor/index.tsx
  web/utils/converter.ts
Labels: type: bug

#2168 feat: temporary remove dark mode :(
  uikit/src/button/styles.scss
  uikit/src/checkbox/styles.scss
  uikit/src/input/styles.scss
  uikit/src/progress/styles.scss
  uikit/src/select/styles.scss
  uikit/src/slider/styles.scss
  uikit/src/switch/styles.scss
  uikit/src/tooltip/styles.scss
  web/app/layout.tsx
  web/containers/CardSidebar/index.tsx
  web/containers/Checkbox/index.tsx
  web/containers/DropdownListSidebar/index.tsx
  web/containers/GPUDriverPromptModal/index.tsx
  web/containers/Layout/BottomBar/DownloadingState/index.tsx
  web/containers/Layout/BottomBar/ImportingModelState/index.tsx
  web/containers/Layout/Ribbon/index.tsx
  web/containers/Layout/TopBar/index.tsx
  web/containers/Loader/index.tsx
  web/containers/ModalTroubleShoot/AppLogs.tsx
  web/containers/ModalTroubleShoot/DeviceSpecs.tsx
  web/containers/ModalTroubleShoot/index.tsx
  web/containers/ModelConfigInput/index.tsx
  web/containers/OpenAiKeyInput/index.tsx
  web/containers/Providers/Theme.tsx
  web/containers/ServerLogs/index.tsx
  web/containers/SliderRightPanel/index.tsx
  web/containers/Toast/index.tsx
  web/hooks/useUserConfigs.ts
  web/screens/Chat/CleanThreadModal/index.tsx
  web/screens/Chat/DeleteThreadModal/index.tsx
  web/screens/Chat/ErrorMessage/index.tsx
  web/screens/Chat/Sidebar/index.tsx
  web/screens/Chat/ThreadList/index.tsx
  web/screens/ExploreModels/HuggingFaceSearchModal/index.tsx
  web/screens/ExploreModels/index.tsx
  web/screens/LocalServer/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/Appearance/TogglePrimary.tsx
  web/screens/Settings/Appearance/ToggleTheme.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/ImportModelOptionModal/ImportModelOptionSelection.tsx
  web/screens/Settings/ImportSuccessIcon/index.tsx
  web/screens/Settings/Models/Row.tsx
  web/screens/Settings/SelectingModelModal/index.tsx
  web/screens/Settings/SettingMenu/index.tsx
  web/screens/Settings/index.tsx
  web/styles/components/message.scss
  web/types/appearance.d.ts
Labels: type: enhancement, type: feature request

#2177 fix space between progress bar and title list of gpu
  web/containers/Layout/BottomBar/SystemMonitor/index.tsx
Labels: type: bug

#2178 fix: change button import model on hub page
  web/screens/ExploreModels/index.tsx
Labels: type: bug, type: enhancement

#2174 docs: add Jan newsletter
  docs/docs/community/community.mdx
  docs/src/containers/Footer/index.js
Labels: type: documentation

#2179 docs: update wall of love
  docs/docs/wall-of-love.md
Labels: type: documentation

#2180 docs: update docker command
  docs/docs/guides/02-installation/05-docker.md
Labels: type: bug, type: documentation

#2183 chore: bump nitro 0.3.14
  extensions/inference-nitro-extension/bin/version.txt
Labels: type: chore

#2187 docs: Update 01-integrate-continue.mdx
  docs/docs/guides/07-integrations/01-integrate-continue.mdx
Labels: type: documentation

#2189 docs: adding new feature for v0.4.7 to release checklist
  docs/docs/template/QA_script.md
Labels: type: documentation

#2186 docs: Update 08-antivirus-compatibility-testing.md
  docs/docs/guides/02-installation/08-antivirus-compatibility-testing.md
Labels: type: documentation

#2198 fix: minor ui missing secondary background
  uikit/src/main.scss
Labels: type: bug

#2199 fix: download model error does not reset state in model hub
  core/src/node/api/processors/download.ts
Labels: type: bug
