Repository menloresearch/jan, pull requests merged in 2024-10, with the labels that each got.

#3744 chore: improve models and threads caching
  web/containers/Layout/RibbonPanel/index.tsx
  web/containers/ModelDropdown/index.tsx
  web/helpers/atoms/BottomPanel.atom.ts
  web/helpers/atoms/Extension.atom.test.ts
  web/helpers/atoms/Model.atom.test.ts
  web/helpers/atoms/Model.atom.ts
  web/helpers/atoms/SystemBar.atom.test.ts
  web/helpers/atoms/Thread.atom.test.ts
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useAssistant.test.ts
  web/hooks/useClipboard.test.ts
  web/hooks/useDeleteModel.test.ts
  web/hooks/useDeleteThread.test.ts
  web/hooks/useDownloadModel.test.ts
  web/hooks/useDropModelBinaries.test.ts
  web/hooks/useFactoryReset.test.ts
  web/hooks/useGetHFRepoData.test.ts
  web/hooks/useGetSystemResources.test.ts
  web/hooks/useGpuSetting.test.ts
  web/hooks/useImportModel.test.ts
  web/hooks/useLoadTheme.test.ts
  web/hooks/useLogs.test.ts
  web/hooks/useModels.test.ts
  web/hooks/useModels.ts
  web/hooks/useSetActiveThread.ts
  web/hooks/useThread.test.ts
  web/hooks/useThreads.ts
  web/hooks/useUpdateModelParameters.ts
  web/types/model.d.ts
  web/utils/modelParam.ts
Labels: type: chore

#3750 chore: add llama3.2 and qwen2.5 models
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/command-r-34b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-2-27b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-2-2b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-2-9b/model.json
  extensions/inference-nitro-extension/resources/models/llama3.1-70b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/llama3.1-8b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/llama3.2-1b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/llama3.2-3b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/qwen2.5-14b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/qwen2.5-32b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/qwen2.5-72b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/qwen2.5-7b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/qwen2.5-coder-7b-instruct/model.json
  extensions/inference-nitro-extension/rollup.config.ts
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
Labels: type: chore

#3747 fix: Optimize resource watching
  web/containers/Layout/BottomPanel/SystemMonitor/SystemMonitor.test.tsx
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
Labels: type: bug

#3756 fix: overlap text on model selector and loader
  web/containers/Loader/ModelStart.tsx
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#3757 fix: overlap text on model selector and loader
  web/containers/Loader/ModelStart.tsx
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#3763 fix: error handling for model imports should be handled gracefully
  extensions/model-extension/src/index.test.ts
  extensions/model-extension/src/index.ts
  extensions/model-extension/src/node/index.ts
Labels: type: bug

#3795 fix: update base url edit page docs
  README.md
  docs/theme.config.tsx
Labels: type: bug

#3799 ci: Update jan-docs.yml
  .github/workflows/jan-docs.yml
Labels: type: ci

#3798 feat: save instruction for new threads as a stable feature
  web/hooks/useLoadTheme.ts
  web/package.json
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: feature request

#3765 test: added more test inside containers component
  web/containers/AutoLink/index.test.tsx
  web/containers/BlankState/index.test.tsx
  web/containers/Brand/Logo/Mark.test.tsx
  web/containers/CenterPanelContainer/index.test.tsx
  web/containers/CopyInstruction/index.test.tsx
  web/containers/EngineSetting/index.test.tsx
  web/containers/Loader/Bubble.tsx
  web/containers/Loader/ModelStart.test.tsx
  web/containers/LoadingModal/index.test.tsx
  web/containers/MainViewContainer/index.test.tsx
  web/containers/ModelConfigInput/index.test.tsx
  web/containers/Providers/Responsive.test.tsx
  web/containers/Providers/Theme.test.tsx
  web/containers/RightPanelContainer/index.test.tsx
  web/jest.config.js
Labels: category: tests

#3797 fix: reset window state after disconnected from multi monitor
  electron/utils/setup.ts
Labels: type: bug, category: app shell

#3816 fix: enable scroll modal component
  joi/src/core/Modal/styles.scss
Labels: type: bug

#3823 chore: sync main to dev 0.5.6
  web/containers/Loader/ModelStart.tsx
Labels: type: chore

#3833 fix: api playground text overlap button and search hub model
  joi/src/core/Tabs/styles.scss
  web/screens/Hub/index.tsx
  web/screens/LocalServer/LocalServerLeftPanel/index.tsx
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#3854 fix: context length input value isn't update
  web/containers/ModelSetting/SettingComponent.tsx
  web/containers/SliderRightPanel/index.tsx
Labels: type: bug

#3862 fix: inconsistent state of downloading multimodal
  extensions/model-extension/package.json
  extensions/model-extension/src/index.ts
Labels: type: bug

#3848 feat: support markdown on user message
  web/containers/ModelDropdown/index.tsx
  web/package.json
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: feature request

#3839 chore: replace windows codesign cert
  .github/workflows/template-build-windows-x64.yml
Labels: type: chore, type: ci

#3835 Feat Jan beta version
  .github/scripts/rename-app-beta.sh
  .github/scripts/rename-uninstaller-beta.sh
  .github/scripts/rename-workspace-beta.sh
  .github/workflows/jan-electron-build-beta.yml
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos-arm64.yml
  .github/workflows/template-build-macos-x64.yml
  .github/workflows/template-build-windows-x64.yml
Labels: type: ci

#3866 fix: hardware section
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#3870 ci: fix docusaurus
  .github/workflows/jan-docs.yml
Labels: type: ci

#3872 fix: hidden box dropdown hardware if no list
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#3873 fix: placeholder no hardware detect
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#3876 fix: reset prompt when send click button
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
Labels: type: bug

#3877 fix: docs trigger on release deploy to production
  .github/workflows/jan-docs-new-release.yaml
Labels: type: bug

#3878 chore: Readme add beta download url
  README.md
Labels: type: chore

#3887 fix: edge case tiny chat input box show randomly
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: bug

#3893 chore: remove deprecated warning from build project joi
  joi/rollup.config.mjs
Labels: type: chore

#3899 chore: update changelog web
  docs/public/assets/images/changelog/jan-v0.5.5.jpeg
  docs/public/assets/images/changelog/jan-v0.5.7.gif
  docs/src/pages/changelog/2024-02-10-jan-is-more-stable.mdx
  docs/src/pages/changelog/2024-10-24-jan-stable.mdx
Labels: type: chore

#3912 fix: deprecated gpt with vision
  extensions/inference-openai-extension/package.json
  extensions/inference-openai-extension/resources/models.json
Labels: type: bug

#3892 fix: handle edge cases syntax highlight
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
Labels: type: bug

#3921 fix: types issue (#internalTypeOnlyBrand) in the @types/node package
  core/tsconfig.json
  extensions/assistant-extension/tsconfig.json
  extensions/inference-nitro-extension/tsconfig.json
  extensions/tensorrt-llm-extension/tsconfig.json
Labels: type: bug
