Repository menloresearch/jan, pull requests merged in 2024-08, with the labels that each got.

#3225 fix: max token issue
  web/screens/Thread/ThreadRightPanel/ModelSettingContainer/index.tsx
  web/utils/componentSettings.ts
Labels: type: bug

#3224 fix: wait for cortex process overlay should be on top
  web/containers/WaitingCortexModal/index.tsx
  web/helpers/atoms/App.atom.ts
  web/hooks/useCortex.ts
  web/package.json
Labels: type: bug

#3232 fix: clean up port before start jan
  electron/download.bat
  electron/handlers/native.ts
  electron/main.ts
Labels: type: bug

#3221 fix: update new api from cortex to support 0.5.0
  core/src/types/file/index.ts
  electron/.eslintrc.js
  electron/download.bat
  electron/handlers/native.ts
  electron/main.ts
  electron/managers/window.ts
  electron/resources/version.txt
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
  web/containers/Layout/index.tsx
  web/containers/Providers/DownloadEventListener.tsx
  web/containers/Providers/EventListener.tsx
  web/containers/Providers/ModelEventListener.tsx
  web/containers/Providers/ModelImportListener.tsx
  web/containers/Providers/index.tsx
  web/containers/WaitingCortexModal/index.tsx
  web/helpers/atoms/App.atom.ts
  web/helpers/atoms/Model.atom.ts
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useCortex.ts
  web/hooks/useDownloadState.ts
  web/hooks/useDropModelBinaries.ts
  web/hooks/useEngineInit.ts
  web/hooks/useMigratingData.ts
  web/hooks/useModelStop.ts
  web/hooks/useModels.ts
  web/hooks/useSendMessage.ts
  web/package.json
  web/screens/HubScreen2/components/InferenceErrorModal.tsx
  web/screens/HubScreen2/components/ModelSearchBar.tsx
  web/screens/HubScreen2/components/SetUpApiKeyModal.tsx
  web/screens/HubScreen2/components/WarningMultipleModelModal.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/ChooseWhatToImportModal/index.tsx
  web/screens/Settings/EngineSetting/index.tsx
  web/screens/Settings/ImportModelOptionModal/index.tsx
  web/screens/Settings/ImportSuccessIcon/index.tsx
  web/screens/Settings/ImportingModelModal/ImportingModelItem.tsx
  web/screens/Settings/ImportingModelModal/index.tsx
  web/screens/Settings/MyModels/ModelItem/index.tsx
  web/screens/Settings/MyModels/index.tsx
  web/screens/Settings/SelectingModelModal/index.tsx
  web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/ChatActionButton/SendMessageButton.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/ChatActionButton/StopInferenceButton.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/ChatActionButton/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/ChatTextInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/MessageToolbar/index.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
  web/screens/Thread/ThreadRightPanel/ModelSettingContainer/index.tsx
  web/utils/componentSettings.ts
Labels: type: bug

#3220 feat: make scroll area type auto for make default visible scrollbar
  joi/src/core/ScrollArea/index.tsx
  joi/src/core/ScrollArea/styles.scss
Labels: type: feature request

#3233 fix: broken status parse due to empty category
  electron/resources/version.txt
  web/utils/model-engine.ts
Labels: type: bug

#3227 chore: update conditional starter screen after cortex load
  web/screens/Thread/index.tsx
Labels: type: chore

#3234 fix: normalize messages for some providers
  web/hooks/useSendMessage.ts
Labels: type: bug

#3235 chore: minor copy for grammar
  web/containers/Providers/ModalMigrations.tsx
Labels: type: chore

#3248 chore: check the legacy incompatible message type
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: chore

#3236 feat: add more options for cortex popup
  web/screens/HubScreen2/components/DownloadLocalModelModal.tsx
  web/screens/HubScreen2/components/HeaderModal.tsx
  web/screens/HubScreen2/components/ListModel.tsx
  web/screens/HubScreen2/components/SetUpRemoteModelModal.tsx
  web/screens/Settings/ImportingModelModal/ImportingModelItem.tsx
  web/screens/Settings/ImportingModelModal/index.tsx
Labels: type: feature request

#3261 fix: remote model added manually does not shown in model drop down
  electron/resources/version.txt
  web/hooks/useGetModelsByEngine.ts
  web/hooks/useModelHub.ts
  web/utils/thread.ts
Labels: type: bug

#3252 fix: set cortex data folder path when starting jan
  core/src/types/file/index.ts
  electron/handlers/native.ts
  electron/main.ts
  electron/resources/version.txt
  web/containers/Layout/BottomPanel/DownloadingStatus/index.tsx
  web/containers/Layout/index.tsx
  web/containers/Providers/ModalMigrations.tsx
  web/containers/Providers/index.tsx
  web/helpers/atoms/AppConfig.atom.ts
  web/hooks/useCortex.ts
  web/hooks/useMigratingData.ts
  web/screens/Settings/Advanced/FactoryReset/components/DataMigration.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/ImportingModelModal/index.tsx
Labels: type: bug

#3270 chore: temporary hidden button import model
  web/screens/HubScreen2/components/ModelSearchBar.tsx
Labels: type: enhancement, type: chore

#3273 chore: update hub search result
  web/screens/HubScreen2/components/HubScreenFilter/index.tsx
  web/screens/HubScreen2/components/RemoteModelGroup.tsx
Labels: type: enhancement, type: chore

#3272 chore: remove focus button
  joi/src/core/Button/styles.scss
Labels: type: enhancement

#3274 fix: should not let second instance terminate cortex
  electron/main.ts
Labels: type: bug

#3276 chore: toast message on model import fail with reason
  web/screens/Settings/ImportingModelModal/index.tsx
Labels: type: chore

#3266 feat: enable copy over instructions
  web/containers/Providers/KeyListener.tsx
  web/hooks/useThreads.ts
  web/package.json
  web/screens/Settings/Advanced/components/CopyOverInstruction.tsx
  web/screens/Settings/Advanced/components/DataMigration.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
Labels: type: feature request

#3277 fix: allow user to reinit engine from settings page
  web/screens/Settings/EngineSetting/index.tsx
Labels: type: bug

#3275 fix: clearer app loading prompt
  web/containers/WaitingCortexModal/index.tsx
Labels: type: bug

#3278 fix: migration wrong directory
  electron/handlers/native.ts
  electron/main.ts
  electron/utils/path.ts
  web/containers/Providers/ModalMigrations.tsx
  web/screens/Settings/Advanced/components/DataMigration.tsx
Labels: type: bug

#3279 feat: add nvidia engine
  core/src/types/model/modelEntity.ts
Labels: type: feature request

#3280 chore: update z-index tooltip
  joi/src/core/Tooltip/styles.scss
Labels: type: chore

#3281 chore": update minor UI
  electron/resources/version.txt
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
  web/screens/HubScreen2/components/BuiltInModelCard.tsx
  web/screens/HubScreen2/components/HfListModel.tsx
  web/screens/HubScreen2/components/HubModelCard.tsx
  web/screens/HubScreen2/components/HuggingFaceModelCard.tsx
  web/screens/HubScreen2/components/ListModel.tsx
  web/screens/HubScreen2/components/SliderItem.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelSegmentInfo/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/index.tsx
Labels: type: enhancement, type: chore

#3287 fix: system bar always show RAM usage 0%
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
  web/helpers/atoms/SystemBar.atom.ts
Labels: type: bug

#3290 feat: add chunk count
  electron/resources/version.txt
  web/helpers/atoms/ChatMessage.atom.ts
  web/hooks/useSendMessage.ts
  web/screens/Thread/ThreadCenterPanel/ChatInput/ChatActionButton/StopInferenceButton.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/components/TokenCount.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: feature request

#3283 fix: onnx can't be selected in download model modal
  web/screens/HubScreen2/components/ListModel.tsx
Labels: type: bug

#3293 fix: add lower case quantization support
  web/screens/HubScreen2/components/ModelSearchBar.tsx
  web/utils/huggingface.ts
Labels: type: bug

#3297 fix: failed download should not be added to download state
  core/src/types/model/index.ts
  core/src/types/model/modelInterface.ts
  web/hooks/useCortex.ts
  web/hooks/useHfModelFetchAndDownload.ts
  web/hooks/useModelDownloadMutation.ts
  web/screens/HubScreen2/components/BuiltInModelCard.tsx
  web/screens/HubScreen2/components/HfListModel.tsx
  web/screens/HubScreen2/components/ListModel.tsx
  web/screens/HubScreen2/components/SliderItem.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
  web/screens/Settings/ImportingModelModal/index.tsx
Labels: type: bug

#3294 fix: error while importing local model is not shown
  core/src/types/model/index.ts
  core/src/types/model/modelInterface.ts
  web/hooks/useCortex.ts
  web/hooks/useHfModelFetchAndDownload.ts
  web/hooks/useModelDownloadMutation.ts
  web/hooks/useSendMessage.ts
  web/screens/HubScreen2/components/BuiltInModelCard.tsx
  web/screens/HubScreen2/components/HfListModel.tsx
  web/screens/HubScreen2/components/ListModel.tsx
  web/screens/HubScreen2/components/SliderItem.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
  web/screens/Settings/ImportingModelModal/index.tsx
Labels: type: bug

#3295 fix: icon setting can close and open right panel
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: bug

#3291 fix: engine logo on model dropdown
  web/containers/ModelDropdown/ModelSection.tsx
Labels: type: bug

#3300 chore: update cortex new version
  electron/resources/version.txt
Labels: type: chore

#3299 fix: merge gpu arch and os tensorrt models
  web/utils/huggingface.ts
Labels: type: bug

#3298 fix: migration item in setting detail omit buttons
  web/containers/Layout/BottomPanel/DownloadingStatus/index.tsx
  web/screens/Settings/Advanced/components/DataMigration.tsx
Labels: type: bug

#3305 feat: embed cortex into jan as a JS module
  .github/workflows/jan-electron-linter-and-test.yml
  electron/cortex-runner.ts
  electron/main.ts
  electron/package.json
Labels: type: feature request

#3309 feat: change data folder
  core/src/types/api/index.ts
  core/src/types/config/appConfigEntity.ts
  electron/handlers/native.ts
  electron/main.ts
  electron/managers/tray.ts
  electron/managers/window.ts
  electron/preload.ts
  electron/utils/path.ts
  electron/utils/shortcut.ts
  web/app/search/layout.tsx
  web/screens/Settings/Advanced/DataFolder/index.tsx
  web/screens/Settings/Advanced/index.tsx
Labels: type: feature request

#3307 fix: avoid lose title threads
  web/constants/Threads.ts
  web/hooks/useCortex.ts
  web/hooks/useMigratingData.ts
  web/hooks/useSendMessage.ts
  web/screens/Thread/ThreadLeftPanel/ModalCleanThread/index.tsx
  web/screens/Thread/ThreadLeftPanel/ThreadItem/index.tsx
  web/screens/Thread/ThreadLeftPanel/TypingAnimated/index.tsx
Labels: type: bug

#3314 fix: refresh should not create new thread
  joi/src/core/TextArea/index.tsx
  web/containers/Providers/DataLoader.tsx
  web/containers/Providers/KeyListener.tsx
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useModelQuery.ts
  web/hooks/useThreadCreateMutation.ts
  web/hooks/useThreadQuery.ts
  web/hooks/useThreads.ts
  web/screens/HubScreen2/components/SliderItem.tsx
  web/screens/Settings/Advanced/components/CopyOverInstruction.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/ChatTextInput/index.tsx
  web/screens/Thread/ThreadLeftPanel/ModalDeleteThread/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
  web/screens/Thread/ThreadRightPanel/AssistantSettingContainer/components/CopyOverInstruction.tsx
  web/screens/Thread/ThreadRightPanel/AssistantSettingContainer/index.tsx
Labels: type: bug

#3306 feat: modal waiting cortex
  joi/src/core/Modal/index.tsx
  web/containers/Loader/Spinner.tsx
  web/containers/WaitingCortexModal/index.tsx
  web/helpers/atoms/AppConfig.atom.ts
Labels: type: feature request

#3316 fix: broken app due to incorrect api path
  web/containers/WaitingCortexModal/index.tsx
  web/helpers/atoms/AppConfig.atom.ts
Labels: type: bug

#3328 fix: update legacy path
  electron/utils/path.ts
Labels: type: bug

#3334 chore: disable quick ask
  electron/utils/path.ts
  web/helpers/atoms/AppConfig.atom.ts
Labels: type: chore

#3336 fix: broken jan build - add log trace (jan.log)
  electron/main.ts
  electron/package.json
  electron/utils/setup.ts
  web/hooks/useThreads.ts
Labels: type: bug

#3338 chore(ui): fix alignment loader starter screen
  web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyModel/OnDeviceListStarter.tsx
Labels: type: enhancement, type: chore

#3342 chore(UI): update experience model dropdown
  web/containers/CenterPanelContainer/index.tsx
  web/containers/ModelDropdown/ModelSection.tsx
  web/helpers/atoms/Model.atom.ts
  web/public/icons/llamacpp.svg
  web/screens/Thread/ThreadLeftPanel/ThreadItem/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
  web/utils/model-engine.ts
Labels: type: enhancement, type: feature request, type: chore

#3346 feat: move icon create new thread into top panel
  web/containers/Layout/TopPanel/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
Labels: type: feature request

#3347 chore: button outline for configure cloud model
  web/containers/ModelDropdown/ModelSection.tsx
Labels: type: enhancement, type: chore

#3350 chore: add back GPU information to system monitoring bar
  .github/ISSUE_TEMPLATE/bug_report.md
  core/src/types/events/resource.event.ts
  electron/package.json
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
  web/helpers/atoms/SystemBar.atom.ts
Labels: type: chore

#3351 fix: failed to relaunch app to update
  electron/main.ts
  electron/utils/clean.ts
  electron/utils/cortex.ts
  electron/utils/process.ts
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
Labels: type: bug

#3352 chore: minor ui improvement
  web/screens/HubScreen2/components/DetailModelGroup.tsx
  web/screens/HubScreen2/components/HubScreenFilter/index.tsx
  web/screens/HubScreen2/components/HuggingFaceModelCard.tsx
  web/screens/Settings/Advanced/components/DataMigration.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/EngineSetting/index.tsx
  web/screens/Settings/Hotkeys/index.tsx
  web/screens/Settings/MyModels/ModelItem/index.tsx
  web/screens/Settings/MyModels/index.tsx
  web/screens/Thread/ThreadRightPanel/AssistantSettingContainer/components/CopyOverInstruction.tsx
  web/screens/Thread/ThreadRightPanel/AssistantSettingContainer/index.tsx
Labels: type: enhancement, type: chore

#3353 fix: LaTex formula render issue
  web/app/layout.tsx
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: bug

#3363 chore: add engine logo from local instead of metadata logo
  web/containers/ModelDropdown/ModelSection.tsx
  web/public/icons/anthropic.svg
  web/public/icons/cohere.svg
  web/public/icons/dot.svg
  web/public/icons/groq.svg
  web/public/icons/martian.svg
  web/public/icons/mistral.svg
  web/public/icons/nvidia.svg
  web/public/icons/openRouter.svg
  web/public/icons/openai.svg
  web/public/icons/send.svg
  web/screens/HubScreen2/components/RemoteModelGroup.tsx
  web/screens/Settings/MyModels/ModelGroup/index.tsx
  web/utils/model-engine.ts
Labels: type: chore

#3383 chore: cherry pick latest fixes
  .github/workflows/jan-server-build-nightly.yml
  .github/workflows/jan-server-build.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos-arm64.yml
  .github/workflows/template-build-macos-x64.yml
  .github/workflows/template-build-windows-x64.yml
  Dockerfile
  Dockerfile.gpu
  charts/server/Chart.lock
  charts/server/Chart.yaml
  charts/server/charts/common-0.1.2.tgz
  charts/server/config.json
  charts/server/values.yaml
  docker-compose-dev.yml
  docker-compose.yml
  joi/src/core/ScrollArea/index.tsx
  joi/src/core/ScrollArea/styles.scss
  joi/src/core/Tooltip/styles.scss
  web/app/layout.tsx
Labels: type: chore

#3391 fix: Jan should have access to it resource folders
  .gitignore
  core/src/node/api/processors/app.ts
  core/src/node/api/processors/extension.ts
  core/src/node/helper/config.ts
  core/src/node/helper/path.ts
  electron/utils/migration.ts
  web/app/layout.tsx
  web/styles/main.scss
Labels: type: bug

#3386 chore: update model dropdown and my model with collapsible chevron
  core/src/types/model/modelEntity.ts
  web/containers/ModelDropdown/index.tsx
  web/containers/SetupRemoteModel/index.tsx
  web/helpers/atoms/Model.atom.ts
  web/hooks/useLoadTheme.ts
  web/public/images/ModelProvider/anthropic.svg
  web/public/images/ModelProvider/cohere.svg
  web/public/images/ModelProvider/cortex.svg
  web/public/images/ModelProvider/dot.svg
  web/public/images/ModelProvider/google.svg
  web/public/images/ModelProvider/groq.svg
  web/public/images/ModelProvider/hugging-face.svg
  web/public/images/ModelProvider/martian.svg
  web/public/images/ModelProvider/meta.svg
  web/public/images/ModelProvider/mistral.svg
  web/public/images/ModelProvider/nitro.svg
  web/public/images/ModelProvider/nvidia.svg
  web/public/images/ModelProvider/openRouter.svg
  web/public/images/ModelProvider/openai.svg
  web/public/images/ModelProvider/send.svg
  web/screens/Settings/MyModels/MyModelList/index.tsx
  web/screens/Settings/MyModels/index.tsx
  web/utils/modelEngine.ts
Labels: type: chore

#3381 chore: move create new thread to top panel
  web/containers/CenterPanelContainer/index.tsx
  web/containers/Layout/TopPanel/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
Labels: type: chore

#3388 feat: small ui improvement
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/Hotkeys/index.tsx
Labels: type: feature request, type: chore

#3382 chore: improve readability with set max width container message
  web/screens/Thread/ThreadCenterPanel/SimpleTextMessage/index.tsx
Labels: type: chore

#3389 feat: add model assistant tab
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: chore

#3393 fix: app emits ugly errors when retrieving settings
  core/src/browser/extension.ts
  web/containers/ListContainer/index.tsx
  web/hooks/useRecommendedModel.ts
Labels: type: bug

#3395 chore: clean up console modal component
  joi/src/core/Modal/index.tsx
Labels: type: chore

#3401 feat: enable copy instruction
  web/containers/CopyInstruction/index.tsx
  web/hooks/useCreateNewThread.ts
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: feature request

#3411 chore: remove model selection in assistant tab model
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: chore, roadmap: Jan Hub

#3415 fix: disable remote model when user did not setup apiKey
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#3420 chore: fix CI - remove headless ui
  web/package.json
Labels: type: chore

#3412 fix: avoid show remote model on system monitor
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
Labels: type: bug

#3414 chore: small ui improvement
  web/containers/ModelDropdown/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
Labels: type: chore

#3413 feat: add blank state component for hub and my model search
  web/containers/BlankState/index.tsx
  web/screens/Hub/index.tsx
  web/screens/Settings/MyModels/index.tsx
Labels: type: feature request

#3402 fix: save state toggle input box setting
  web/containers/ModelDropdown/index.tsx
  web/helpers/atoms/Thread.atom.ts
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: bug

#3422 feat: openrouter model settings
  core/src/browser/extension.ts
  extensions/inference-openrouter-extension/resources/settings.json
  extensions/inference-openrouter-extension/src/index.ts
Labels: type: feature request

#3419 feat: cortex extension pulls hf model list
  core/src/types/model/modelEntity.ts
  electron/package.json
  extensions/inference-cortex-extension/helpers/huggingface.js
  extensions/inference-cortex-extension/package.json
  extensions/inference-cortex-extension/rollup.config.ts
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-cortex-extension/src/node/index.ts
  extensions/model-extension/package.json
  extensions/model-extension/src/helpers/params.ts
  extensions/model-extension/src/index.ts
  extensions/tensorrt-llm-extension/src/node/index.ts
  joi/package.json
  package.json
  web/containers/ModelDropdown/index.tsx
  web/containers/ModelLabel/index.tsx
  web/package.json
  web/screens/Hub/ModelList/ModelHeader/index.tsx
  web/screens/Hub/ModelList/ModelItem/index.tsx
  web/screens/Hub/ModelList/index.tsx
  web/utils/componentSettings.ts
Labels: type: feature request

#3421 feat: import model with gguf metadata extraction
  extensions/model-extension/download.bat
  extensions/model-extension/package.json
  extensions/model-extension/rollup.config.ts
  extensions/model-extension/scripts/convert-hf-to-gguf.py
  extensions/model-extension/scripts/convert.py
  extensions/model-extension/scripts/gguf-py/LICENSE
  extensions/model-extension/scripts/gguf-py/README.md
  extensions/model-extension/scripts/gguf-py/examples/writer.py
  extensions/model-extension/scripts/gguf-py/gguf/__init__.py
  extensions/model-extension/scripts/gguf-py/gguf/constants.py
  extensions/model-extension/scripts/gguf-py/gguf/gguf.py
  extensions/model-extension/scripts/gguf-py/gguf/gguf_reader.py
  extensions/model-extension/scripts/gguf-py/gguf/gguf_writer.py
  extensions/model-extension/scripts/gguf-py/gguf/py.typed
  extensions/model-extension/scripts/gguf-py/gguf/tensor_mapping.py
  extensions/model-extension/scripts/gguf-py/gguf/vocab.py
  extensions/model-extension/scripts/gguf-py/pyproject.toml
  extensions/model-extension/scripts/gguf-py/scripts/__init__.py
  extensions/model-extension/scripts/gguf-py/scripts/gguf-convert-endian.py
  extensions/model-extension/scripts/gguf-py/scripts/gguf-dump.py
  extensions/model-extension/scripts/gguf-py/scripts/gguf-set-metadata.py
  extensions/model-extension/scripts/gguf-py/tests/test_gguf.py
  extensions/model-extension/scripts/install_deps.py
  extensions/model-extension/scripts/version.txt
  extensions/model-extension/src/index.ts
  extensions/model-extension/src/node/index.ts
Labels: type: feature request

#3426 refactor: marked helper - model description as markdown
  web/screens/Hub/ModelList/ModelItem/index.tsx
  web/screens/Settings/CoreExtensions/ExtensionItem.tsx
  web/screens/Settings/CoreExtensions/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailToggleItem/index.tsx
  web/utils/marked.ts
Labels: type: chore

#3428 chore: disable internal REST endpoints due to a vulnerability issue
  core/src/node/api/restful/v1.ts
Labels: type: chore

#3433 fix: add toaster warning when blocked create new thread
  web/hooks/useCreateNewThread.ts
Labels: type: bug

#3432 fix: decreased scrollbar width
  joi/src/core/ScrollArea/styles.scss
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#3431 fix: missing font katex
  web/package.json
  web/postcss.config.js
  web/styles/main.scss
  web/styles/vendor/katex-fonts.scss
  web/styles/vendor/katex-fonts/KaTeX_AMS-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Caligraphic-Bold.woff2
  web/styles/vendor/katex-fonts/KaTeX_Caligraphic-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Fraktur-Bold.woff2
  web/styles/vendor/katex-fonts/KaTeX_Fraktur-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Main-Bold.woff2
  web/styles/vendor/katex-fonts/KaTeX_Main-BoldItalic.woff2
  web/styles/vendor/katex-fonts/KaTeX_Main-Italic.woff2
  web/styles/vendor/katex-fonts/KaTeX_Main-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Math-BoldItalic.woff2
  web/styles/vendor/katex-fonts/KaTeX_Math-Italic.woff2
  web/styles/vendor/katex-fonts/KaTeX_SansSerif-Bold.woff2
  web/styles/vendor/katex-fonts/KaTeX_SansSerif-Italic.woff2
  web/styles/vendor/katex-fonts/KaTeX_SansSerif-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Script-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Size1-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Size2-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Size3-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Size4-Regular.woff2
  web/styles/vendor/katex-fonts/KaTeX_Typewriter-Regular.woff2
  web/styles/vendor/katex.scss
Labels: type: bug

#3429 fix: setting chatbox input
  web/containers/Layout/TopPanel/index.tsx
  web/helpers/atoms/ThreadRightPanel.atom.ts
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: bug

#3436 fix: date format for chat item
  web/utils/datetime.ts
Labels: type: bug

#3435 fix: preserve model settings should maintain all settings
  extensions/model-extension/src/index.ts
  web/containers/ModelDropdown/index.tsx
  web/hooks/useCreateNewThread.ts
  web/hooks/useRecommendedModel.ts
  web/hooks/useUpdateModelParameters.ts
Labels: type: bug

#3430 fix: setting extension placeholder and input action apikey
  core/src/browser/extension.ts
  extensions/inference-anthropic-extension/resources/settings.json
  extensions/inference-cohere-extension/resources/settings.json
  extensions/inference-groq-extension/resources/settings.json
  extensions/inference-martian-extension/resources/settings.json
  extensions/inference-mistral-extension/resources/settings.json
  extensions/inference-nvidia-extension/resources/settings.json
  extensions/inference-openai-extension/resources/settings.json
  extensions/inference-openrouter-extension/resources/settings.json
  extensions/inference-triton-trtllm-extension/resources/settings.json
Labels: type: bug

#3439 fix: unable to import model due to missing metadata
  extensions/model-extension/src/index.ts
Labels: type: bug

#3441 chore: add back OpenRouter request endpoint setting
  extensions/inference-openrouter-extension/resources/settings.json
Labels: type: chore

#3442 fix: enable extensions migration
  electron/utils/migration.ts
  web/hooks/useUpdateModelParameters.ts
Labels: type: bug

#3425 feat: add checklist regression test
  specs/Makefile
  specs/QA-checklist.md
  specs/README.md
  specs/adrs/adr-001-jan-deployable-cloud-native.md
  specs/adrs/adr-002-jan-ai-apps.md
  specs/adrs/adr-003-jan-plugins.md
  specs/adrs/adr-004-UI-Service.md
  specs/adrs/adr-005-model-installation.md
  specs/adrs/adr-006-jan-core-module.md
  specs/adrs/adr-007-jan-plugin-catalog.md
  specs/adrs/adr-008-Extensible-Jan-with-Docker.md
  specs/images/adr-001-01.png
  specs/images/adr-001-02.png
  specs/images/adr-002-01.png
  specs/images/adr-002-02.png
  specs/images/adr-003-01.png
  specs/images/jan-core-module.png
  specs/images/jan-plugin-catalog.png
  specs/images/jan-ui-framework.png
  specs/jan-001-log-framework.md
  specs/spec-template.md
Labels: type: feature request

#3443 chore: change jan default data folder path to app's userData
  core/src/node/api/processors/fsExt.ts
  core/src/node/helper/config.ts
  web/app/search/layout.tsx
  web/containers/Providers/DataLoader.tsx
  web/hooks/useFactoryReset.ts
Labels: type: chore

#3449 fix: responsive modal import model
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadList/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/index.tsx
Labels: P1: important, type: bug

#3450 fix: modal title should not truncated
  joi/src/core/Modal/styles.scss
Labels: type: bug

#3458 chore: add husky pre-commit
  .husky/pre-commit
  package.json
Labels: type: chore

#3457 fix: add a minimum height for the main window otherwise it shrinks
  electron/managers/mainWindowConfig.ts
Labels: type: bug

#3456 fix: correct time-weighted retrieval toggle
  web/app/search/layout.tsx
  web/containers/Providers/DataLoader.tsx
  web/screens/Thread/ThreadRightPanel/Tools/index.tsx
Labels: type: bug

#3463 fix: import model by folder on win
  core/src/browser/fs.ts
  core/src/node/api/processors/fsExt.ts
  core/src/types/api/index.ts
  web/hooks/useImportModel.ts
Labels: type: bug

#3465 fix: search input clearable component
  joi/src/core/Input/index.tsx
  joi/src/core/Input/styles.scss
  web/containers/ModelSearch/index.tsx
  web/screens/Settings/CoreExtensions/index.tsx
Labels: type: bug, type: feature request

#3469 chore: move remote models to bottom of the models hub
  web/screens/Hub/ModelList/index.tsx
Labels: type: chore

#3470 fix: resize left and panel when scroll area show
  web/containers/LeftPanelContainer/index.tsx
  web/containers/RightPanelContainer/index.tsx
Labels: type: bug

#3467 fix: modal responsive import model
  electron/managers/mainWindowConfig.ts
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadList/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelSegmentInfo/index.tsx
Labels: type: bug

#3468 chore: add llama 3.1 8B gguf model
  extensions/inference-nitro-extension/package.json
  extensions/inference-nitro-extension/resources/models/gemma-1.1-2b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-1.1-7b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-2-27b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-2-2b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-2-9b/model.json
  extensions/inference-nitro-extension/resources/models/llama3-8b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/llama3.1-70b-instruct/model.json
  extensions/inference-nitro-extension/resources/models/llama3.1-8b-instruct/model.json
  extensions/inference-nitro-extension/rollup.config.ts
Labels: type: chore

#3474 fix: wrong classname icon
  web/containers/ModelDropdown/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
Labels: type: bug

#3482 fix: add engine in payload for nitro chat completion api
  core/src/node/api/restful/helper/builder.ts
  web/hooks/useImportModel.ts
Labels: type: bug

#3479 chore: Update model.json with correct filename
  extensions/inference-nitro-extension/resources/models/gemma-1.1-2b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-1.1-7b/model.json
Labels: type: chore

#3484 fix: responsive modal import gguf
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadList/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelSegmentInfo/index.tsx
  web/utils/modelEngine.ts
Labels: type: bug

#3477 feat: track last state left and right panel
  web/containers/Providers/Responsive.tsx
Labels: type: feature request

#3493 chore: Sync main to dev 0.5.3
  core/src/node/api/restful/helper/builder.ts
  extensions/inference-nitro-extension/resources/models/gemma-1.1-2b/model.json
  extensions/inference-nitro-extension/resources/models/gemma-1.1-7b/model.json
  web/.eslintrc.js
  web/containers/Layout/BottomPanel/SystemMonitor/index.tsx
  web/containers/ModelDropdown/index.tsx
  web/hooks/useImportModel.ts
  web/jest.config.js
  web/package.json
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadList/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelSegmentInfo/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
  web/testRunner.js
  web/tsconfig.json
  web/utils/memory.test.ts
  web/utils/memory.ts
  web/utils/modelEngine.ts
Labels: type: chore
