Repository menloresearch/jan, pull requests merged in 2024-12, with the labels that each got.

#4168 fix: Glitch theme applies on launch
  web/helpers/atoms/Setting.atom.ts
  web/hooks/useLoadTheme.test.ts
  web/hooks/useLoadTheme.ts
Labels: type: bug

#4167 fix: smooth the loader animation
  web/containers/Loader/GenerateResponse.test.tsx
  web/containers/Loader/GenerateResponse.tsx
  web/containers/Loader/ModelStart.tsx
Labels: type: bug

#4166 fix: high performance large convo rendering
  web/package.json
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatItem/index.tsx
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
Labels: type: bug

#4177 fix: 4171 - Model loading gets stuck on stop
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/resources/default_settings.json
  extensions/inference-cortex-extension/rollup.config.ts
  extensions/inference-cortex-extension/src/@types/global.d.ts
  extensions/inference-cortex-extension/src/index.ts
  web/containers/ErrorMessage/index.tsx
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
Labels: type: bug

#4183 chore: bump version 0.5.10
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/package.json
  web/package.json
Labels: type: chore

#4185 chore: correct scrollview thumb style
  joi/src/core/ScrollArea/styles.scss
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
Labels: type: chore

#4191 fix: scrollbar issue css
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
Labels: type: bug

#4190 chore: update the docs for the new Cortex server port
  docs/src/pages/docs/error-codes.mdx
  docs/src/pages/docs/troubleshooting.mdx
Labels: type: chore

#4196 fix: 4178 - current generated message options should be visible
  web/containers/ErrorMessage/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatItem/index.tsx
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
Labels: type: bug

#4199 fix: 4165 - Refactor message builder to avoid sending empty messages
  web/hooks/useSendChatMessage.ts
  web/utils/messageRequestBuilder.ts
Labels: type: bug

#4200 fix: 4162 - Graceful Openrouter error handling
  core/src/browser/extensions/engines/OAIEngine.ts
  core/src/browser/extensions/engines/helpers/sse.ts
Labels: type: bug

#4201 fix: 4155 - Queue up health check on server restarting
  extensions/inference-cortex-extension/src/index.ts
Labels: type: bug

#4213 fix: 4209 - Inconsistent max tokens value persistence
  web/containers/ModelDropdown/index.tsx
  web/hooks/useCreateNewThread.ts
Labels: type: bug

#4212 fix: 4208 - Empty title with special characters
  web/containers/Providers/ModelHandler.tsx
Labels: type: bug

#4214 chore: add NGL settings for vision models
  extensions/inference-cortex-extension/package.json
  extensions/inference-cortex-extension/resources/models/bakllava-1/model.json
  extensions/inference-cortex-extension/resources/models/llava-13b/model.json
  extensions/inference-cortex-extension/resources/models/llava-7b/model.json
Labels: type: chore

#4197 feat: macos universal
  .github/workflows/jan-electron-build-beta.yml
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build.yml
  .github/workflows/template-build-macos-arm64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-noti-discord-and-update-url-readme.yml
  Makefile
  electron/package.json
  extensions/assistant-extension/package.json
Labels: type: feature request

#4216 fix: react-markdown crash on code highlighting - threads switching do not take effect sometime
  web/package.json
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
Labels: type: bug

#4223 fix: syntax highlight configurations that made everything dark
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
Labels: type: bug

#4224 chore: bump web version 0.5.11
  web/package.json
Labels: type: chore

#4232 chore: update download url for macos universal
  README.md
Labels: type: chore

#4233 chore: fix beta ci
  .github/workflows/jan-electron-build-beta.yml
Labels: type: chore

#4227 chore: roadmap template fix
  .github/ISSUE_TEMPLATE/roadmap.md
Labels: type: chore

#4231 fix: list style off screen
  web/styles/components/message.scss
Labels: type: bug

#4226 fix: hide Vulkan option for users who don't have GPU
  web/containers/Providers/Jotai.tsx
  web/screens/Settings/Advanced/index.tsx
  web/types/file.d.ts
  web/utils/messageRequestBuilder.ts
  web/utils/threadMessageBuilder.ts
Labels: type: bug

#4234 enhancement: default open Jan Input Box Settings and Right panel
  web/containers/Providers/Responsive.tsx
  web/helpers/atoms/App.atom.ts
  web/helpers/atoms/Thread.atom.ts
Labels: type: enhancement

#4241 feat: add auto build when PR is approved
  .github/workflows/jan-electron-build-nightly.yml
Labels: type: feature request

#4240 fix: performance issue when pasting long content into the chat input box
  web/containers/CenterPanelContainer/index.tsx
  web/containers/Layout/index.tsx
  web/containers/LeftPanelContainer/index.tsx
  web/containers/MainViewContainer/index.tsx
  web/containers/RightPanelContainer/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: bug

#4248 fix: crash markdown render code block without triple backtick
  web/package.json
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
Labels: type: bug

#4252 enhancement: better error handing for remote models when there's no internet connection
  web/containers/ErrorMessage/index.tsx
Labels: type: enhancement

#4256 fix: auto scrolling to bottom
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
Labels: type: bug

#4265 chore: 4244 - deprecate groq llama 3.1 70B Versatile
  extensions/inference-groq-extension/resources/models.json
Labels: type: chore

#4259 chore: add ci janhq/core publish npm
  .github/workflows/publish-npm-core.yml
Labels: type: chore

#4269 fix: markdown inline inputbox
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
Labels: type: bug

#4266 fix: 4238 - fix default max_tokens set on remote models
  extensions/inference-openai-extension/resources/models.json
  web/containers/ModelDropdown/index.tsx
  web/hooks/useCreateNewThread.ts
  web/utils/modelEngine.ts
Labels: type: bug

#4270 feat: add cicd for janhq/joi
  .github/workflows/publish-npm-joi.yml
  joi/package.json
Labels: type: feature request

#4277 fix: disabled start model from mymodel list when server is running
  web/screens/Settings/MyModels/MyModelList/index.tsx
Labels: type: bug

#4276 enhancement: move token speed to bottom
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
Labels: type: enhancement

#4262 feat: product analytic UI
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-build-windows-x64.yml
  electron/tests/e2e/thread.e2e.spec.ts
  web/containers/Layout/BottomPanel/index.tsx
  web/containers/Layout/index.tsx
  web/containers/LeftPanelContainer/index.tsx
  web/containers/RightPanelContainer/index.tsx
  web/helpers/atoms/Setting.atom.ts
  web/next.config.js
  web/package.json
  web/screens/Settings/Advanced/index.test.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/Privacy/index.test.tsx
  web/screens/Settings/Privacy/index.tsx
  web/screens/Settings/SettingDetail/index.tsx
  web/screens/Settings/index.tsx
  web/types/index.d.ts
Labels: type: feature request

#4279 fix: starter screen layout
  web/containers/CenterPanelContainer/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/screens/Thread/index.tsx
Labels: type: bug

#4278 feat: add chat width setting option for thread
  web/containers/Layout/TopPanel/index.tsx
  web/helpers/atoms/Setting.atom.ts
  web/public/images/compact-width.png
  web/public/images/full-width.png
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/SettingDetail/index.tsx
  web/screens/Settings/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
Labels: type: feature request

#4282 fix: attachment preview issue
  core/src/browser/extensions/engines/OAIEngine.ts
  core/src/node/api/restful/helper/builder.ts
  core/src/types/message/messageEntity.ts
  web/hooks/usePath.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/DocMessage.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/ImageMessage.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/RelativeImage.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
  web/utils/datetime.test.ts
  web/utils/datetime.ts
  web/utils/file.ts
  web/utils/threadMessageBuilder.test.ts
  web/utils/threadMessageBuilder.ts
Labels: type: bug

#4280 feat: handle case thread when original model deleted
  web/containers/ModelDropdown/index.tsx
  web/hooks/useCreateNewThread.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/utils/model.ts
Labels: type: feature request

#4293 chore: bump cortex 1.0.5 rc2
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4290 fix: empty tooltip on attachment icon, also fix z-index
  web/screens/Hub/ModelList/ModelHeader/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: bug

#4294 fix: context length is reset while creating a new thread
  web/hooks/useCreateNewThread.ts
Labels: type: bug

#4284 enhancement: update thumbnail chat width option setting
  web/public/images/compact-width-dark.png
  web/public/images/compact-width.png
  web/public/images/full-width-dark.png
  web/public/images/full-width.png
  web/screens/Settings/Appearance/index.tsx
Labels: type: enhancement

#4289 fix: scroll to bottom issue
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
Labels: type: bug

#4295 fix: new thread isn't automatically created on factory reset
  core/src/browser/extensions/engines/OAIEngine.ts
  extensions/assistant-extension/src/index.ts
  web/containers/Providers/ModelHandler.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
  web/screens/Thread/ThreadLeftPanel/index.tsx
  web/utils/datetime.test.ts
  web/utils/datetime.ts
  web/utils/messageRequestBuilder.ts
  web/utils/threadMessageBuilder.ts
Labels: type: bug

#4296 enhancement: set recommend model to undefined if no model available
  web/hooks/useCreateNewThread.ts
  web/hooks/useRecommendedModel.ts
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: enhancement

#4297 chore: deprecate Jan core's REST module - all API requests go to cortex.cpp
  core/src/node/api/HttpServer.ts
  core/src/node/api/index.test.ts
  core/src/node/api/index.ts
  core/src/node/api/processors/app.test.ts
  core/src/node/api/processors/app.ts
  core/src/node/api/restful/app/download.test.ts
  core/src/node/api/restful/app/download.ts
  core/src/node/api/restful/app/handlers.test.ts
  core/src/node/api/restful/app/handlers.ts
  core/src/node/api/restful/common.test.ts
  core/src/node/api/restful/common.ts
  core/src/node/api/restful/helper/builder.test.ts
  core/src/node/api/restful/helper/builder.ts
  core/src/node/api/restful/helper/configuration.test.ts
  core/src/node/api/restful/helper/configuration.ts
  core/src/node/api/restful/helper/consts.test.ts
  core/src/node/api/restful/helper/consts.ts
  core/src/node/api/restful/v1.test.ts
  core/src/node/api/restful/v1.ts
  core/src/node/helper/path.ts
  core/tsconfig.json
  docs/openapi/.gitkeep
  docs/openapi/jan.json
  docs/openapi/jan.yaml
  docs/openapi/specs/assistants.yaml
  docs/openapi/specs/chat.yaml
  docs/openapi/specs/messages.yaml
  docs/openapi/specs/models.yaml
  docs/openapi/specs/threads.yaml
  docs/openapi/version.txt
  electron/docs/openapi/.gitkeep
  electron/package.json
  extensions/conversational-extension/src/index.ts
  package.json
  server/cortex.json
  server/index.ts
  server/main.ts
  server/middleware/s3.ts
  server/package.json
  server/tsconfig.json
  web/hooks/useActiveModel.ts
Labels: type: chore

#4300 fix: conditional render model setting based on selected model
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: bug

#4301 fix: escape heading on user message item
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
Labels: type: bug

#4307 fix: thread error handling
  web/containers/Providers/ModelHandler.tsx
  web/hooks/useDeleteThread.ts
Labels: type: bug

#4304 fix: fetch threads and messages without limiting
  extensions/conversational-extension/src/index.ts
  extensions/inference-cortex-extension/bin/version.txt
  extensions/model-extension/src/cortex.ts
  web/containers/Providers/ModelHandler.tsx
  web/hooks/useCreateNewThread.ts
  web/hooks/useThreads.ts
  web/package.json
Labels: type: bug

#4308 fix: scroll bottom issue
  web/containers/ModelDropdown/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyThread/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
Labels: type: bug

#4310 fix: overlap bottom system monitor
  web/screens/LocalServer/LocalServerLeftPanel/index.tsx
Labels: type: bug

#4315 fix: dynamic input box width and remove tooltip image option
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
Labels: type: bug

#4316 fix: cleaning a thread should just clear out messages
  extensions/conversational-extension/src/index.ts
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useDeleteThread.test.ts
  web/hooks/useDeleteThread.ts
Labels: type: bug

#4317 fix: change theme settings do not work after relocated data folder
  web/helpers/atoms/Setting.atom.ts
  web/hooks/useLoadTheme.ts
  web/screens/Settings/Appearance/index.tsx
Labels: type: bug

#4319 fix: threads sorting order after updated
  web/helpers/atoms/Thread.atom.ts
Labels: type: bug

#4320 fix: update thread's title edge cases
  web/hooks/useCreateNewThread.ts
Labels: type: bug

#4321 fix: generating message is gone after switching to another thread
  web/helpers/atoms/ChatMessage.atom.ts
Labels: type: bug

#4322 fix: app picks model automatically edge cases
  web/containers/ModelDropdown/index.tsx
  web/hooks/useDeleteThread.ts
  web/screens/Thread/ThreadRightPanel/Tools/index.tsx
Labels: type: bug

#4323 fix: scroll bottom when generation text
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
Labels: type: bug

#4326 fix: disabled native resize textarea when textarea autogrowing
  joi/src/core/TextArea/index.tsx
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: bug

#4330 chore: bump cortex 1.0.6-rc
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4336 chore: bump latest cortex stable release version
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4341 fix: send message button state reset on stop
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useActiveModel.ts
  web/hooks/useDeleteThread.ts
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: bug

#4324 chore: upgrade to turbo v2 and reduce ci quality gate runtime
  .github/workflows/jan-electron-linter-and-test.yml
  .github/workflows/publish-npm-core.yml
  .github/workflows/publish-npm-joi.yml
  .gitignore
  .yarnrc.yml
  Makefile
  core/package.json
  core/rollup.config.ts
  core/src/node/api/processors/app.test.ts
  core/tsconfig.json
  docs/package.json
  docs/yarn.lock
  electron/package.json
  electron/tests/config/fixtures.ts
  extensions/.yarnrc.yml
  extensions/assistant-extension/package.json
  extensions/conversational-extension/package.json
  extensions/inference-anthropic-extension/package.json
  extensions/inference-cohere-extension/package.json
  extensions/inference-cortex-extension/package.json
  extensions/inference-groq-extension/package.json
  extensions/inference-martian-extension/package.json
  extensions/inference-mistral-extension/package.json
  extensions/inference-nvidia-extension/package.json
  extensions/inference-openai-extension/package.json
  extensions/inference-openrouter-extension/package.json
  extensions/inference-triton-trtllm-extension/package.json
  extensions/model-extension/package.json
  extensions/monitoring-extension/package.json
  extensions/package.json
  extensions/tensorrt-llm-extension/package.json
  extensions/turbo.json
  extensions/yarn.lock
  joi/package.json
  joi/rollup.config.mjs
  joi/tsconfig.json
  package.json
  server/package.json
  turbo.json
  web/containers/CopyInstruction/index.test.tsx
  web/containers/CopyInstruction/index.tsx
  web/containers/Layout/BottomPanel/SystemMonitor/SystemMonitor.test.tsx
  web/helpers/atoms/App.atom.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useDeleteThread.test.ts
  web/jest.config.js
  web/package.json
  yarn.lock
Labels: type: chore

#4348 fix: regenerate scroll bottom
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
Labels: type: bug

#4350 chore: Refactor thread state management
  web/containers/Providers/ModelHandler.tsx
  web/helpers/atoms/Thread.atom.ts
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/MessageToolbar/index.tsx
Labels: type: chore

#4354 chore: don't stop inference and hide the stop button when creating a new thread
  web/hooks/useCreateNewThread.ts
Labels: type: chore

#4355 chore: bump cortex 1.0.7 RC
  extensions/inference-cortex-extension/bin/version.txt
  web/hooks/useCreateNewThread.test.ts
Labels: type: chore

#4356 fix: button state reset on switching models
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useActiveModel.ts
  web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.tsx
Labels: type: bug

#4357 chore: bump cortex latest version 1.0.7
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4334 feat: local engine management
  .github/workflows/jan-electron-linter-and-test.yml
  core/src/browser/extension.ts
  core/src/browser/extensions/enginesManagement.ts
  core/src/browser/extensions/index.ts
  core/src/types/engine/index.ts
  core/src/types/index.ts
  extensions/engine-management-extension/jest.config.js
  extensions/engine-management-extension/package.json
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/engine-management-extension/src/@types/global.d.ts
  extensions/engine-management-extension/src/error.ts
  extensions/engine-management-extension/src/index.ts
  extensions/engine-management-extension/src/node/cpuInfo.ts
  extensions/engine-management-extension/src/node/index.test.ts
  extensions/engine-management-extension/src/node/index.ts
  extensions/engine-management-extension/tsconfig.json
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/package.json
  extensions/inference-cortex-extension/src/@types/global.d.ts
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-cortex-extension/src/node/index.test.ts
  extensions/inference-cortex-extension/src/node/index.ts
  extensions/model-extension/package.json
  extensions/yarn.lock
  web/containers/Providers/EventListener.tsx
  web/helpers/atoms/Extension.atom.ts
  web/hooks/useDownloadState.ts
  web/hooks/useEngineManagement.ts
  web/package.json
  web/screens/Settings/CoreExtensions/index.tsx
  web/screens/Settings/Engines/DeleteEngineVariant.tsx
  web/screens/Settings/Engines/Settings.tsx
  web/screens/Settings/Engines/index.tsx
  web/screens/Settings/SettingDetail/index.tsx
  web/screens/Settings/SettingLeftPanel/SettingItem/index.tsx
  web/screens/Settings/SettingLeftPanel/index.tsx
  web/screens/Settings/index.tsx
  yarn.lock
Labels: type: feature request

#4360 chore: sync latest main into dev
  extensions/inference-cortex-extension/bin/version.txt
  web/containers/Providers/ModelHandler.tsx
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useActiveModel.ts
  web/hooks/useCreateNewThread.test.ts
  web/hooks/useCreateNewThread.ts
  web/hooks/useDeleteThread.ts
  web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/MessageToolbar/index.tsx
Labels: type: chore

#4359 enhancement: update ui delete engine with modal confirmation
  extensions/yarn.lock
  web/screens/Settings/Engines/Settings.tsx
Labels: type: enhancement

#4370 chore: improve development dev-ex with auto extensions migration
  Makefile
  electron/package.json
  extensions/yarn.lock
  package.json
Labels: type: chore

#4371 chore: deprecate make build-joi
  .github/workflows/jan-electron-linter-and-test.yml
Labels: type: chore

#4373 chore: refactor core and server packages
  .gitignore
  core/package.json
  core/rolldown.config.mjs
  core/rollup.config.ts
  core/src/browser/core.ts
  core/src/node/api/processors/app.ts
  core/src/node/extension/extension.ts
  core/src/types/api/index.ts
  core/tsconfig.json
  electron/handlers/native.ts
  electron/package.json
  extensions/yarn.lock
  server/main.ts
  server/package.json
  server/rolldown.config.mjs
  server/tsconfig.json
  yarn.lock
Labels: type: chore
