Repository menloresearch/jan, pull requests merged in 2025-03, with the labels that each got.

#4764 feat: add openai 4.5 preview and anthropic claude 3.7 sonnet models
  extensions/engine-management-extension/models/anthropic.json
  extensions/engine-management-extension/models/openai.json
Labels: type: feature request

#4763 fix: correct jan discord channel
  web/containers/ModalTroubleShoot/index.tsx
Labels: type: bug

#4768 fix: image upload button does not work - refresh models list persist current selected engine
  web/hooks/useEngineManagement.ts
  web/screens/Hub/ModelPage/RemoteModelRefresh.tsx
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Hub/index.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
Labels: type: bug

#4773 fix: list space styled and hidden message toolbar when editmode
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
  web/styles/components/marked.scss
Labels: type: bug

#4769 refactor: clean up deprecated components and events
  core/rolldown.config.mjs
  core/src/browser/core.test.ts
  core/src/browser/core.ts
  core/src/browser/extension.test.ts
  core/src/browser/extension.ts
  core/src/browser/fs.ts
  core/src/node/api/common/adapter.ts
  core/src/node/api/processors/download.test.ts
  core/src/node/api/processors/download.ts
  core/src/node/helper/download.test.ts
  core/src/node/helper/download.ts
  core/src/node/helper/index.ts
  core/src/types/api/index.ts
  core/src/types/file/index.ts
  core/src/types/miscellaneous/fileDownloadRequest.ts
  core/src/types/miscellaneous/index.ts
  core/src/types/miscellaneous/networkConfig.ts
  core/src/types/thread/index.ts
  core/src/types/thread/threadEvent.test.ts
  core/src/types/thread/threadEvent.ts
  electron/package.json
  extensions/model-extension/src/index.ts
  extensions/model-extension/src/legacy/download.ts
  web/containers/Layout/BottomPanel/InstallingExtension/InstallingExtensionModal.tsx
  web/containers/Layout/BottomPanel/InstallingExtension/index.tsx
  web/containers/Layout/BottomPanel/index.tsx
  web/containers/Layout/index.tsx
  web/containers/Providers/EventListener.tsx
  web/containers/Providers/ModelImportListener.tsx
  web/helpers/atoms/Extension.atom.test.ts
  web/helpers/atoms/Extension.atom.ts
  web/hooks/useImportModel.ts
  web/screens/Settings/CoreExtensions/ExtensionItem.tsx
  web/screens/Settings/CoreExtensions/index.tsx
  web/screens/Settings/ExtensionSetting/index.tsx
Labels: type: chore

#4774 fix: quickask ui color and alignment on mymodel list
  web/app/search/layout.tsx
  web/screens/Settings/MyModels/MyModelList/index.tsx
Labels: type: bug

#4775 chore: bump cortex version to fix model sources issue
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4778 chore: sync initial hub models
  extensions/engine-management-extension/package.json
  extensions/engine-management-extension/resources/openai.json
  extensions/model-extension/resources/default.json
Labels: type: chore

#4777 refactor: clean up legacy vision model settings
  extensions/inference-cortex-extension/src/index.ts
  extensions/model-extension/src/index.ts
Labels: type: chore

#4788 analytics: integrate posthog into Jan web
  docs/.env.example
  docs/next.config.mjs
  docs/package.json
  docs/public/sitemap-0.xml
  docs/src/components/FooterMenu/index.tsx
  docs/src/pages/_app.mdx
  docs/yarn.lock
Labels: type: feature request

#4787 fix: engine version update - cortex version bump - update tests
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/engine-management-extension/src/index.ts
  extensions/hardware-management-extension/src/index.ts
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/jest.config.js
  extensions/inference-cortex-extension/package.json
  extensions/inference-cortex-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-cortex-extension/src/node/index.test.ts
  extensions/inference-cortex-extension/src/node/index.ts
  web/screens/Settings/Engines/LocalEngineSettings.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
Labels: type: bug

#4789 fix: anthropic response template correction
  core/src/browser/extensions/engines/EngineManager.test.ts
  extensions/engine-management-extension/package.json
  extensions/engine-management-extension/resources/anthropic.json
  extensions/engine-management-extension/src/index.ts
  extensions/inference-cortex-extension/src/index.test.ts
Labels: type: bug

#4790 fix: image preview overlap toolbar message
  web/screens/Thread/ThreadCenterPanel/TextMessage/ImageMessage.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
Labels: type: bug

#4791 fix: cohere response template correction for proper markdown parsing
  core/src/browser/extensions/conversational.test.ts
  core/src/browser/extensions/enginesManagement.test.ts
  core/src/browser/extensions/hardwareManagement.test.ts
  core/src/browser/extensions/model.test.ts
  extensions/engine-management-extension/package.json
  extensions/engine-management-extension/resources/cohere.json
Labels: type: bug

#4792 fix: Hub UI issue render readme
  extensions/yarn.lock
  web/package.json
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Hub/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
  web/styles/components/code-block.scss
  web/styles/components/marked.scss
  yarn.lock
Labels: type: bug

#4793 chore: bump cortex version
  extensions/engine-management-extension/src/api.test.ts
  extensions/engine-management-extension/src/error.test.ts
  extensions/engine-management-extension/src/index.test.ts
  extensions/engine-management-extension/src/populateRemoteModels.test.ts
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4794 fix: app image - could not load model
  extensions/engine-management-extension/src/node/index.ts
Labels: type: bug

#4796 fix: hub model list desc render
  web/screens/Hub/ModelList/ModelItem/index.tsx
  web/utils/modelSource.ts
Labels: type: bug

#4797 fix: table markdown
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownUtils.tsx
  web/styles/components/marked.scss
Labels: type: bug

#4795 enhancement: add checkmark selected model
  web/containers/ModelDropdown/index.tsx
Labels: type: enhancement

#4798 chore: do not symlink engine on linux
  extensions/engine-management-extension/src/node/index.ts
Labels: type: chore

#4800 fix: update career url
  docs/src/components/FooterMenu/index.tsx
  docs/src/pages/about/team.mdx
  docs/src/pages/docs/index.mdx
Labels: type: bug

#4802 chore: correct cohere response template
  extensions/engine-management-extension/resources/cohere.json
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rolldown.config.mjs
Labels: type: chore

#4805 fix: minor ui issue
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Settings/Appearance/index.tsx
  web/styles/components/marked.scss
Labels: type: bug

#4806 fix: clear logs should not delete the folder
  extensions/inference-cortex-extension/bin/version.txt
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Settings/Privacy/index.tsx
Labels: type: bug

#4819 feat: Cortex API Authorization
  .github/workflows/nightly-integrate-cortex-cpp.yml
  .github/workflows/template-get-update-version.yml
  extensions/assistant-extension/rolldown.config.mjs
  extensions/assistant-extension/src/@types/global.d.ts
  extensions/assistant-extension/src/node/retrieval.ts
  extensions/conversational-extension/rolldown.config.mjs
  extensions/conversational-extension/src/@types/global.d.ts
  extensions/conversational-extension/src/index.ts
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/engine-management-extension/src/@types/global.d.ts
  extensions/engine-management-extension/src/index.ts
  extensions/hardware-management-extension/package.json
  extensions/hardware-management-extension/rolldown.config.mjs
  extensions/hardware-management-extension/src/@types/global.d.ts
  extensions/hardware-management-extension/src/index.ts
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/src/@types/global.d.ts
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-cortex-extension/src/node/index.ts
  extensions/model-extension/rolldown.config.mjs
  extensions/model-extension/src/@types/global.d.ts
  extensions/model-extension/src/index.ts
  server/cortex.json
  server/global.d.ts
  server/index.ts
  server/rolldown.config.mjs
  web/hooks/useGetLatestRelease.ts
Labels: type: feature request

#4820 feat: rotate api token for each run
  core/src/types/api/index.ts
  electron/handlers/native.ts
  electron/main.ts
  extensions/assistant-extension/rolldown.config.mjs
  extensions/assistant-extension/src/@types/global.d.ts
  extensions/assistant-extension/src/node/retrieval.ts
  extensions/conversational-extension/rolldown.config.mjs
  extensions/conversational-extension/src/@types/global.d.ts
  extensions/conversational-extension/src/index.ts
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/engine-management-extension/src/@types/global.d.ts
  extensions/engine-management-extension/src/index.ts
  extensions/hardware-management-extension/rolldown.config.mjs
  extensions/hardware-management-extension/src/@types/global.d.ts
  extensions/hardware-management-extension/src/index.ts
  extensions/inference-cortex-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/src/@types/global.d.ts
  extensions/inference-cortex-extension/src/index.ts
  extensions/inference-cortex-extension/src/node/index.ts
  extensions/model-extension/rolldown.config.mjs
  extensions/model-extension/src/@types/global.d.ts
  extensions/model-extension/src/index.ts
  server/global.d.ts
  server/index.ts
  server/rolldown.config.mjs
  web/hooks/useGetLatestRelease.ts
Labels: type: feature request

#4821 chore: should get hardware information on launch
  web/containers/Providers/DataLoader.tsx
Labels: type: chore

#4822 chore: should have an option to not revalidate hardware information
  extensions/hardware-management-extension/src/index.ts
  extensions/model-extension/src/index.ts
  web/containers/Providers/DataLoader.tsx
  web/hooks/useHardwareManagement.ts
Labels: type: chore

#4825 chore: cortex.cpp gpu activation could cause a race condition
  extensions/conversational-extension/src/index.ts
  extensions/engine-management-extension/src/index.ts
  extensions/hardware-management-extension/src/index.ts
  extensions/inference-cortex-extension/src/index.ts
  extensions/model-extension/src/index.ts
  web/screens/Settings/Hardware/index.tsx
Labels: type: chore

#4828 fix: jan beta logo displayed in jan release
  .github/workflows/jan-electron-build.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-build-windows-x64.yml
  electron/icons_dev/jan-beta-512x512.png
  electron/icons_dev/jan-beta-tray.png
  electron/icons_dev/jan-beta-tray@2x.png
  electron/icons_dev/jan-beta.ico
  electron/icons_dev/jan-beta.png
  electron/icons_dev/jan-nightly-512x512.png
  electron/icons_dev/jan-nightly-tray.png
  electron/icons_dev/jan-nightly-tray@2x.png
  electron/icons_dev/jan-nightly.ico
  electron/icons_dev/jan-nightly.png
Labels: type: bug

#4827 fix: jan logo beta displayed in jan release
  .github/workflows/jan-electron-build.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-build-windows-x64.yml
  electron/icons_dev/jan-beta-512x512.png
  electron/icons_dev/jan-beta-tray.png
  electron/icons_dev/jan-beta-tray@2x.png
  electron/icons_dev/jan-beta.ico
  electron/icons_dev/jan-beta.png
  electron/icons_dev/jan-nightly-512x512.png
  electron/icons_dev/jan-nightly-tray.png
  electron/icons_dev/jan-nightly-tray@2x.png
  electron/icons_dev/jan-nightly.ico
  electron/icons_dev/jan-nightly.png
Labels: type: bug, type: ci, os: linux

#4838 chore: remove attribute Homebrew
  docs/public/assets/images/general/menlo.svg
  docs/src/components/FooterMenu/index.tsx
  docs/src/pages/about/index.mdx
  docs/src/pages/privacy.mdx
  docs/yarn.lock
Labels: type: chore

#4859 feat: Jan - MCP Client Host
  src-tauri/Cargo.toml
  src-tauri/src/core/cmd.rs
  src-tauri/src/core/fs.rs
  src-tauri/src/core/mcp.rs
  src-tauri/src/core/mod.rs
  src-tauri/src/core/server.rs
  src-tauri/src/core/setup.rs
  src-tauri/src/core/state.rs
  src-tauri/src/lib.rs
  web/containers/Providers/CoreConfigurator.tsx
  web/services/tauriService.ts
Labels: type: feature request
