Repository menloresearch/jan, pull requests merged in 2025-04, with the labels that each got.

#4851 chore: update jan doc v0.5.16
  docs/src/pages/docs/_assets/llama.cpp-01.png
  docs/src/pages/docs/_assets/model-management-04.png
  docs/src/pages/docs/_assets/settings-19.png
  docs/src/pages/docs/_assets/trouble-shooting-01.png
  docs/src/pages/docs/data-folder.mdx
  docs/src/pages/docs/desktop/windows.mdx
  docs/src/pages/docs/privacy.mdx
  docs/src/pages/docs/settings.mdx
  docs/src/pages/docs/troubleshooting.mdx
Labels: type: chore

#4860 feat: Jan Tool Use - MCP frontend implementation
  core/src/browser/extensions/engines/AIEngine.ts
  core/src/browser/extensions/engines/OAIEngine.ts
  core/src/browser/index.ts
  core/src/browser/tools/index.test.ts
  core/src/browser/tools/index.ts
  core/src/browser/tools/manager.ts
  core/src/browser/tools/tool.test.ts
  core/src/browser/tools/tool.ts
  core/src/types/message/messageEntity.ts
  extensions/assistant-extension/package.json
  extensions/assistant-extension/rolldown.config.mjs
  extensions/assistant-extension/src/index.ts
  extensions/assistant-extension/src/node/index.ts
  extensions/assistant-extension/src/node/retrieval.ts
  extensions/assistant-extension/src/tools/retrieval.ts
  package.json
  src-tauri/Cargo.toml
  src-tauri/capabilities/default.json
  src-tauri/src/core/cmd.rs
  src-tauri/src/core/fs.rs
  src-tauri/src/core/mcp.rs
  src-tauri/src/core/mod.rs
  src-tauri/src/core/server.rs
  src-tauri/src/core/setup.rs
  src-tauri/src/core/state.rs
  src-tauri/src/lib.rs
  src-tauri/tauri.conf.json
  web/containers/ModalAppUpdaterChangelog/index.tsx
  web/hooks/useLoadTheme.ts
  web/hooks/useSendChatMessage.ts
  web/package.json
  web/services/coreService.ts
  web/types/model.d.ts
  web/utils/messageRequestBuilder.ts
Labels: type: feature request

#4856 chore: remove workflow automation
  docs/src/pages/integrations/_meta.json
  docs/src/pages/integrations/index.mdx
Labels: type: chore

#4877 chore: allow draggable window app
  src-tauri/capabilities/default.json
  src-tauri/tauri.conf.json
  web/containers/Layout/TopPanel/index.tsx
Labels: type: chore

#4887 chore: enable window effect blur
  src-tauri/tauri.conf.json
Labels: type: chore

#4903 fix: added border for search textfield
  web/containers/ModelSearch/index.tsx
Labels: type: bug

#4900 feat: jan UI with Tool use UX
  core/src/types/inference/inferenceEntity.ts
  core/src/types/message/messageEntity.ts
  web/containers/Providers/ModelHandler.tsx
  web/helpers/atoms/ChatMessage.atom.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Hub/ModelFilter/ModelSize/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/ToolCallBlock.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
  web/utils/messageRequestBuilder.ts
Labels: type: feature request

#4913 feat: MCP settings UI
  src-tauri/src/core/cmd.rs
  src-tauri/src/lib.rs
  web/package.json
  web/screens/Settings/MCP/configuration.tsx
  web/screens/Settings/MCP/index.tsx
  web/screens/Settings/MCP/search.tsx
  web/screens/Settings/SettingDetail/index.tsx
  web/screens/Settings/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
  web/services/tauriService.ts
Labels: type: feature request

#4919 fix: clean up threads persistence and fix assistant update issue
  src-tauri/src/core/threads.rs
  web/containers/ModelDropdown/index.tsx
  web/hooks/useCreateNewThread.ts
  web/hooks/useUpdateModelParameters.ts
Labels: type: bug

#4921 chore: update llama.cpp repo url in readme
  README.md
Labels: type: chore

#4922 fix: thread title does not set on remote models
  web/containers/Providers/ModelHandler.tsx
  web/hooks/useCreateNewThread.ts
  web/hooks/useDeleteThread.ts
Labels: type: bug

#4928 fix: prevent curly quotes from MCP config
  web/screens/Settings/MCP/configuration.tsx
Labels: type: bug

#4930 Enhanced the wording on the overview and the quickstart pages.
  docs/bun.lock
  docs/src/pages/docs/index.mdx
  docs/src/pages/docs/quickstart.mdx
Labels: type: docs

#4931 feat: permission dialog for tool call requests
  web/containers/ToolCallApprovalModal/index.tsx
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/EditChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/MessageToolbar/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
Labels: type: feature request

#4938 feat: allow users to enable and disable tools
  web/containers/ToolCallApprovalModal/index.tsx
  web/helpers/atoms/Thread.atom.ts
  web/hooks/useSendChatMessage.ts
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
Labels: type: feature request

#4916 chore: add windows download script
  package.json
  src-tauri/.gitignore
  src-tauri/binaries/download.bat
  src-tauri/tauri.conf.json
Labels: type: chore

#4937 chore: fix jan about doc
  docs/src/pages/about/index.mdx
  docs/src/pages/about/team.mdx
Labels: type: chore
