Repository menloresearch/jan, pull requests merged in 2025-05, with the labels that each got.

#4958 chore: fix headers
  .github/workflows/jan-docs-new-release.yaml
  .github/workflows/jan-docs.yml
  docs/_headers
Labels: type: chore

#4963 chore: pull binaries windows, linux
  scripts/download-bin.js
  src-tauri/tauri.conf.json
Labels: type: chore

#4904 fix: Jan supports cortex with llama-server
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/engine-management-extension/src/node/index.ts
  extensions/engine-management-extension/src/utils.ts
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rolldown.config.mjs
  src-tauri/Cargo.toml
  src-tauri/binaries/download.bat
  src-tauri/binaries/download.sh
  src-tauri/src/lib.rs
  web/hooks/useSendChatMessage.ts
Labels: type: bug

#4949 feat: run mcp with bundled bun and uv
  .gitignore
  package.json
  scripts/download-bin.js
  src-tauri/Cargo.toml
  src-tauri/src/core/mcp.rs
  src-tauri/tauri.conf.json
Labels: type: feature request

#4975 feat: tauri cicd preview
  .github/workflows/jan-electron-build-beta.yml
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-electron-build.yml
  .github/workflows/template-electron-build-linux-x64.yml
  .github/workflows/template-electron-build-macos.yml
  .github/workflows/template-electron-build-windows-x64.yml
  .github/workflows/template-tauri-build-linux-x64-preview.yml
  .github/workflows/template-tauri-build-macos-preview.yml
  .github/workflows/template-tauri-build-windows-x64-preview.yml
Labels: type: feature request

#4983 fix: qwen3 - weird token output - reasoning content should not be in completion request
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rolldown.config.mjs
  web/utils/messageRequestBuilder.ts
Labels: type: bug

#4984 chore: my models search box css issue
  web/containers/ModelSearch/index.tsx
Labels: type: chore

#4986 fix: update remote models list
  extensions/engine-management-extension/models/cohere.json
  extensions/engine-management-extension/models/deepseek.json
  extensions/engine-management-extension/models/google_gemini.json
  extensions/engine-management-extension/models/groq.json
Labels: type: bug

#4987 fix: border for the search box in my models
  web/containers/ModelSearch/index.tsx
Labels: type: bug

#4989 fix: distinguish between hub and models search
  core/src/browser/extensions/model.ts
  extensions/model-extension/src/index.ts
  web/containers/ModelSearch/index.tsx
  web/hooks/useEngineManagement.ts
  web/screens/Hub/index.tsx
Labels: type: bug

#4985 fix: should not normalize user input content
  web/utils/messageRequestBuilder.ts
Labels: type: bug

#4990 fix: add execution permission for bun and uv
  scripts/download-bin.mjs
Labels: type: bug

#4994 fix: should not spawn many llama.cpp servers for the same model
  .github/workflows/jan-electron-linter-and-test.yml
  Makefile
  extensions/inference-cortex-extension/src/index.ts
  package.json
  web-app/package.json
  web-app/src/containers/ChatInput.tsx
  web-app/src/lib/extension.ts
  web-app/src/lib/model.spec.ts
Labels: type: bug

#4995 refactor: remove hardcoded provider names
  core/src/browser/extensions/engines/EngineManager.ts
  core/src/browser/extensions/enginesManagement.ts
  core/src/types/engine/index.ts
  core/src/types/model/modelEntity.ts
  extensions/engine-management-extension/src/index.ts
  extensions/inference-cortex-extension/src/index.ts
  extensions/model-extension/src/index.ts
  extensions/model-extension/src/legacy/model-json.ts
  web-app/src/services/providers.ts
  web-app/src/services/threads.ts
Labels: type: chore

#4933 feat: Download manager for llama.cpp extension
  extensions/download-extension/package.json
  extensions/download-extension/rolldown.config.mjs
  extensions/download-extension/settings.json
  extensions/download-extension/src/@types/global.d.ts
  extensions/download-extension/src/index.ts
  extensions/download-extension/tsconfig.json
  extensions/download-extension/vite.config.ts
  src-tauri/Cargo.toml
  src-tauri/src/core/mod.rs
  src-tauri/src/core/state.rs
  src-tauri/src/core/utils/download.rs
  src-tauri/src/core/utils/mod.rs
  src-tauri/src/lib.rs
Labels: type: feature request

#4997 chore: increase hight of drag area window
  web-app/src/containers/DropdownModelProvider.tsx
  web-app/src/containers/HeaderPage.tsx
  web-app/src/containers/LeftPanel.tsx
  web-app/src/routes/__root.tsx
  web-app/src/routes/hub.tsx
Labels: type: chore

#5005 chore: initial setup screen for remote provider
  package.json
  web-app/package.json
  web-app/src/components/ui/button.tsx
  web-app/src/containers/CustomeTooltipJoyRide.tsx
  web-app/src/containers/ProvidersMenu.tsx
  web-app/src/containers/SetupScreen.tsx
  web-app/src/containers/dynamicControllerSetting/InputControl.tsx
  web-app/src/containers/dynamicControllerSetting/index.tsx
  web-app/src/mock/data.ts
  web-app/src/routes/index.tsx
  web-app/src/routes/settings/providers/$providerName.tsx
Labels: type: chore

#5007 chore: update empty state thread list, search, and no model
  web-app/src/containers/LeftPanel.tsx
  web-app/src/routes/settings/providers/$providerName.tsx
  web-app/src/routes/threads/$threadId.tsx
Labels: type: chore

#5008 feat: new frontend with model download function
  web-app/src/containers/ChatInput.tsx
  web-app/src/containers/DownloadManegement.tsx
  web-app/src/hooks/useDownloadStore.ts
  web-app/src/lib/completion.ts
  web-app/src/lib/models.ts
  web-app/src/providers/ExtensionProvider.tsx
  web-app/src/routes/hub.tsx
  web-app/src/services/eventsService.ts
  web-app/src/services/mcp.ts
  web-app/src/services/models.ts
Labels: type: feature request

#5009 chore: handle chat functions
  web-app/src/containers/ChatInput.tsx
  web-app/src/containers/DownloadManegement.tsx
  web-app/src/containers/ThreadContent.tsx
  web-app/src/hooks/useAppState.ts
  web-app/src/hooks/useChat.ts
  web-app/src/hooks/useMessages.ts
Labels: type: chore

#5011 chore: update model handlers on the new frontend
  web-app/src/containers/DownloadManegement.tsx
  web-app/src/containers/dialogs/DeleteModel.tsx
  web-app/src/hooks/useLocalApiServer.ts
  web-app/src/hooks/useModelProvider.ts
  web-app/src/routes/settings/local-api-server.tsx
  web-app/src/routes/settings/providers/$providerName.tsx
  web-app/src/services/models.ts
  web-app/src/services/providers.ts
Labels: type: chore

#5013 chore: initial assistant feature
  web-app/package.json
  web-app/src/components/ui/dropdown-menu.tsx
  web-app/src/components/ui/textarea.tsx
  web-app/src/constants/localStorage.ts
  web-app/src/constants/routes.ts
  web-app/src/containers/ChatInput.tsx
  web-app/src/containers/DropdownAssistant.tsx
  web-app/src/containers/DropdownModelProvider.tsx
  web-app/src/containers/HeaderPage.tsx
  web-app/src/containers/LeftPanel.tsx
  web-app/src/containers/dialogs/AddEditAssistant.tsx
  web-app/src/hooks/useAssistant.ts
  web-app/src/routeTree.gen.ts
  web-app/src/routes/assistant.tsx
  web-app/src/routes/index.tsx
  web-app/src/routes/threads/$threadId.tsx
Labels: type: feature request, type: chore

#5014 chore: Pin rmcp commit
  src-tauri/Cargo.toml
  src-tauri/src/core/mcp.rs
Labels: type: chore

#5015 chore: allow users to enable/disable MCP servers
  extensions/conversational-extension/package.json
  extensions/hardware-management-extension/package.json
  extensions/model-extension/package.json
  src-tauri/src/core/mcp.rs
  web-app/src/hooks/useMCPServers.ts
  web-app/src/hooks/useProxyConfig.ts
  web-app/src/routes/settings/extensions.tsx
  web-app/src/routes/settings/https-proxy.tsx
  web-app/src/routes/settings/mcp-servers.tsx
  web-app/src/services/models.ts
  web-app/src/types/modelProviders.d.ts
Labels: type: chore

#5016 chore: improve switch component offset
  web-app/src/components/ui/switch.tsx
Labels: type: chore

#5017 chore: cleanup whitespace left panel on thread list
  web-app/src/containers/LeftPanel.tsx
Labels: type: chore

#5010 chore: add some ts-ignore to make tauri build works
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/jan-tauri-build-nightly.yml
  .github/workflows/template-tauri-build-linux-x64.yml
  .github/workflows/template-tauri-build-macos.yml
  .github/workflows/template-tauri-build-windows-x64.yml
  src-tauri/binaries/download.bat
  src-tauri/tauri.bundle.windows.nsis.template
  web-app/src/containers/DropdownAssistant.tsx
  web-app/src/containers/LanguageSwitcher.tsx
  web-app/src/containers/ModelSetting.tsx
  web-app/src/hooks/useGeneralSetting.ts
  web-app/src/lib/completion.ts
Labels: type: chore

#5019 chore: stream app logs to log window
  src-tauri/src/core/cmd.rs
  src-tauri/src/core/mcp.rs
  src-tauri/src/lib.rs
  web-app/src/hooks/useAppState.ts
  web-app/src/hooks/useLocalApiServer.ts
  web-app/src/lib/service.ts
  web-app/src/providers/ExtensionProvider.tsx
  web-app/src/routes/local-api-server/logs.tsx
  web-app/src/routes/settings/general.tsx
  web-app/src/routes/settings/local-api-server.tsx
  web-app/src/services/app.ts
  web-app/src/services/events.ts
Labels: type: chore

#5020 chore: add function delete and params type assistant
  web-app/src/components/ui/textarea.tsx
  web-app/src/containers/DropdownAssistant.tsx
  web-app/src/containers/dialogs/AddEditAssistant.tsx
  web-app/src/hooks/useAssistant.ts
  web-app/src/routes/assistant.tsx
Labels: type: chore

#5023 feat: handle stop streaming message, scroll to bottom and model loads
  extensions/inference-cortex-extension/src/index.ts
  web-app/src/containers/ChatInput.tsx
  web-app/src/containers/StreamingContent.tsx
  web-app/src/hooks/useAppState.ts
  web-app/src/hooks/useChat.ts
  web-app/src/lib/completion.ts
  web-app/src/routes/threads/$threadId.tsx
Labels: type: feature request

#5024 feat: Jan supports multiple assistants
  core/src/types/thread/threadEntity.ts
  src-tauri/src/core/threads.rs
  web-app/src/containers/DropdownAssistant.tsx
  web-app/src/hooks/useAssistant.ts
  web-app/src/hooks/useChat.ts
  web-app/src/hooks/useThreads.ts
  web-app/src/lib/messages.ts
  web-app/src/routes/index.tsx
  web-app/src/routes/threads/$threadId.tsx
  web-app/src/services/threads.ts
  web-app/src/types/threads.d.ts
Labels: type: feature request

#5022 chore: regroup codeblock setting appearance
  web-app/src/routes/settings/appearance.tsx
Labels: type: chore

#5021 chore: scroll to bottom when have new log message
  web-app/src/routes/local-api-server/logs.tsx
Labels: type: chore

#5026 chore: reduce state update to prevent glitchy scroll to bottom
  web-app/src/lib/model.spec.ts
  web-app/src/routes/threads/$threadId.tsx
Labels: type: chore

#5027 chore: remove electron nightly/manual
  .github/workflows/jan-electron-build-nightly.yml
  web-app/src/containers/dialogs/AddEditAssistant.tsx
Labels: type: chore

#5029 chore: add setting hardware
  web-app/src/constants/localStorage.ts
  web-app/src/constants/routes.ts
  web-app/src/containers/SettingsMenu.tsx
  web-app/src/hooks/useAppearance.ts
  web-app/src/hooks/useAssistant.ts
  web-app/src/hooks/useCodeblock.ts
  web-app/src/hooks/useGeneralSetting.ts
  web-app/src/hooks/useHardware.ts
  web-app/src/hooks/useLeftPanel.ts
  web-app/src/hooks/useLocalApiServer.ts
  web-app/src/hooks/useMCPServers.ts
  web-app/src/hooks/useMessages.ts
  web-app/src/hooks/useModelProvider.ts
  web-app/src/hooks/useProxyConfig.ts
  web-app/src/hooks/useTheme.ts
  web-app/src/hooks/useThreads.ts
  web-app/src/i18n.ts
  web-app/src/routeTree.gen.ts
  web-app/src/routes/settings/hardware.tsx
Labels: type: chore

#5032 chore: model loading and truncate dropdown assiatant title
  web-app/src/containers/ChatInput.tsx
  web-app/src/containers/DropdownAssistant.tsx
  web-app/src/containers/LeftPanel.tsx
  web-app/src/routes/assistant.tsx
  web-app/src/routes/threads/$threadId.tsx
Labels: type: chore

#5031 chore: token speed and edit message
  web-app/src/containers/ChatInput.tsx
  web-app/src/containers/ThreadContent.tsx
  web-app/src/hooks/useAppState.ts
  web-app/src/hooks/useChat.ts
  web-app/src/types/threads.d.ts
Labels: type: chore

#5033 feat: add custom OpenAI provider
  extensions/inference-cortex-extension/resources/default_settings.json
  extensions/inference-cortex-extension/src/index.ts
  web-app/src/containers/ProvidersMenu.tsx
  web-app/src/containers/dialogs/DeleteProvider.tsx
  web-app/src/hooks/useChat.ts
  web-app/src/hooks/useModelProvider.ts
  web-app/src/lib/utils.ts
  web-app/src/mock/data.ts
  web-app/src/routes/settings/providers/$providerName.tsx
  web-app/src/services/providers.ts
Labels: type: feature request

#5036 chore: fix auto focus chat input
  web-app/src/containers/ChatInput.tsx
Labels: type: chore

#5037 fix: windows installer and allowed origins
  src-tauri/src/core/setup.rs
  src-tauri/tauri.bundle.windows.nsis.template
Labels: type: bug

#5038 chore: model import from llama.cpp provider
  web-app/src/routes/settings/providers/$providerName.tsx
  web-app/src/services/models.ts
Labels: type: chore

#5041 chore: handle hardware settings
  web-app/package.json
  web-app/src/hooks/useHardware.ts
  web-app/src/routes/settings/general.tsx
  web-app/src/routes/settings/hardware.tsx
  web-app/src/services/hardware.ts
  web-app/src/types/global.d.ts
  web-app/vite.config.ts
Labels: type: chore

#5044 chore: add inline message chat input
  web-app/src/containers/ChatInput.tsx
Labels: type: chore

#5050 chore: enable / disable proxy configrations
  core/src/browser/extensions/engines/AIEngine.ts
  extensions/inference-cortex-extension/src/index.ts
  web-app/src/hooks/useChat.ts
  web-app/src/lib/completion.ts
  web-app/src/routes/settings/https-proxy.tsx
Labels: type: chore

#5056 chore: update Jan change logs v0.5.17
  docs/public/assets/images/changelog/jan-v0-5-17-gemm3-patch.gif
  docs/src/pages/changelog/2025-02-18-advanced-llama.cpp-settings.mdx
  docs/src/pages/changelog/2025-03-14-jan-security-patch.mdx
  docs/src/pages/changelog/2025-05-14-jan-qwen3-patch.mdx
Labels: type: chore

#5060 feat: initial app logs
  src-tauri/capabilities/log-app-window.json
  web-app/src/constants/routes.ts
  web-app/src/constants/windows.ts
  web-app/src/routeTree.gen.ts
  web-app/src/routes/__root.tsx
  web-app/src/routes/logs.tsx
  web-app/src/routes/settings/general.tsx
  web-app/src/routes/settings/hardware.tsx
  web-app/src/routes/settings/local-api-server.tsx
Labels: type: feature request

#5054 chore: app updater UI
  src-tauri/capabilities/default.json
  src-tauri/src/lib.rs
  web-app/package.json
  web-app/src/containers/DownloadManegement.tsx
  web-app/src/containers/LeftPanel.tsx
  web-app/src/containers/dialogs/AppUpdater.tsx
  web-app/src/hooks/useAppUpdater.ts
  web-app/src/hooks/useReleaseNotes.ts
  web-app/src/lib/utils.ts
  web-app/src/providers/DataProvider.tsx
  web-app/src/routes/__root.tsx
Labels: type: chore

#5051 fix: tauri updater
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/template-tauri-build-linux-x64.yml
  .github/workflows/template-tauri-build-macos.yml
  .github/workflows/template-tauri-build-windows-x64.yml
  src-tauri/Cargo.toml
  src-tauri/src/core/cmd.rs
  src-tauri/src/lib.rs
Labels: type: bug

#5048 chore: wildcard for connect-src
  src-tauri/tauri.conf.json
Labels: type: chore

#5066 fix: allow dialog triggered by tooltip
  web-app/src/containers/ThreadContent.tsx
Labels: type: bug

#5062 chore: add model information in System Monitoring
  extensions/inference-cortex-extension/src/index.ts
  src-tauri/src/core/cmd.rs
  web-app/src/lib/utils.ts
  web-app/src/routes/settings/https-proxy.tsx
  web-app/src/routes/system-monitor.tsx
  web-app/src/services/models.ts
  web-app/src/types/models.ts
Labels: type: chore

#5074 feat: Implement Cortex server auto-restart and webview notification
  src-tauri/src/core/cmd.rs
  src-tauri/src/core/setup.rs
  src-tauri/src/core/state.rs
  src-tauri/src/lib.rs
  web-app/src/containers/dialogs/CortexFailureDialog.tsx
  web-app/src/routes/__root.tsx
Labels: type: feature request

#5076 fix: close side windows should not kill background processes
  src-tauri/src/core/mcp.rs
  src-tauri/src/lib.rs
Labels: type: bug

#5079 fix: hidden date when value 0
  web-app/src/containers/ThreadContent.tsx
Labels: type: bug

#5080 fix: mcp info when long string without space
  web-app/src/routes/settings/mcp-servers.tsx
Labels: type: bug

#5077 chore: update font-src
  src-tauri/tauri.conf.json
Labels: type: chore

#5081 fix: provider activation status
  web-app/src/hooks/useModelProvider.ts
  web-app/src/services/threads.ts
Labels: type: bug

#5084 fix: `copy:lib` on macos when directory already exists
  package.json
Labels: type: bug

#5073 feat: improve download extension
  extensions/download-extension/src/index.ts
  src-tauri/src/core/utils/download.rs
  src-tauri/src/lib.rs
Labels: type: feature request

#5083 chore: providers should default on
  src-tauri/tauri.conf.json
  web-app/src/hooks/useModelProvider.ts
Labels: type: chore

#5086 chore: handle many issues with app settings and message actions
  web-app/src/containers/ThreadContent.tsx
  web-app/src/containers/dialogs/AddEditMCPServer.tsx
  web-app/src/hooks/useChat.ts
  web-app/src/hooks/useMCPServers.ts
  web-app/src/hooks/useModelProvider.ts
  web-app/src/providers/DataProvider.tsx
  web-app/src/routes/settings/hardware.tsx
  web-app/src/routes/settings/mcp-servers.tsx
  web-app/src/services/mcp.ts
Labels: type: chore

#5087 feat: Model import (download + local import) for llama.cpp extension
  core/src/browser/extensions/engines/AIEngine.ts
  extensions/llamacpp-extension/package.json
  extensions/llamacpp-extension/src/index.ts
  src-tauri/Cargo.toml
  src-tauri/src/core/cmd.rs
  src-tauri/src/core/utils/mod.rs
  src-tauri/src/lib.rs
Labels: type: feature request

#5093 fix: model import name issues
  web-app/src/hooks/useModelProvider.ts
  web-app/src/services/models.ts
Labels: type: bug

#5090 fix: text component scaling
  web-app/src/containers/ThreadContent.tsx
  web-app/src/containers/dialogs/EditJsonMCPserver.tsx
  web-app/src/index.css
Labels: type: bug

#5089 fix: broken ui download count when leftpanel close
  web-app/src/containers/DownloadManegement.tsx
Labels: type: bug

#5099 feat: product analytic
  web-app/package.json
  web-app/src/constants/localStorage.ts
  web-app/src/containers/analytics/PromptAnalytic.tsx
  web-app/src/hooks/useAnalytic.ts
  web-app/src/providers/AnalyticProvider.tsx
  web-app/src/routes/__root.tsx
  web-app/src/routes/settings/privacy.tsx
  web-app/src/services/analytic.ts
  web-app/src/types/global.d.ts
  web-app/vite.config.ts
Labels: type: feature request

#5098 feat: add couple section about us on general settings
  web-app/src/routes/settings/general.tsx
Labels: type: feature request

#5097 chore: translation
  web-app/src/containers/dialogs/AddEditAssistant.tsx
  web-app/src/locales/en/common.json
  web-app/src/locales/id/common.json
  web-app/src/locales/vn/common.json
Labels: type: chore

#5101 chore: remove model provider from setup screen
  web-app/src/containers/SetupScreen.tsx
Labels: type: chore

#5108 chore: add function to model settings
  web-app/src/containers/DropdownModelProvider.tsx
  web-app/src/containers/ModelSetting.tsx
  web-app/src/hooks/useChat.ts
  web-app/src/hooks/useModelProvider.ts
  web-app/src/lib/predefined.ts
Labels: type: chore

#5109 fix: prevent send message when empty message
  web-app/src/containers/ChatInput.tsx
Labels: type: bug

#5111 feat: Support download resume
  src-tauri/src/core/utils/download.rs
Labels: type: feature request

#5110 fix: overflow content codeblock
  web-app/src/containers/RenderMarkdown.tsx
  web-app/src/containers/ThinkingBlock.tsx
  web-app/src/containers/ThreadContent.tsx
  web-app/src/containers/ToolCallBlock.tsx
  web-app/src/routes/__root.tsx
  web-app/src/routes/threads/$threadId.tsx
Labels: type: bug

#5116 fix: chore UI issues
  src-tauri/src/lib.rs
  web-app/src/containers/ThinkingBlock.tsx
  web-app/src/mock/data.ts
  web-app/src/services/models.ts
Labels: type: bug

#5120 chore: bump llama.cpp to b5509
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rolldown.config.mjs
  src-tauri/binaries/download.bat
  src-tauri/binaries/download.sh
  web-app/src/containers/DropdownModelProvider.tsx
  web-app/src/hooks/useChat.ts
Labels: type: chore

#5127 chore: persist assistants settings
  core/src/browser/fs.ts
  extensions/assistant-extension/src/index.ts
  extensions/inference-cortex-extension/resources/default_settings.json
  src-tauri/src/core/cmd.rs
  src-tauri/src/core/fs.rs
  src-tauri/src/lib.rs
  web-app/src/hooks/useAssistant.ts
  web-app/src/providers/DataProvider.tsx
  web-app/src/services/assistants.ts
  web-app/src/services/models.ts
Labels: type: chore

#5125 chore: add skip button joyride
  web-app/src/containers/CustomeTooltipJoyRide.tsx
  web-app/src/containers/HeaderPage.tsx
  web-app/src/containers/SetupScreen.tsx
  web-app/src/routes/settings/providers/$providerName.tsx
Labels: type: chore

#5133 feat: start and stop model
  web-app/src/containers/AvatarEmoji.tsx
  web-app/src/containers/dialogs/AddEditAssistant.tsx
  web-app/src/hooks/useAppearance.ts
  web-app/src/hooks/useChat.ts
  web-app/src/lib/completion.ts
  web-app/src/routes/settings/providers/$providerName.tsx
  web-app/src/routes/system-monitor.tsx
  web-app/src/services/models.ts
Labels: type: feature request

#5134 chore: allow users to setting model offload
  extensions/inference-cortex-extension/resources/default_settings.json
  extensions/inference-cortex-extension/src/index.ts
  web-app/src/hooks/useChat.ts
  web-app/src/lib/completion.ts
  web-app/src/services/providers.ts
Labels: type: chore

#5138 chore: hide reveal password
  web-app/src/index.css
Labels: type: chore

#5136 feat: add refresh button list model remote provider
  web-app/src/routes/settings/providers/$providerName.tsx
  web-app/src/services/providers.ts
Labels: type: feature request

#5142 fix: content overflow when long text without space
  web-app/src/containers/RenderMarkdown.tsx
Labels: type: bug

#5141 fix: thread list state order after dragable
  web-app/src/containers/ThreadList.tsx
  web-app/src/hooks/useThreads.ts
  web-app/src/providers/DataProvider.tsx
  web-app/src/services/threads.ts
Labels: type: bug

#5144 fix: state model threadId
  web-app/src/routes/threads/$threadId.tsx
Labels: type: bug

#5148 fix: avoid floating content when render table markdown
  web-app/src/styles/markdown.css
Labels: type: bug

#5149 ci: deprecate electron build
  .github/workflows/jan-tauri-build-nightly.yaml
  .github/workflows/jan-tauri-build.yaml
  .github/workflows/template-tauri-build-linux-x64.yml
  .github/workflows/template-tauri-build-macos.yml
  .github/workflows/template-tauri-build-windows-x64.yml
Labels: type: ci

#5154 fix: extension settings are not retained in new sessions
  core/src/browser/extension.ts
  src-tauri/src/core/setup.rs
  web-app/src/containers/ProvidersMenu.tsx
Labels: type: bug
