Repository menloresearch/jan, pull requests merged in 2025-02, with the labels that each got.

#4551 chore: reasoning block
  extensions/yarn.lock
  web/containers/Providers/ModelHandler.tsx
  web/package.json
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/ThinkingBlock.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
  web/tailwind.config.js
  yarn.lock
Labels: type: chore

#4562 enhancement: update UI uploading files and images
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/FileUploadPreview/index.tsx
  web/screens/Thread/ThreadCenterPanel/ImageUploadPreview/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/DocMessage.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/RelativeImage.tsx
Labels: type: enhancement

#4564 fix: think content render as markdown
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/ThinkingBlock.tsx
Labels: type: bug, type: enhancement

#4567 fix: download progress import from hgf
  extensions/yarn.lock
  web/screens/Settings/HuggingFaceRepoDetailModal/ModelDownloadRow/index.tsx
Labels: type: bug

#4566 enhancement: code snippet colors should depend on native theme
  extensions/yarn.lock
  themes/dark-dimmed/theme.json
  themes/joi-dark/theme.json
  themes/joi-light/theme.json
  themes/night-blue/theme.json
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
  web/styles/components/code-block.scss
  web/styles/main.scss
  yarn.lock
Labels: type: enhancement

#4568 chore: correct conversational API request methods with latest cortex update
  extensions/conversational-extension/src/index.ts
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4572 fix: exclude yml into totaldownload start next version
  docs/src/utils/format.ts
  docs/yarn.lock
Labels: type: bug, type: enhancement

#4574 enhancement: adjust hub ui in different themes
  extensions/yarn.lock
  joi/src/core/Dropdown/styles.scss
  web/screens/Hub/ModelList/ModelHeader/index.tsx
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Hub/index.tsx
  web/styles/components/marked.scss
Labels: type: enhancement

#4578 enhancement: error ui in threads
  web/containers/ErrorMessage/index.tsx
  web/tailwind.config.js
Labels: type: enhancement

#4581 chore: delete custom engine
  web/screens/Settings/Engines/ModalDeleteCustomEngine.tsx
  web/screens/Settings/Engines/RemoteEngineItem.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
Labels: type: chore

#4580 chore: engine model adding ux refinement
  core/src/types/engine/index.ts
  extensions/engine-management-extension/resources/anthropic.json
  extensions/engine-management-extension/resources/cohere.json
  extensions/engine-management-extension/resources/groq.json
  extensions/engine-management-extension/resources/martian.json
  extensions/engine-management-extension/resources/mistral.json
  extensions/engine-management-extension/resources/nvidia.json
  extensions/engine-management-extension/resources/openai.json
  extensions/engine-management-extension/resources/openrouter.json
  extensions/engine-management-extension/src/index.ts
  web/containers/ModelDropdown/index.tsx
  web/package.json
  web/screens/Settings/Engines/ModalAddModel.tsx
Labels: type: chore

#4579 enhancement: toggle change cover hub banner style
  web/screens/Hub/index.tsx
Labels: type: enhancement

#4585 chore: calculate model label
  extensions/yarn.lock
  web/containers/ModelLabel/ModelLabel.test.tsx
  web/containers/ModelLabel/index.tsx
  yarn.lock
Labels: type: chore

#4584 chore: add default inference parameters for custom remote models
  extensions/engine-management-extension/src/index.ts
Labels: type: chore

#4586 chore:add deepseek r1 distill models to hub
  extensions/inference-cortex-extension/package.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-llama-70b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-llama-8b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-1.5b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-14b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-32b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-7b/model.json
  extensions/inference-cortex-extension/resources/models/llama3.1-8b-instruct/model.json
  extensions/inference-cortex-extension/rolldown.config.mjs
Labels: type: chore

#4527 chore: Updated copies in-app
  docs/src/pages/docs/configure-extensions.mdx
  docs/src/pages/docs/install-engines.mdx
  electron/package.json
  extensions/inference-cortex-extension/resources/default_settings.json
  web/screens/Settings/Advanced/FactoryReset/ModalConfirmReset.tsx
  web/screens/Settings/Advanced/FactoryReset/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/CoreExtensions/index.tsx
  web/screens/Settings/Engines/ModalAddRemoteEngine.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
Labels: type: chore

#4598 chore: bump cortex with conversation patch update
  extensions/conversational-extension/src/index.ts
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4599 chore: update style codeblock
  web/styles/components/code-block.scss
Labels: type: chore

#4604 fix: load model error component
  web/containers/ErrorMessage/index.tsx
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
Labels: type: bug

#4602 chore: update remote provider response transform template
  extensions/engine-management-extension/models/openrouter.json
  extensions/engine-management-extension/resources/deepseek.json
  extensions/engine-management-extension/resources/google_gemini.json
  extensions/engine-management-extension/resources/groq.json
  extensions/engine-management-extension/resources/martian.json
  extensions/engine-management-extension/resources/nvidia.json
  extensions/engine-management-extension/resources/openai.json
  extensions/engine-management-extension/resources/openrouter.json
  extensions/engine-management-extension/rolldown.config.mjs
Labels: type: chore

#4609 fix: remote engine model auto select
  extensions/yarn.lock
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
Labels: type: bug

#4611 chore: open URL from model detail page should open in an external browser
  web/screens/Hub/ModelList/ModelHeader/index.tsx
  web/screens/Hub/ModelList/ModelItem/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownUtils.tsx
Labels: type: chore

#4614 chore: add back app logging function
  electron/main.ts
  electron/utils/logger.ts
Labels: type: chore

#4615 fix: error handling - pull remote models list raise an error on fail
  extensions/engine-management-extension/src/index.ts
Labels: type: chore

#4616 fix: remove from list dropdown when deleted remote model
  extensions/yarn.lock
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#4618 fix: inconsistent models list on first launch
  extensions/engine-management-extension/src/index.ts
Labels: type: bug

#4617 fix: filter out fake gpu
  web/services/appService.ts
Labels: type: bug

#4622 chore: bump cortex to the latest version 1.0.10-rc1 to address hardware UI issues
  core/src/types/hardware/index.ts
  core/src/types/miscellaneous/systemResourceInfo.ts
  extensions/engine-management-extension/src/utils.ts
  extensions/inference-cortex-extension/bin/version.txt
  web/screens/Settings/Hardware/index.tsx
Labels: type: chore

#4623 chore: change cortex.cpp log level to info for easier log observation
  extensions/inference-cortex-extension/src/node/index.ts
Labels: type: chore

#4624 fix: remove toggle enable GPU from setting
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#4625 chore: add back env paths setting so cortex engine can load libraries properly
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/src/node/index.ts
Labels: type: chore

#4626 chore: fix engine variant for mac targets
  extensions/engine-management-extension/src/utils.ts
Labels: type: chore

#4627 fix: render slow on device label
  extensions/yarn.lock
  web/containers/ModelLabel/index.tsx
Labels: type: bug

#4630 chore: bump cortex.cpp to the rc5 to address race condition issue
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4634 chore: beta version not publish to github
  .github/workflows/jan-electron-build-beta.yml
  .github/workflows/template-build-jan-server.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-build-windows-x64.yml
Labels: type: chore

#4639 fix: filter out variant engine
  web/screens/Settings/Engines/LocalEngineSettings.tsx
Labels: type: bug

#4644 fix: rename google gemini into gemini
  web/utils/modelEngine.ts
Labels: type: bug

#4645 fix: model dropdown icon miss align
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#4648 fix: error setting remote engine
  extensions/yarn.lock
  web/containers/ErrorMessage/index.tsx
  web/utils/modelEngine.ts
Labels: type: bug

#4646 chore: remote engine error handling
  core/src/browser/extensions/engines/OAIEngine.test.ts
  core/src/browser/extensions/engines/OAIEngine.ts
  core/src/browser/extensions/engines/helpers/sse.test.ts
  core/src/browser/extensions/engines/helpers/sse.ts
  core/src/types/model/modelEntity.ts
  extensions/engine-management-extension/models/anthropic.json
  extensions/engine-management-extension/models/cohere.json
  extensions/engine-management-extension/models/mistral.json
  extensions/engine-management-extension/models/nvidia.json
  extensions/engine-management-extension/models/openai.json
  extensions/engine-management-extension/resources/anthropic.json
  extensions/engine-management-extension/src/index.ts
  extensions/inference-cortex-extension/bin/version.txt
  web/containers/AutoLink/index.tsx
  web/utils/componentSettings.ts
Labels: type: chore

#4650 fix: gpu hardware state
  extensions/yarn.lock
  web/screens/Settings/Hardware/index.tsx
Labels: type: bug

#4654 chore: bump cortex version and fix misc UI issues
  extensions/inference-cortex-extension/bin/version.txt
  web/screens/LocalServer/LocalServerRightPanel/index.tsx
  web/utils/modelEngine.ts
Labels: type: chore

#4656 chore: bump cortex-cpp rc10
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4631 feat: app updater with changelog
  core/src/types/api/index.ts
  electron/handlers/native.ts
  electron/handlers/update.ts
  extensions/yarn.lock
  web/containers/Layout/index.tsx
  web/containers/ModalAppUpdaterChangelog/index.tsx
  web/containers/ModalAppUpdaterNotAvailable/index.tsx
  web/containers/Providers/AppUpdateListener.tsx
  web/helpers/atoms/App.atom.ts
  web/hooks/useGetLatestRelease.ts
  web/styles/components/marked.scss
Labels: type: feature request

#4660 chore: disable turn off local engine llamacpp
  web/screens/Settings/Engines/LocalEngineItem.tsx
Labels: type: bug, type: chore

#4661 chore: update ui width text field slider, and conditional button copy based value length
  web/containers/SliderRightPanel/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
Labels: type: chore

#4662 fix: app stucks at generating response state after stopped the previous session
  extensions/engine-management-extension/models/openai.json
  extensions/inference-cortex-extension/bin/version.txt
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: bug

#4672 chore: Sync Server Playground Schema with Latest Cortex.cpp API Specs
  server/cortex.json
Labels: type: chore

#4677 chore: bump cortex.cpp 1.0.10-rc13
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4678 fix: reload app when gpu change
  extensions/yarn.lock
  web/screens/Settings/Hardware/index.tsx
Labels: type: bug

#4679 chore: bump cortex release 1.0.10
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4680 chore: fix engine template for remote providers
  extensions/engine-management-extension/resources/anthropic.json
  extensions/engine-management-extension/resources/cohere.json
Labels: type: chore

#4695 fix: format compact number utils
  docs/src/utils/format.ts
Labels: type: bug, type: chore

#4696 chore: Hub UI and markdown CSS
  web/screens/Hub/ModelList/ModelHeader/index.tsx
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
Labels: type: chore

#4698 feat: allow users to refresh cloud model list
  electron/package.json
  extensions/inference-cortex-extension/bin/version.txt
  web/containers/Loader/Spinner.tsx
  web/hooks/useEngineManagement.ts
  web/package.json
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
Labels: type: feature request

#4708 chore: change app logo for jan beta and nightly version
  .github/workflows/jan-electron-build-beta.yml
  .github/workflows/jan-electron-build-nightly.yml
  electron/icons/jan-beta-512x512.png
  electron/icons/jan-beta-tray.png
  electron/icons/jan-beta-tray@2x.png
  electron/icons/jan-beta.ico
  electron/icons/jan-beta.png
  electron/icons/jan-nightly-512x512.png
  electron/icons/jan-nightly-tray.png
  electron/icons/jan-nightly-tray@2x.png
  electron/icons/jan-nightly.ico
  electron/icons/jan-nightly.png
Labels: type: chore

#4707 feat: Jan Model Hub should stay updated
  extensions/inference-cortex-extension/bin/version.txt
  extensions/model-extension/jest.config.js
  extensions/model-extension/package.json
  extensions/model-extension/src/cortex.ts
  extensions/model-extension/src/index.test.ts
  extensions/model-extension/src/index.ts
  extensions/model-extension/src/legacy/model-json.test.ts
  extensions/model-extension/src/migration.test.ts
  extensions/model-extension/tsconfig.json
  extensions/model-extension/vite.config.ts
  web/utils/modelEngine.ts
Labels: type: feature request, category: model hub

#4711 feat: preserve token speed in the thread
  web/containers/Providers/ModelHandler.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
Labels: type: feature request

#4712 chore: streaming should be turned on by default
  extensions/engine-management-extension/models/cohere.json
Labels: type: chore

#4713 fix: should disable start model button when there is a model is loading
  web/screens/Settings/MyModels/MyModelList/index.tsx
Labels: type: bug

#4709 chore: change app logo for build nightly
  .github/workflows/jan-electron-build-beta.yml
  .github/workflows/jan-electron-build-nightly.yml
  .github/workflows/template-build-linux-x64.yml
  .github/workflows/template-build-macos.yml
  .github/workflows/template-build-windows-x64.yml
Labels: type: chore

#4714 feat: Jan Model Hub filter options and responsiveness
  joi/src/core/Slider/Slider.test.tsx
  joi/src/core/Slider/index.tsx
  web/screens/Hub/ModelFilter/ContextLength/index.tsx
  web/screens/Hub/ModelFilter/ModelSize/index.tsx
  web/screens/Hub/ModelList/index.tsx
  web/screens/Hub/index.tsx
  web/screens/Settings/MyModels/index.tsx
Labels: type: feature request

#4715 chore: sticky model hub filter panel
  web/screens/Hub/index.tsx
  web/screens/LocalServer/LocalServerCenterPanel/index.tsx
Labels: type: chore

#4719 chore: migrate engine settings on update
  core/src/browser/extension.ts
  extensions/engine-management-extension/package.json
  extensions/engine-management-extension/resources/anthropic.json
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/engine-management-extension/src/@types/global.d.ts
  extensions/engine-management-extension/src/index.test.ts
  extensions/engine-management-extension/src/index.ts
  extensions/engine-management-extension/src/node/index.test.ts
  extensions/model-extension/package.json
  extensions/model-extension/src/index.ts
  web/env-example
Labels: type: chore

#4721 enhancement: update pixelated icon on windows platform
  electron/icons/icon.ico
  extensions/yarn.lock
  yarn.lock
Labels: type: enhancement

#4722 chore: fix model hub sorting
  web/screens/Hub/index.tsx
Labels: type: chore

#4723 chore: enhance onboarding screen's models
  .husky/pre-commit
  web/containers/ModelDropdown/index.tsx
  web/screens/Settings/SettingLeftPanel/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.test.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/utils/model.ts
Labels: type: chore

#4726 enhancement: scrollbar setting options
  extensions/yarn.lock
  joi/src/core/ScrollArea/styles.scss
  web/containers/Layout/index.tsx
  web/containers/LeftPanelContainer/index.tsx
  web/containers/ListContainer/index.tsx
  web/containers/ModelDropdown/index.tsx
  web/containers/RightPanelContainer/index.tsx
  web/containers/ServerLogs/index.tsx
  web/helpers/atoms/Setting.atom.ts
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Hub/index.tsx
  web/screens/Settings/Advanced/ProxySettings/index.tsx
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/Appearance/index.tsx
  web/screens/Settings/CoreExtensions/index.tsx
  web/screens/Settings/Engines/LocalEngineSettings.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
  web/screens/Settings/Engines/index.tsx
  web/screens/Settings/Hardware/index.tsx
  web/screens/Settings/Hotkeys/index.tsx
  web/screens/Settings/MyModels/index.tsx
  web/screens/Settings/Privacy/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/styles/base/global.scss
Labels: type: enhancement

#4730 refactor: clean up legacy predefined models
  extensions/inference-cortex-extension/resources/models/aya-23-35b/model.json
  extensions/inference-cortex-extension/resources/models/aya-23-8b/model.json
  extensions/inference-cortex-extension/resources/models/bakllava-1/model.json
  extensions/inference-cortex-extension/resources/models/codeninja-1.0-7b/model.json
  extensions/inference-cortex-extension/resources/models/codestral-22b/model.json
  extensions/inference-cortex-extension/resources/models/command-r-34b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-coder-1.3b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-coder-34b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-llama-70b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-llama-8b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-1.5b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-14b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-32b/model.json
  extensions/inference-cortex-extension/resources/models/deepseek-r1-distill-qwen-7b/model.json
  extensions/inference-cortex-extension/resources/models/gemma-1.1-2b/model.json
  extensions/inference-cortex-extension/resources/models/gemma-1.1-7b/model.json
  extensions/inference-cortex-extension/resources/models/gemma-2-27b/model.json
  extensions/inference-cortex-extension/resources/models/gemma-2-2b/model.json
  extensions/inference-cortex-extension/resources/models/gemma-2-9b/model.json
  extensions/inference-cortex-extension/resources/models/llama2-chat-70b/model.json
  extensions/inference-cortex-extension/resources/models/llama2-chat-7b/model.json
  extensions/inference-cortex-extension/resources/models/llama3-8b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/llama3-hermes-8b/model.json
  extensions/inference-cortex-extension/resources/models/llama3.1-70b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/llama3.1-8b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/llama3.2-1b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/llama3.2-3b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/llamacorn-1.1b/model.json
  extensions/inference-cortex-extension/resources/models/llava-13b/model.json
  extensions/inference-cortex-extension/resources/models/llava-7b/model.json
  extensions/inference-cortex-extension/resources/models/mistral-ins-7b-q4/model.json
  extensions/inference-cortex-extension/resources/models/mixtral-8x7b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/noromaid-7b/model.json
  extensions/inference-cortex-extension/resources/models/openchat-3.5-7b/model.json
  extensions/inference-cortex-extension/resources/models/phi3-3.8b/model.json
  extensions/inference-cortex-extension/resources/models/phi3-medium/model.json
  extensions/inference-cortex-extension/resources/models/phind-34b/model.json
  extensions/inference-cortex-extension/resources/models/qwen-7b/model.json
  extensions/inference-cortex-extension/resources/models/qwen2-7b/model.json
  extensions/inference-cortex-extension/resources/models/qwen2.5-14b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/qwen2.5-32b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/qwen2.5-72b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/qwen2.5-7b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/qwen2.5-coder-14b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/qwen2.5-coder-32b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/qwen2.5-coder-7b-instruct/model.json
  extensions/inference-cortex-extension/resources/models/stable-zephyr-3b/model.json
  extensions/inference-cortex-extension/resources/models/stealth-v1.2-7b/model.json
  extensions/inference-cortex-extension/resources/models/tinyllama-1.1b/model.json
  extensions/inference-cortex-extension/resources/models/trinity-v1.2-7b/model.json
  extensions/inference-cortex-extension/resources/models/vistral-7b/model.json
  extensions/inference-cortex-extension/resources/models/wizardcoder-13b/model.json
  extensions/inference-cortex-extension/resources/models/yi-34b/model.json
  extensions/inference-cortex-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/src/@types/global.d.ts
  extensions/inference-cortex-extension/src/index.ts
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
Labels: type: chore

#4731 fix: flow app updater manual check from native menu
  electron/handlers/update.ts
  electron/utils/menu.ts
Labels: type: bug

#4734 chore: update hub UI
  web/containers/ModelDownloadButton/index.tsx
  web/screens/Hub/ModelList/ModelHeader/index.tsx
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Hub/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
  web/styles/components/code-block.scss
  web/styles/components/marked.scss
  web/styles/components/message.scss
Labels: type: chore

#4733 chore: correct channel name to ask for help
  docs/src/pages/docs/troubleshooting.mdx
Labels: type: chore

#4736 enhancement: improve chat thread
  web/containers/Providers/ModelHandler.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
  web/utils/datetime.test.ts
  web/utils/datetime.ts
Labels: type: enhancement

#4737 fix: chat body scrollbar
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/MarkdownTextMessage.tsx
  web/styles/base/global.scss
  yarn.lock
Labels: type: bug

#4738 fix: onboarding screen should show persisted cloud providers
  electron/.eslintrc.js
  electron/tsconfig.json
  extensions/engine-management-extension/src/index.ts
  extensions/inference-cortex-extension/bin/version.txt
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnboardingScreen/index.test.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnboardingScreen/index.tsx
  web/screens/Thread/index.tsx
Labels: type: bug

#4741 chore: remove hard coded recommendation models and use cortexso featured tags
  extensions/model-extension/resources/default.json
  extensions/model-extension/src/index.ts
  web/containers/ModelDropdown/index.tsx
  web/hooks/useModelSource.ts
  web/screens/Hub/ModelPage/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnboardingScreen/index.test.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnboardingScreen/index.tsx
  web/utils/model.ts
  web/utils/modelSource.ts
Labels: type: chore

#4739 fix: hub ui no result search found
  web/screens/Hub/ModelList/index.tsx
  web/screens/Hub/index.tsx
Labels: type: bug

#4747 fix: correct default engine variant setup on first launch
  extensions/engine-management-extension/src/utils.test.ts
  extensions/engine-management-extension/src/utils.ts
  web/containers/ModelLabel/ModelLabel.test.tsx
  web/containers/ModelLabel/index.tsx
  web/hooks/useSettings.ts
  web/screens/Hub/ModelList/ModelHeader/index.tsx
  web/screens/Settings/Advanced/index.test.tsx
  web/screens/Settings/Privacy/index.test.tsx
Labels: type: bug

#4750 fix: cannot click dropdown appearance
  joi/src/core/Select/index.tsx
  web/screens/Settings/Appearance/index.tsx
Labels: type: bug

#4751 fix: app check available update
  electron/main.ts
Labels: type: bug

#4752 fix: some endpoints are invisible
  server/cortex.json
  server/index.ts
Labels: type: bug

#4754 chore: correct model author with new cortexso update
  core/src/types/model/modelSource.ts
  extensions/inference-cortex-extension/bin/version.txt
  extensions/model-extension/resources/default.json
  web/screens/Hub/ModelList/ModelHeader/index.tsx
  web/screens/Hub/ModelList/ModelItem/index.tsx
  web/screens/Hub/ModelPage/index.tsx
Labels: type: chore

#4756 chore: handle list number and disc readme hgf
  web/screens/Hub/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
  web/styles/components/marked.scss
Labels: type: chore

#4762 fix: first message padding is off
  web/screens/Thread/ThreadCenterPanel/ChatBody/index.tsx
  web/screens/Thread/ThreadCenterPanel/TextMessage/index.tsx
Labels: type: bug
