Repository menloresearch/jan, pull requests merged in 2025-06, with the labels that each got.

#5167 chore: check app update via general setting
  web-app/src/containers/dialogs/AppUpdater.tsx
  web-app/src/routes/settings/general.tsx
Labels: type: chore

#5175 fix: handle undefined search index in getFilteredThreads
  web-app/src/hooks/useThreads.ts
Labels: type: bug

#5178 chore: enhance MCP permission settings
  src-tauri/src/core/mcp.rs
  web-app/src/routes/settings/mcp-servers.tsx
Labels: type: chore

#5181 fix: avatar assistants render
  extensions/assistant-extension/src/index.ts
  web-app/src/containers/AvatarEmoji.tsx
  web-app/src/containers/DropdownAssistant.tsx
  web-app/src/containers/ThreadContent.tsx
  web-app/src/containers/dialogs/AddEditAssistant.tsx
  web-app/src/routes/assistant.tsx
Labels: type: bug

#5184 ci: tauri build macos
  .github/workflows/template-tauri-build-macos.yml
  .github/workflows/template-tauri-build-windows-x64.yml
  src-tauri/tauri.bundle.windows.nsis.template
  src-tauri/tauri.conf.json
  web-app/src/containers/DownloadManegement.tsx
  web-app/src/containers/dialogs/AppUpdater.tsx
  web-app/src/hooks/useAppUpdater.ts
  web-app/src/routes/settings/general.tsx
Labels: type: ci

#5193 feat: Jan API Server should have API Key setting
  src-tauri/src/core/cmd.rs
  src-tauri/src/core/server.rs
  web-app/src/containers/ApiKeyInput.tsx
  web-app/src/hooks/useLocalApiServer.ts
  web-app/src/routes/settings/local-api-server.tsx
Labels: type: feature request

#5197 feat: integrate fuzzy search into model dropdown
  web-app/src/containers/DropdownModelProvider.tsx
Labels: type: feature request

#5198 fix: truncate tool name
  web-app/src/containers/DropdownToolsAvailable.tsx
  web-app/src/routes/hub.tsx
Labels: type: bug

#5199 fix: dropdown model position
  web-app/src/containers/DropdownModelProvider.tsx
Labels: type: bug

#5202 chore: thinking block auto collapse when streaming finish
  web-app/src/containers/ThinkingBlock.tsx
  web-app/src/containers/ThreadContent.tsx
  web-app/vite.config.ts
Labels: type: chore

#5201 feat: store last use model create thread
  web-app/src/constants/localStorage.ts
  web-app/src/containers/ChatInput.tsx
  web-app/src/containers/DropdownModelProvider.tsx
  web-app/src/containers/dialogs/AppUpdater.tsx
Labels: type: feature request

#5203 fix: force provider avatar to render in high quality
  web-app/src/containers/ProvidersAvatar.tsx
Labels: type: bug

#5206 fix: load threads from api instead of states
  web-app/src/providers/DataProvider.tsx
Labels: type: bug

#5212 fix: avoid spamming server restarts
  web-app/src/hooks/useMCPServers.ts
  web-app/src/routes/settings/mcp-servers.tsx
Labels: type: bug

#5218 chore: force windows to default alpha color 1
  web-app/src/containers/ColorPickerAppAccentColor.tsx
  web-app/src/containers/ColorPickerAppBgColor.tsx
  web-app/src/containers/ColorPickerAppDestructiveColor.tsx
  web-app/src/containers/ColorPickerAppMainView.tsx
  web-app/src/containers/ColorPickerAppPrimaryColor.tsx
  web-app/src/hooks/useAppearance.ts
  web-app/src/providers/AppearanceProvider.tsx
Labels: type: chore

#5225 chore: add toggle loading sever MCP
  web-app/src/components/ui/switch.tsx
  web-app/src/containers/DropdownModelProvider.tsx
  web-app/src/hooks/useMCPServers.ts
  web-app/src/routes/settings/mcp-servers.tsx
Labels: type: chore

#5231 chore: fix model settings are not applied accordingly on change
  extensions/inference-cortex-extension/resources/default_settings.json
  extensions/inference-cortex-extension/src/index.ts
  web-app/src/containers/ChatInput.tsx
  web-app/src/hooks/useChat.ts
  web-app/src/lib/completion.ts
  web-app/src/services/providers.ts
Labels: type: chore

#5237 chore: streaming tool output
  web-app/src/containers/RenderMarkdown.tsx
  web-app/src/containers/StreamingContent.tsx
  web-app/src/containers/ThreadContent.tsx
  web-app/src/containers/ToolCallBlock.tsx
  web-app/src/hooks/useAppState.ts
  web-app/src/hooks/useChat.ts
  web-app/src/lib/completion.ts
  web-app/src/routes/__root.tsx
  web-app/src/types/message.d.ts
Labels: type: chore

#5239 chore: experimental tag mcp
  web-app/src/routes/settings/mcp-servers.tsx
Labels: type: chore

#5241 fix: could not add custom models
  web-app/src/lib/completion.ts
Labels: type: bug

#5245 fix: update style cortex dialog
  web-app/src/containers/dialogs/CortexFailureDialog.tsx
Labels: type: bug

#5249 fix: avoid persisting threads and messages on local storage
  web-app/src/hooks/useMessages.ts
  web-app/src/hooks/useThreads.ts
Labels: type: bug

#5258 fix: replace close think tag from text segment
  web-app/src/containers/ThreadContent.tsx
Labels: type: bug

#5259 fix: recheck tools approval state
  web-app/src/hooks/useToolApproval.ts
Labels: type: bug

#5261 chore: enable shortcut zoom
  src-tauri/capabilities/default.json
  src-tauri/tauri.conf.json
  web-app/src/routes/settings/shortcuts.tsx
Labels: type: chore

#5263 fix: thinking block
  web-app/src/containers/ThreadContent.tsx
  web-app/src/routes/hub.tsx
Labels: type: bug

#5269 fix: glitch download from onboarding
  web-app/src/routes/hub.tsx
Labels: type: bug

#5276 ✨enhancement: masking sensitive values in environment variables
  web-app/src/routes/settings/mcp-servers.tsx
Labels: type: bug, type: enhancement

#5280 chore: add a place to download beta apps
  docs/src/pages/docs/desktop/_meta.json
  docs/src/pages/docs/desktop/beta.mdx
Labels: type: chore

#5295 fix: update jan doc
  docs/src/components/Home/Hero/index.tsx
Labels: type: bug

#5311 chore: correct binary name for stable version (#5303)
  .github/workflows/template-tauri-build-windows-x64.yml
Labels: type: chore

#5317 ci: enable devtool on prod build
  .github/workflows/template-tauri-build-linux-x64.yml
  .github/workflows/template-tauri-build-macos.yml
  .github/workflows/template-tauri-build-windows-x64.yml
Labels: type: ci

#5354 fix: built in models capabilities
  web-app/src/services/providers.ts
Labels: type: bug

#5357 fix: update broken installation url
  README.md
Labels: type: bug

#5365 fix: download link
  docs/src/components/Download/CardDownload.tsx
  docs/src/components/DropdownDownload/index.tsx
Labels: type: bug

#5366 fix: remove log
  docs/src/components/DropdownDownload/index.tsx
Labels: type: bug
