Repository menloresearch/jan, pull requests merged in 2025-01, with the labels that each got.

#4379 fix: if the default engine isn't installed, the app should reset it
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/engine-management-extension/src/index.ts
  extensions/yarn.lock
Labels: type: bug

#4382 fix: should not disable Vulkan support option
  web/screens/Settings/Advanced/index.tsx
Labels: type: bug

#4383 chore: reduce test build steps
  .github/workflows/jan-electron-linter-and-test.yml
  electron/playwright.config.ts
Labels: type: chore

#4386 chore: add cpu_threads settings in cortex extension
  extensions/inference-cortex-extension/bin/version.txt
  extensions/inference-cortex-extension/resources/default_settings.json
  extensions/inference-cortex-extension/src/index.ts
Labels: type: chore

#4387 fix: enable default opt in analytic
  web/helpers/atoms/Setting.atom.ts
Labels: type: bug, type: enhancement

#4390 fix: send event opt out
  extensions/inference-cortex-extension/resources/default_settings.json
  web/containers/Layout/index.tsx
Labels: type: bug

#4394 fix: revert back product analytic with default opt-out
  web/containers/Layout/index.tsx
  web/helpers/atoms/Setting.atom.ts
Labels: type: bug

#4397 fix: max_tokens revert back to 8192 automatically when creating a new thread
  web/hooks/useCreateNewThread.ts
Labels: type: bug

#4399 fix: input scrolls to the bottom when set the caret to the top
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  web/screens/Thread/ThreadCenterPanel/ChatInput/RichTextEditor.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/index.test.tsx
Labels: type: bug

#4391 chore: add flathub submission
  ai.menlo.jan.desktop
  ai.menlo.jan.metainfo.xml
Labels: type: chore

#4405 chore: bump latest cortex release 1.0.8
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4404 enhancement: instruction textarea using autoresize
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: enhancement

#4409 chore: resolve hotfix from main into dev
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rollup.config.ts
Labels: type: chore

#4412 chore: Update Jan Docs (2)
  docs/src/pages/docs/_assets/jan-app.png
  docs/src/pages/docs/_assets/model-management-04.png
  docs/src/pages/docs/_assets/model-management-05.png
  docs/src/pages/docs/_assets/model-management-06.png
  docs/src/pages/docs/_assets/model-management-07.png
  docs/src/pages/docs/_assets/settings-01.png
  docs/src/pages/docs/_assets/settings-02.png
  docs/src/pages/docs/_assets/settings-03.png
  docs/src/pages/docs/_assets/settings-04.png
  docs/src/pages/docs/_assets/settings-05.png
  docs/src/pages/docs/_assets/settings-06.png
  docs/src/pages/docs/_assets/settings-07.png
  docs/src/pages/docs/_assets/settings-08.png
  docs/src/pages/docs/_assets/settings-09.png
  docs/src/pages/docs/_assets/settings-10.png
  docs/src/pages/docs/_assets/settings-11.png
  docs/src/pages/docs/_assets/settings-12.png
  docs/src/pages/docs/_assets/settings-13.png
  docs/src/pages/docs/_assets/settings-14.png
  docs/src/pages/docs/_assets/settings-15.png
  docs/src/pages/docs/_assets/settings-17.png
  docs/src/pages/docs/_assets/settings-18.png
  docs/src/pages/docs/_assets/trouble-shooting-01.png
  docs/src/pages/docs/_assets/trouble-shooting-02.png
  docs/src/pages/docs/desktop/linux.mdx
  docs/src/pages/docs/desktop/mac.mdx
  docs/src/pages/docs/desktop/windows.mdx
  docs/src/pages/docs/index.mdx
  docs/src/pages/docs/models/manage-models.mdx
  docs/src/pages/docs/quickstart.mdx
  docs/src/pages/docs/tools/retrieval.mdx
Labels: type: chore

#4418 chore: support request headers template
  core/src/types/engine/index.ts
  web/containers/ModelDropdown/index.tsx
  web/screens/Settings/Engines/ModalAddRemoteEngine.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
Labels: type: chore

#4425 fix: add per_page params on github releases endpoint
  docs/src/pages/index.mdx
Labels: type: bug

#4437 fix: load model fail on windows
  electron/package.json
  extensions/engine-management-extension/package.json
  extensions/inference-cortex-extension/src/node/index.ts
  package.json
Labels: type: bug

#4438 chore: bump engine version to 0.1.43
  extensions/inference-cortex-extension/rolldown.config.mjs
Labels: type: chore

#4440 fix: sass legacy warn
  electron/package.json
  joi/package.json
  joi/rollup.config.mjs
  yarn.lock
Labels: type: bug, type: chore

#4444 chore: resolve button state download engine variant
  web/screens/Settings/Engines/Settings.tsx
Labels: type: chore

#4447 fix: ci npm publish
  .github/workflows/publish-npm-core.yml
  .github/workflows/publish-npm-joi.yml
Labels: type: bug

#4451 fix: incorrect default max_tokens set - legacy issue
  extensions/inference-cortex-extension/bin/version.txt
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#4453 chore: deprecate tensorrt-llm extension
  extensions/tensorrt-llm-extension/README.md
  extensions/tensorrt-llm-extension/jest.config.js
  extensions/tensorrt-llm-extension/package.json
  extensions/tensorrt-llm-extension/resources/models.json
  extensions/tensorrt-llm-extension/rolldown.config.mjs
  extensions/tensorrt-llm-extension/src/@types/global.d.ts
  extensions/tensorrt-llm-extension/src/index.test.ts
  extensions/tensorrt-llm-extension/src/index.ts
  extensions/tensorrt-llm-extension/src/node/index.ts
  extensions/tensorrt-llm-extension/tsconfig.json
Labels: type: chore

#4452 chore: add chat completion field form add remote engine
  electron/package.json
  extensions/engine-management-extension/resources/anthropic.json
  extensions/engine-management-extension/resources/cohere.json
  extensions/engine-management-extension/resources/groq.json
  extensions/engine-management-extension/resources/martian.json
  extensions/engine-management-extension/resources/mistral.json
  extensions/engine-management-extension/resources/nvidia.json
  extensions/engine-management-extension/resources/openai.json
  extensions/engine-management-extension/resources/openrouter.json
  extensions/yarn.lock
  web/screens/Settings/Engines/ModalAddRemoteEngine.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
Labels: type: chore

#4455 fix: hide placeholder python engine and unsupported openai o1 system …
  extensions/engine-management-extension/resources/openai.json
  web/screens/Settings/Engines/index.tsx
  web/screens/Settings/SettingLeftPanel/index.tsx
Labels: type: bug

#4454 fix: empty response on some generation attempts
  web/hooks/useSendChatMessage.ts
Labels: type: bug

#4457 feat: move cortex extension settings to local engine page
  web/screens/Settings/Engines/LocalEngineSettings.tsx
  web/screens/Settings/Engines/index.tsx
  web/screens/Settings/ExtensionSetting/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/SettingDetailTextInputItem/index.tsx
  web/screens/Settings/SettingDetail/SettingDetailItem/index.tsx
  web/screens/Settings/SettingDetail/index.tsx
  web/screens/Settings/SettingLeftPanel/index.tsx
Labels: type: feature request

#4458 fix: mismatch NGL number between UI and model settings
  web/utils/componentSettings.ts
Labels: type: bug

#4459 fix: windows uninstall not force close app
  .github/scripts/rename-uninstaller.sh
  electron/scripts/uninstaller.nsh
  extensions/yarn.lock
  yarn.lock
Labels: type: bug

#4463 chore: fix engine description hyperlink display
  web/screens/Settings/Engines/LocalEngineSettings.tsx
Labels: type: chore

#4465 fix: bump engine version - update engine variant symlink and copy CUDA dependencies
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/engine-management-extension/src/node/index.ts
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/src/node/index.ts
  web/containers/Layout/BottomPanel/DownloadingState/index.tsx
  web/screens/Settings/Engines/LocalEngineSettings.tsx
Labels: type: bug

#4467 chore: bump cortex server rc3
  extensions/inference-cortex-extension/bin/version.txt
Labels: type: chore

#4470 fix: app crashes on select cloud model first time onboarding
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
Labels: type: bug

#4475 fix: remote engine revamp issues
  web/containers/ModelDropdown/index.tsx
  web/containers/Providers/ModelHandler.tsx
  web/hooks/useActiveModel.ts
  web/hooks/useConfigurations.ts
  web/hooks/useRecommendedModel.ts
  web/hooks/useStarterScreen.ts
  web/screens/Hub/ModelList/index.tsx
  web/screens/LocalServer/LocalServerLeftPanel/index.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
  web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.tsx
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
Labels: type: bug

#4476 chore: refactor - clean out useEngines - mutate swr to update
  extensions/engine-management-extension/models/anthropic.json
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
  web/containers/ModelDropdown/index.tsx
  web/containers/Providers/DataLoader.tsx
  web/containers/Providers/ModelHandler.tsx
  web/helpers/atoms/Engines.atom.ts
  web/hooks/useEngines.ts
  web/hooks/useRecommendedModel.ts
  web/hooks/useStarterScreen.ts
  web/screens/Hub/ModelList/index.tsx
  web/screens/Settings/Engines/index.tsx
  web/screens/Settings/MyModels/MyModelList/index.tsx
  web/screens/Settings/SettingDetail/index.tsx
  web/screens/Settings/SettingLeftPanel/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyThread/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: chore

#4477 chore: fix remote engines request templates
  extensions/engine-management-extension/models/martian.json
  extensions/engine-management-extension/models/mistral.json
  extensions/engine-management-extension/models/nvidia.json
  extensions/engine-management-extension/models/openrouter.json
  extensions/engine-management-extension/resources/anthropic.json
  extensions/engine-management-extension/resources/mistral.json
  web/utils/messageRequestBuilder.ts
Labels: type: chore

#4486 chore: sync from main into dev
  core/src/browser/extensions/engines/helpers/sse.ts
  extensions/engine-management-extension/models/anthropic.json
  extensions/engine-management-extension/models/martian.json
  extensions/engine-management-extension/models/mistral.json
  extensions/engine-management-extension/models/nvidia.json
  extensions/engine-management-extension/models/openrouter.json
  extensions/engine-management-extension/resources/anthropic.json
  extensions/engine-management-extension/resources/mistral.json
  extensions/inference-cortex-extension/bin/version.txt
  web/containers/Layout/BottomPanel/SystemMonitor/TableActiveModel/index.tsx
  web/containers/ModelDropdown/index.tsx
  web/containers/Providers/DataLoader.tsx
  web/containers/Providers/ModelHandler.tsx
  web/containers/Providers/SWRConfigProvider.tsx
  web/containers/Providers/index.tsx
  web/helpers/atoms/Engines.atom.ts
  web/hooks/useActiveModel.ts
  web/hooks/useConfigurations.ts
  web/hooks/useEngines.ts
  web/hooks/useRecommendedModel.ts
  web/hooks/useStarterScreen.ts
  web/screens/Hub/ModelList/index.tsx
  web/screens/LocalServer/LocalServerLeftPanel/index.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
  web/screens/Settings/Engines/index.tsx
  web/screens/Settings/MyModels/MyModelList/index.tsx
  web/screens/Settings/MyModels/index.tsx
  web/screens/Settings/SettingDetail/index.tsx
  web/screens/Settings/SettingLeftPanel/index.tsx
  web/screens/Thread/ThreadCenterPanel/AssistantSetting/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/EmptyThread/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatBody/OnDeviceStarterScreen/index.tsx
  web/screens/Thread/ThreadCenterPanel/ChatInput/index.tsx
  web/screens/Thread/ThreadCenterPanel/LoadModelError/index.tsx
  web/screens/Thread/ThreadRightPanel/index.tsx
  web/utils/messageRequestBuilder.ts
Labels: type: chore

#4498 chore: bump llama.cpp to the latest version
  extensions/inference-cortex-extension/download.bat
  extensions/inference-cortex-extension/download.sh
  extensions/inference-cortex-extension/rollup.config.ts
Labels: type: chore

#4500 fix: Correct index for Windows download button
  docs/src/components/DropdownDownload/index.tsx
Labels: type: bug

#4504 fix: thread title summarization doesn't work well on reasoning models
  web/containers/Providers/ModelHandler.tsx
Labels: type: bug

#4507 fix: typo meta description
  docs/src/pages/index.mdx
Labels: type: bug

#4506 chore: ignore external contributors
  .github/workflows/auto-assign-author.yml
Labels: type: chore

#4516 chore: Update outdated integrations docs
  docs/src/pages/integrations/workflow-automation/raycast.mdx
Labels: type: chore

#4521 enhancement: minor ui refinements
  extensions/yarn.lock
  web/containers/CenterPanelContainer/index.tsx
  web/containers/Layout/TopPanel/index.tsx
  web/containers/LeftPanelContainer/index.tsx
  web/containers/Loader/ModelReload.tsx
  web/containers/Providers/index.tsx
  web/containers/RightPanelContainer/index.test.tsx
  web/containers/RightPanelContainer/index.tsx
  web/screens/Settings/Advanced/ProxySettings/index.tsx
  web/screens/Settings/Engines/index.tsx
Labels: type: enhancement

#4524 enhancement: create new thread with last chosen model
  web/hooks/useCreateNewThread.ts
Labels: type: enhancement

#4523 enhancement: added space scroll remote engine setting
  web/containers/Layout/TopPanel/index.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
Labels: type: enhancement

#4528 enhancement: Update app layout with an expanded system monitor
  web/containers/MainViewContainer/index.tsx
  web/screens/Thread/ThreadCenterPanel/index.tsx
Labels: type: enhancement

#4534 feat: allow users to add remote models
  core/src/browser/extensions/enginesManagement.ts
  core/src/types/model/modelEntity.ts
  web/hooks/useEngineManagement.ts
  web/screens/Settings/Engines/ModalAddModel.tsx
  web/screens/Settings/Engines/RemoteEngineSettings.tsx
Labels: type: feature request

#4533 enhancement: update responsive setting and my model page
  web/screens/Settings/Advanced/index.tsx
  web/screens/Settings/MyModels/index.tsx
Labels: type: enhancement

#4530 feat: Standardize inline error messages
  web/containers/ErrorMessage/index.test.tsx
  web/containers/ErrorMessage/index.tsx
Labels: type: feature request

#4535 fix: broken range slider ctx length
  web/screens/Thread/ThreadRightPanel/index.tsx
Labels: type: bug

#4536 chore: sync cortex engine version
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/rolldown.config.mjs
Labels: type: chore

#4537 fix: app does not reload model when prompt template is updated
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/inference-cortex-extension/rolldown.config.mjs
  web/containers/ModelDropdown/index.tsx
Labels: type: bug

#4541 chore: ensure app Id is maintained
  core/src/types/config/appConfigEntity.ts
  web/containers/Layout/index.tsx
  web/hooks/useFactoryReset.ts
  web/utils/settings.ts
Labels: type: chore

#4542 chore: rotate model hub banner on app launch until set
  web/helpers/atoms/App.atom.ts
  web/screens/Hub/index.tsx
Labels: type: chore

#4547 feat: pull models list when setting up a new remote engine
  core/src/types/model/modelEntity.ts
  extensions/engine-management-extension/rolldown.config.mjs
  extensions/engine-management-extension/src/@types/global.d.ts
  extensions/engine-management-extension/src/index.ts
Labels: type: feature request

#4548 chore: align item menu action error message
  extensions/yarn.lock
  web/containers/ErrorMessage/index.tsx
Labels: type: chore
